import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase/server-client";
import { bulkIncreaseTradeInCosts, createTradeInCost, deleteTradeInCost, toggleTradeInCost, updateTradeInCost } from "./actions";
type Props={searchParams:Promise<{q?:string;category?:string}>};
export default async function TradeInCostsPage({searchParams}:Props){const{q,category}=await searchParams;const supabase=await createSupabaseServerClient();const{data}=await supabase.from("trade_in_cost_references").select("code,label,amount,category,selectable,is_active,updated_at").order("category").order("sort_order").order("label");const all=data??[];const needle=(q??"").trim().toLocaleLowerCase("tr-TR");const costs=all.filter(x=>(!category||x.category===category)&&(!needle||[x.code,x.label,x.category].some(v=>String(v).toLocaleLowerCase("tr-TR").includes(needle))));return <main className="adminShell adminShellWide"><header className="adminTopbar"><div><h1 className="adminPageTitle">Masraf Referansları</h1><p className="adminLead">Takas fiyatından düşülecek maliyetleri ara, filtrele ve yönet.</p></div><Link className="adminButton adminButtonSecondary" href="/admin/trade-in">Cihaz Fiyatları</Link></header>
<section className="adminDashboardCard"><form className="adminListingForm" method="get"><label className="adminField">Ara<input name="q" defaultValue={q??""} placeholder="Kalem adı veya kod"/></label><label className="adminField">Grup<select name="category" defaultValue={category??""}><option value="">Tümü</option><option value="system">Sistem</option><option value="repair">Onarım / değişen</option><option value="accessory">Kutu / aksesuar</option></select></label><div className="adminFormActions"><button className="adminButton">Filtrele</button><Link className="adminButton adminButtonSecondary" href="/admin/trade-in/costs">Temizle</Link></div></form><p className="adminLead">{costs.length} / {all.length} kalem gösteriliyor.</p></section>
<section className="adminDashboardCard"><form className="adminListingForm" action={createTradeInCost}><label className="adminField">Kalem adı<input name="label" required placeholder="Face ID arızası"/></label><label className="adminField">Tutar<input name="amount" inputMode="decimal" required placeholder="2500"/></label><label className="adminField">Kullanım alanı<select name="category" defaultValue="system"><option value="system">Otomatik sistem kesintisi</option><option value="repair">Onarım / değişen seçeneği</option><option value="accessory">Kutu / aksesuar seçeneği</option></select></label><label className="adminField">Kod (opsiyonel)<input name="code" placeholder="face_id"/></label><div className="adminFormActions"><button className="adminButton">Yeni Kalem Ekle</button></div></form></section>
<section className="adminDashboardCard"><h2 style={{marginTop:0}}>Toplu yüzdelik zam</h2><form className="adminListingForm" action={bulkIncreaseTradeInCosts}><label className="adminField">Kalem grubu<select name="scope" defaultValue="all"><option value="all">Tüm masraf referansları</option><option value="system">Otomatik sistem kesintileri</option><option value="repair">Onarım / değişen seçenekleri</option><option value="accessory">Kutu / aksesuar seçenekleri</option></select></label><label className="adminField">Zam oranı (%)<input name="percentage" inputMode="decimal" required placeholder="10"/></label><div className="adminFormActions"><button className="adminButton">Toplu Zammı Uygula</button></div></form></section>
<section className="listingSection"><div className="sectionHeading"><div><h2>Referans maliyetler</h2><p>{costs.length} kalem</p></div></div><div className="adminDraftList">{costs.map(cost=><article className="adminDraftItem" key={cost.code}><div><span className="productCode">{cost.category}{cost.selectable?" · form seçeneği":""}</span><h3>{cost.label}</h3><p>{Number(cost.amount).toLocaleString("tr-TR")} ₺ · {cost.is_active?"Aktif":"Gizli"}</p></div><div className="adminInlineActions"><form action={updateTradeInCost}><input type="hidden" name="code" value={cost.code}/><input name="label" defaultValue={cost.label}/><input name="amount" inputMode="decimal" defaultValue={String(cost.amount)}/><button className="adminButton adminButtonSecondary">Kaydet</button></form><form action={toggleTradeInCost}><input type="hidden" name="code" value={cost.code}/><input type="hidden" name="active" value={String(cost.is_active)}/><button className="adminButton adminButtonSecondary">{cost.is_active?"Gizle":"Göster"}</button></form><form action={deleteTradeInCost}><input type="hidden" name="code" value={cost.code}/><button className="adminButton adminDangerButton">Sil</button></form></div></article>)}</div></section></main>}
