"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server-client";
import { isAdminEmail } from "@/modules/auth/admin-access";

async function adminClient(){const supabase=await createSupabaseServerClient();const{data,error}=await supabase.auth.getUser();if(error||!data.user||!isAdminEmail(data.user.email))redirect("/admin/login");return supabase}
function text(form:FormData,key:string){return String(form.get(key)??"").trim()}
function number(form:FormData,key:string){const value=Number(text(form,key).replace(",","."));if(!Number.isFinite(value)||value<0)throw new Error("Geçerli fiyat gir.");return value}
function percentage(form:FormData){const value=Number(text(form,"percentage").replace(",","."));if(!Number.isFinite(value)||value<=0||value>500)throw new Error("Zam oranı 0 ile 500 arasında olmalı.");return value}
function codeFrom(label:string){return label.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function refresh(){revalidatePath("/kategori/teknik-servis");revalidatePath("/admin/technical-service/prices")}
export async function createServicePrice(form:FormData){const supabase=await adminClient();const min=number(form,"minPrice"),max=number(form,"maxPrice");if(max<min)throw new Error("Maksimum fiyat minimumdan küçük olamaz.");const label=text(form,"faultLabel");const code=text(form,"faultCode")||codeFrom(label);const{error}=await supabase.from("service_price_references").insert({device_type:text(form,"deviceType"),brand:text(form,"brand"),model:text(form,"model"),fault_code:code,fault_label:label,min_price:min,max_price:max,is_active:true});if(error)throw new Error(error.code==="23505"?"Bu cihaz/marka/model ve kalem zaten kayıtlı.":"Referans eklenemedi.");refresh()}
export async function updateServicePrice(form:FormData){const supabase=await adminClient();const min=number(form,"minPrice"),max=number(form,"maxPrice");if(max<min)throw new Error("Maksimum fiyat minimumdan küçük olamaz.");const{error}=await supabase.from("service_price_references").update({fault_label:text(form,"faultLabel"),brand:text(form,"brand"),model:text(form,"model"),min_price:min,max_price:max,updated_at:new Date().toISOString()}).eq("id",text(form,"id"));if(error)throw new Error("Fiyat güncellenemedi.");refresh()}
export async function toggleServicePrice(form:FormData){const supabase=await adminClient();const active=text(form,"active")==="true";const{error}=await supabase.from("service_price_references").update({is_active:!active,updated_at:new Date().toISOString()}).eq("id",text(form,"id"));if(error)throw new Error("Durum güncellenemedi.");refresh()}
export async function deleteServicePrice(form:FormData){const supabase=await adminClient();const{error}=await supabase.from("service_price_references").delete().eq("id",text(form,"id"));if(error)throw new Error("Referans silinemedi.");refresh()}
export async function bulkIncreaseServicePrices(form:FormData){const supabase=await adminClient();const pct=percentage(form);const deviceType=text(form,"deviceType");const brand=text(form,"brand");let query=supabase.from("service_price_references").select("id,min_price,max_price,device_type,brand");if(deviceType)query=query.eq("device_type",deviceType);if(brand)query=query.ilike("brand",brand);const{data,error}=await query;if(error)throw new Error("Servis fiyatları okunamadı.");const now=new Date().toISOString();const results=await Promise.all((data??[]).map(row=>supabase.from("service_price_references").update({min_price:Math.round(Number(row.min_price)*(1+pct/100)*100)/100,max_price:Math.round(Number(row.max_price)*(1+pct/100)*100)/100,updated_at:now}).eq("id",row.id)));if(results.some(result=>result.error))throw new Error("Toplu zam uygulanırken bazı servis fiyatları güncellenemedi.");refresh()}
