import { createSupabaseServerClient } from "@/lib/supabase/server-client";
import { createServicePrice, deleteServicePrice, toggleServicePrice, updateServicePrice } from "./actions";

export default async function ServicePricesPage(){
 const supabase=await createSupabaseServerClient();
 const {data}=await supabase.from("service_price_references").select("id,device_type,fault_code,fault_label,min_price,max_price,is_active").order("device_type").order("sort_order").order("fault_label");
 const rows=data??[];
 return <main className="adminShell adminShellWide"><header className="adminTopbar"><div><h1 className="adminPageTitle">Servis Fiyat Referansları</h1><p className="adminLead">Müşteriye gösterilecek tahmini servis fiyat aralıklarını yönet.</p></div></header>
 <section className="adminDashboardCard"><form className="adminListingForm" action={createServicePrice}><label className="adminField">Cihaz türü<select name="deviceType" required defaultValue="Telefon"><option>Telefon</option><option>Laptop</option><option>Tablet</option><option>Masaüstü Bilgisayar</option><option>Diğer</option></select></label><label className="adminField">Arıza / işlem<input name="faultLabel" required placeholder="Ekran değişimi"/></label><label className="adminField">Minimum fiyat<input name="minPrice" inputMode="decimal" required placeholder="2500"/></label><label className="adminField">Maksimum fiyat<input name="maxPrice" inputMode="decimal" required placeholder="5000"/></label><div className="adminFormActions"><button className="adminButton" type="submit">Referans Ekle</button></div></form></section>
 <section className="listingSection"><div className="sectionHeading"><div><h2>Fiyat listesi</h2><p>{rows.length} referans</p></div></div>{rows.length?<div className="adminDraftList">{rows.map(row=><article className="adminDraftItem" key={row.id}><div><span className="productCode">{row.device_type}</span><h3>{row.fault_label}</h3><p>{Number(row.min_price).toLocaleString("tr-TR")} ₺ – {Number(row.max_price).toLocaleString("tr-TR")} ₺ · {row.is_active?"Aktif":"Gizli"}</p></div><div className="adminInlineActions"><form action={updateServicePrice}><input type="hidden" name="id" value={row.id}/><input name="minPrice" defaultValue={String(row.min_price)} aria-label="Minimum fiyat"/><input name="maxPrice" defaultValue={String(row.max_price)} aria-label="Maksimum fiyat"/><button className="adminButton adminButtonSecondary" type="submit">Kaydet</button></form><form action={toggleServicePrice}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="active" value={String(row.is_active)}/><button className="adminButton adminButtonSecondary" type="submit">{row.is_active?"Gizle":"Göster"}</button></form><form action={deleteServicePrice}><input type="hidden" name="id" value={row.id}/><button className="adminButton adminDangerButton" type="submit">Sil</button></form></div></article>)}</div>:<p className="emptyState">Henüz servis fiyat referansı yok.</p>}</section></main>
}
