import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase/server-client";
import { applyBulkPriceUpdate } from "./actions";

type Props = { searchParams: Promise<{ base?: string; target?: string; rounding?: string; error?: string; updated?: string; rate?: string }> };
function parsePositive(value?: string) { if (!value) return null; const parsed = Number(value.replace(",", ".")); return Number.isFinite(parsed) && parsed > 0 ? parsed : null; }
function formatTry(value: number | null) { return value == null ? "Fiyat yok" : `${value.toLocaleString("tr-TR")} ₺`; }
function calculateIndexedPrice(usdBase: number, targetRate: number, roundingStep: number) { return Math.round((usdBase * targetRate) / roundingStep) * roundingStep; }
function usdBase(current: number, stored: unknown, baseRate: number) { return stored == null ? current / baseRate : Number(stored); }

export default async function AdminPricingPage({ searchParams }: Props) {
  const params = await searchParams; const supabase = await createSupabaseServerClient();
  const [{data:settings},{data:products},{data:tradeInDevices},{data:costReferences},{data:serviceReferences},{data:history}] = await Promise.all([
    supabase.from("site_settings").select("usd_try_rate,fx_rounding_step").eq("id",true).maybeSingle(),
    supabase.from("products").select("id,product_code,title,price,usd_base_price").eq("fx_index_enabled",true).not("price","is",null).order("created_at",{ascending:false}),
    supabase.from("trade_in_devices").select("id,brand,model,storage,market_price_tr,market_price_passport,market_price_international,usd_base_market_price_tr,usd_base_market_price_passport,usd_base_market_price_international").eq("fx_index_enabled",true).order("brand"),
    supabase.from("trade_in_cost_references").select("code,label,amount,usd_base_amount").eq("fx_index_enabled",true).order("sort_order"),
    supabase.from("service_price_references").select("id,device_type,brand,model,fault_label,min_price,max_price,usd_base_min_price,usd_base_max_price").eq("fx_index_enabled",true).order("device_type"),
    supabase.from("price_update_history").select("id,base_rate,target_rate,rounding_step,affected_count,product_count,trade_in_device_count,cost_reference_count,service_reference_count,created_at").order("created_at",{ascending:false}).limit(10),
  ]);
  const savedRate=settings?.usd_try_rate==null?null:Number(settings.usd_try_rate); const savedRounding=settings?.fx_rounding_step==null?100:Number(settings.fx_rounding_step); const baseRate=parsePositive(params.base)??savedRate; const targetRate=parsePositive(params.target); const requestedRounding=Number(params.rounding??savedRounding); const roundingStep=[1,10,50,100,500,1000].includes(requestedRounding)?requestedRounding:100; const canPreview=Boolean(targetRate&&baseRate);
  const productPreview=canPreview?(products??[]).map(item=>{const current=Number(item.price);const base=usdBase(current,item.usd_base_price,baseRate!);return{...item,current,base,next:calculateIndexedPrice(base,targetRate!,roundingStep)}}):[];
  const tradeInPreview=canPreview?(tradeInDevices??[]).map(item=>{const tr=Number(item.market_price_tr),passport=Number(item.market_price_passport),international=Number(item.market_price_international);return{...item,current:{tr,passport,international},next:{tr:calculateIndexedPrice(usdBase(tr,item.usd_base_market_price_tr,baseRate!),targetRate!,roundingStep),passport:calculateIndexedPrice(usdBase(passport,item.usd_base_market_price_passport,baseRate!),targetRate!,roundingStep),international:calculateIndexedPrice(usdBase(international,item.usd_base_market_price_international,baseRate!),targetRate!,roundingStep)}}}):[];
  const costPreview=canPreview?(costReferences??[]).map(item=>{const current=Number(item.amount);return{...item,current,next:calculateIndexedPrice(usdBase(current,item.usd_base_amount,baseRate!),targetRate!,roundingStep)}}):[];
  const servicePreview=canPreview?(serviceReferences??[]).map(item=>{const min=Number(item.min_price),max=Number(item.max_price);return{...item,current:{min,max},next:{min:calculateIndexedPrice(usdBase(min,item.usd_base_min_price,baseRate!),targetRate!,roundingStep),max:calculateIndexedPrice(usdBase(max,item.usd_base_max_price,baseRate!),targetRate!,roundingStep)}}}):[];
  const totalPreview=productPreview.length+tradeInPreview.length+costPreview.length+servicePreview.length;
  return <main className="adminShell adminShellWide">
    <header className="adminTopbar"><div><h1 className="adminPageTitle">Fiyat Yönetimi</h1><p className="adminLead">Tek kur değişikliğiyle tüm USD indeksli fiyat gruplarını önizle ve güncelle.</p></div><div className="adminTopbarActions"><Link className="adminButton adminButtonSecondary" href="/admin/trade-in">Takas</Link><Link className="adminButton adminButtonSecondary" href="/admin/technical-service/prices">Servis Fiyatları</Link></div></header>
    {params.updated?<p className="adminSuccess">{params.updated} kayıt güncellendi. Yeni kur: {params.rate}</p>:null}{params.error?<p className="adminError">{params.error}</p>:null}
    <section className="adminCompactPanel adminCompactPanelOpen"><div className="adminCompactPanelTitle"><div><strong>Kur değişikliği</strong><small>Mevcut baz kur: {savedRate?Number(savedRate).toLocaleString("tr-TR"):"Henüz tanımlı değil"}</small></div></div><form action="/admin/pricing" method="get" className="adminListingFilters adminCompactFilters"><label className="adminField">Baz USD/TRY<input name="base" inputMode="decimal" required defaultValue={baseRate??""}/></label><label className="adminField">Yeni USD/TRY<input name="target" inputMode="decimal" required defaultValue={targetRate??""}/></label><label className="adminField">Yuvarlama<select name="rounding" defaultValue={String(roundingStep)}><option value="1">1 TL</option><option value="10">10 TL</option><option value="50">50 TL</option><option value="100">100 TL</option><option value="500">500 TL</option><option value="1000">1.000 TL</option></select></label><button className="adminButton">Önizle</button></form></section>
    {canPreview?<><div className="adminOverviewGrid adminCompactOverview"><div><span>Toplam</span><strong>{totalPreview}</strong></div><div><span>Ürün</span><strong>{productPreview.length}</strong></div><div><span>Takas</span><strong>{tradeInPreview.length}</strong></div><div><span>Masraf</span><strong>{costPreview.length}</strong></div><div><span>Servis</span><strong>{servicePreview.length}</strong></div></div>
      <div className="adminToolRow">
        <details className="adminCompactPanel"><summary>Ürün fiyatları ({productPreview.length})</summary><div className="adminCompactList">{productPreview.map(item=><div className="adminCompactRow" key={item.id}><div><strong>{item.product_code} · {item.title}</strong><small>USD baz ${item.base.toFixed(2)}</small></div><span>{formatTry(item.current)} → <strong>{formatTry(item.next)}</strong></span></div>)}</div></details>
        <details className="adminCompactPanel"><summary>Takas cihazları ({tradeInPreview.length})</summary><div className="adminCompactList">{tradeInPreview.map(item=><div className="adminCompactRow" key={item.id}><div><strong>{item.brand} {item.model} {item.storage}</strong><small>TR {formatTry(item.current.tr)} → {formatTry(item.next.tr)}</small><small>YD kayıtlı {formatTry(item.current.passport)} → {formatTry(item.next.passport)}</small><small>YD kayıtsız {formatTry(item.current.international)} → {formatTry(item.next.international)}</small></div></div>)}</div></details>
        <details className="adminCompactPanel"><summary>Masraf referansları ({costPreview.length})</summary><div className="adminCompactList">{costPreview.map(item=><div className="adminCompactRow" key={item.code}><div><strong>{item.label}</strong><small>{item.code}</small></div><span>{formatTry(item.current)} → <strong>{formatTry(item.next)}</strong></span></div>)}</div></details>
        <details className="adminCompactPanel"><summary>Servis referansları ({servicePreview.length})</summary><div className="adminCompactList">{servicePreview.map(item=><div className="adminCompactRow" key={item.id}><div><strong>{item.device_type} · {item.fault_label}</strong><small>{[item.brand,item.model].filter(Boolean).join(" ")||"Genel"}</small></div><span>{formatTry(item.current.min)}–{formatTry(item.current.max)} → <strong>{formatTry(item.next.min)}–{formatTry(item.next.max)}</strong></span></div>)}</div></details>
      </div>
      <section className="adminCompactConfirm"><div><strong>{baseRate} → {targetRate} USD/TRY</strong><small>{roundingStep} TL yuvarlama · {totalPreview} kayıt</small></div><form action={applyBulkPriceUpdate}><input type="hidden" name="baseRate" value={baseRate??""}/><input type="hidden" name="targetRate" value={targetRate??""}/><input type="hidden" name="roundingStep" value={roundingStep}/><button className="adminButton">Tüm fiyatları güncelle</button></form></section>
    </>:null}
    <details className="adminCompactPanel adminHistoryPanel"><summary>Son fiyat güncellemeleri ({history?.length??0})</summary>{history?.length?<div className="adminCompactList">{history.map(item=><div className="adminCompactRow" key={item.id}><div><strong>{Number(item.base_rate).toLocaleString("tr-TR")} → {Number(item.target_rate).toLocaleString("tr-TR")}</strong><small>{new Date(item.created_at).toLocaleString("tr-TR")}</small></div><span>{item.affected_count} kayıt · {item.rounding_step} TL</span></div>)}</div>:<p className="emptyState">Henüz güncelleme yok.</p>}</details>
  </main>;
}
