"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { createTradeInDevicePrice, deleteTradeInDevicePrice, updateProductPrice, updateTradeInDevicePrice } from "./actions";
import styles from "./pricing-lists.module.css";

type ProductPrice = { id:string; product_code:string; title:string; price:number|string|null; publication_status:string; stock_status:string };
type TradePrice = { id:string; catalog_id:string|null; device_type:string; brand:string; model:string; storage:string|null; market_price_tr:number|string; market_price_passport:number|string; market_price_international:number|string; profit_margin_pct:number|string; is_active:boolean };
type CatalogItem = { id:string; category:string; sub_category:string; device_type:string; brand:string; model:string; storage_options:string[]|null; color_options:string[]|null; reference_price_tr:number|string|null; price_status:string; is_active:boolean };
function money(value:number|string|null|undefined){if(value==null||value==="")return "Fiyat yok";const parsed=Number(value);return Number.isFinite(parsed)?`${parsed.toLocaleString("tr-TR")} ₺`:"Fiyat yok"}
function normalize(value:unknown){return String(value??"").toLocaleLowerCase("tr-TR")}
export function ProductPriceList({products}:{products:ProductPrice[]}){const[query,setQuery]=useState("");const[filter,setFilter]=useState("all");const[editing,setEditing]=useState<string|null>(null);const filtered=useMemo(()=>{const needle=normalize(query.trim());return products.filter(product=>{const matchesQuery=!needle||normalize(`${product.product_code} ${product.title}`).includes(needle);const matchesFilter=filter==="all"||(filter==="in_stock"&&product.stock_status==="in_stock")||(filter==="sold"&&product.stock_status==="sold")||(filter==="published"&&product.publication_status==="published")||(filter==="draft"&&product.publication_status==="draft");return matchesQuery&&matchesFilter})},[products,query,filter]);return <section className={styles.panel}><div className={styles.headingRow}><div><h2>Ürün Fiyatları</h2></div><span className={styles.count}>{filtered.length} / {products.length}</span></div><div className={styles.toolbar}><input aria-label="Ürün ara" className={styles.search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Kod veya ürün ara..."/><select aria-label="Ürün filtresi" className={styles.select} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tüm ürünler</option><option value="in_stock">Stokta</option><option value="sold">Satıldı</option><option value="published">Yayında</option><option value="draft">Taslak</option></select></div><div className={styles.list}>{filtered.map(product=>{const isEditing=editing===product.id;return <div className={styles.row} key={product.id}><div className={styles.identity}><strong>{product.title}</strong><small>{product.product_code} · {product.stock_status==="sold"?"Satıldı":product.stock_status==="in_stock"?"Stokta":product.stock_status} · {product.publication_status==="published"?"Yayında":product.publication_status==="draft"?"Taslak":"Gizli"}</small></div>{!isEditing?<><strong className={styles.price}>{money(product.price)}</strong><div className={styles.actions}><button className="adminButton adminButtonSecondary" type="button" onClick={()=>setEditing(product.id)}>Düzenle</button><Link className={styles.openLink} href={`/admin/listings/${product.id}`}>Aç</Link></div></>:<form action={updateProductPrice} className={styles.inlineEditor}><input type="hidden" name="id" value={product.id}/><input className={styles.priceInput} autoFocus name="price" inputMode="decimal" defaultValue={product.price??""}/><button className="adminButton" type="submit">Kaydet</button><button className={styles.cancelButton} type="button" onClick={()=>setEditing(null)}>Vazgeç</button></form>}</div>})}{!filtered.length?<p className="emptyState">Aramaya uygun ürün bulunamadı.</p>:null}</div></section>}

export function TradePriceList({devices,catalog}:{devices:TradePrice[];catalog:CatalogItem[]}){
  const[query,setQuery]=useState("");
  const[category,setCategory]=useState("all");
  const[status,setStatus]=useState("all");
  const[editing,setEditing]=useState<string|null>(null);
  const deviceByCatalog=useMemo(()=>new Map(devices.filter(d=>d.catalog_id).map(d=>[d.catalog_id as string,d])),[devices]);
  const categories=useMemo(()=>Array.from(new Set(catalog.map(x=>x.category))).sort((a,b)=>a.localeCompare(b,"tr")),[catalog]);
  const filtered=useMemo(()=>{const needle=normalize(query.trim());return catalog.filter(item=>{const device=deviceByCatalog.get(item.id);const matchesQuery=!needle||normalize(`${item.category} ${item.sub_category} ${item.device_type} ${item.brand} ${item.model} ${(item.storage_options??[]).join(" ")} ${(item.color_options??[]).join(" ")}`).includes(needle);const matchesCategory=category==="all"||item.category===category;const matchesStatus=status==="all"||(status==="priced"&&Boolean(device))||(status==="unpriced"&&!device);return matchesQuery&&matchesCategory&&matchesStatus})},[catalog,deviceByCatalog,query,category,status]);
  const pricedCount=devices.filter(x=>x.is_active&&Number(x.market_price_tr)>0).length;
  return <section className={styles.panel}>
    <div className={styles.headingRow}><div><h2>Takas ve Teknik Servis Fiyatları</h2><p style={{margin:"6px 0 0",maxWidth:850,color:"#9aa6b6",lineHeight:1.55}}>Master katalogdaki tüm marka ve modeller burada görünür. Fiyatı olmayan kayıt müşteri Takas/Servis formuna açılmaz; TR referans fiyatı girildiğinde hesaplamaya aktif olur.</p></div><span className={styles.count}>{pricedCount} fiyatlı / {catalog.length} katalog</span></div>
    <div style={{margin:"0 0 16px",padding:"12px 14px",border:"1px solid #2a3241",borderRadius:14,background:"#0c1118",color:"#c5cfdd",fontSize:13,lineHeight:1.55}}><strong>Teknik Servis fiyat notu:</strong> Teknik Servis yalnızca pozitif <strong>TR referans fiyatı</strong> olan cihazları kullanır. YD kayıtlı ve YD kayıtsız değerler sadece takas hesabındadır. Katalogda fiyatı olmayan model kayıtlı kalır fakat hesaplamaya kapalıdır.</div>
    <div className={styles.toolbar}><input aria-label="Katalog ara" className={styles.search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Kategori, marka, model, renk veya depolama ara..."/><select aria-label="Kategori filtresi" className={styles.select} value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Tüm kategoriler</option>{categories.map(x=><option key={x} value={x}>{x}</option>)}</select><select aria-label="Fiyat durumu" className={styles.select} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tümü</option><option value="priced">Fiyatlandırılmış</option><option value="unpriced">Fiyat bekliyor</option></select><span className={styles.count}>{filtered.length} / {catalog.length}</span></div>
    <div className={styles.list}>{filtered.map(item=>{const device=deviceByCatalog.get(item.id);const isEditing=editing===item.id;const storages=(item.storage_options??[]).filter(Boolean);const colors=(item.color_options??[]).filter(Boolean);return <div className={`${styles.row} ${styles.tradeRow}`} key={item.id}>
      <div className={styles.identity}><strong>{item.brand} {item.model}</strong><small>{item.category}{item.sub_category?` · ${item.sub_category}`:""} · {device?"Fiyat aktif":"Fiyat bekliyor"}</small>{storages.length?<small>Depolama: {storages.join(" · ")}</small>:null}{colors.length?<small>Renk: {colors.join(" · ")}</small>:null}</div>
      {device&&!isEditing?<><div className={styles.tradePrices}><span><small>TR · Servis referansı</small><strong>{money(device.market_price_tr)}</strong></span><span><small>YD kayıtlı</small><strong>{money(device.market_price_passport)}</strong></span><span><small>YD kayıtsız</small><strong>{money(device.market_price_international)}</strong></span></div><div className={styles.actions}><button className="adminButton adminButtonSecondary" type="button" onClick={()=>setEditing(item.id)}>Düzenle</button><form action={deleteTradeInDevicePrice} onSubmit={event=>{if(!window.confirm(`${item.brand} ${item.model} fiyat kaydı kaldırılsın mı?`))event.preventDefault()}}><input type="hidden" name="id" value={device.id}/><button className="adminButton adminDangerButton" type="submit">Fiyatı kaldır</button></form></div></>:null}
      {device&&isEditing?<form action={updateTradeInDevicePrice} className={styles.tradeEditor}><input type="hidden" name="id" value={device.id}/><label>TR — servis referansı<input autoFocus name="marketPriceTr" inputMode="decimal" defaultValue={Number(device.market_price_tr)} required/></label><label>YD kayıtlı<input name="marketPricePassport" inputMode="decimal" defaultValue={Number(device.market_price_passport)} required/></label><label>YD kayıtsız<input name="marketPriceInternational" inputMode="decimal" defaultValue={Number(device.market_price_international)} required/></label><label>Kâr %<input name="profitMarginPct" inputMode="decimal" defaultValue={Number(device.profit_margin_pct)} required/></label><div className={styles.actions}><button className="adminButton">Kaydet</button><button className={styles.cancelButton} type="button" onClick={()=>setEditing(null)}>Vazgeç</button></div></form>:null}
      {!device&&!isEditing?<div className={styles.actions}><strong className={styles.price}>{item.reference_price_tr?money(item.reference_price_tr):"Fiyat girilmedi"}</strong><button className="adminButton adminButtonSecondary" type="button" onClick={()=>setEditing(item.id)}>Fiyatlandır</button></div>:null}
      {!device&&isEditing?<form action={createTradeInDevicePrice} className={styles.tradeEditor}><input type="hidden" name="catalogId" value={item.id}/><input type="hidden" name="deviceType" value={item.device_type}/><input type="hidden" name="brand" value={item.brand}/><input type="hidden" name="model" value={item.model}/><label>Varyant / depolama{storages.length?<select name="storage" defaultValue=""><option value="">Model geneli</option>{storages.map(x=><option key={x} value={x}>{x}</option>)}</select>:<input name="storage"/>}</label><label>TR — servis referansı<input autoFocus name="marketPriceTr" inputMode="decimal" defaultValue={item.reference_price_tr??""} required/></label><label>YD kayıtlı<input name="marketPricePassport" inputMode="decimal" defaultValue="0" required/></label><label>YD kayıtsız<input name="marketPriceInternational" inputMode="decimal" defaultValue="0" required/></label><label>Kâr %<input name="profitMarginPct" inputMode="decimal" defaultValue="15" required/></label><div className={styles.actions}><button className="adminButton">Fiyatı aktifleştir</button><button className={styles.cancelButton} type="button" onClick={()=>setEditing(null)}>Vazgeç</button></div></form>:null}
    </div>})}{!filtered.length?<p className="emptyState">Filtreye uygun katalog kaydı bulunamadı.</p>:null}</div>
  </section>
}
