"use client";

import Link from "next/link";
import { useState } from "react";
import { deleteTradeInDevicePrice, updateProductPrice, upsertVariantPrice } from "./actions";
import styles from "./pricing-lists.module.css";

type ProductPrice = { id:string; product_code:string; title:string; price:number|string|null; publication_status:string; stock_status:string };
type VariantRow = { variant_id:string; catalog_id:string; device_type:string; category:string; sub_category:string; brand:string; model:string; storage:string; color:string; trade_id:string|null; market_price_tr:number|string|null; market_price_passport:number|string|null; market_price_international:number|string|null; profit_margin_pct:number|string|null; total_count:number|string };
function money(value:number|string|null|undefined){if(value==null||value==="")return "Fiyat yok";const parsed=Number(value);return Number.isFinite(parsed)?`${parsed.toLocaleString("tr-TR")} ₺`:"Fiyat yok"}
function pageHref(page:number,query:string,deviceType:string,status:string){const p=new URLSearchParams({view:"trade",page:String(page)});if(query)p.set("q",query);if(deviceType)p.set("deviceType",deviceType);if(status&&status!=="all")p.set("status",status);return `/admin/pricing?${p.toString()}`}

export function ProductPriceList({products}:{products:ProductPrice[]}){
 const[query,setQuery]=useState("");const[filter,setFilter]=useState("all");const[editing,setEditing]=useState<string|null>(null);
 const filtered=products.filter(product=>{const needle=query.trim().toLocaleLowerCase("tr-TR");const matchesQuery=!needle||`${product.product_code} ${product.title}`.toLocaleLowerCase("tr-TR").includes(needle);const matchesFilter=filter==="all"||(filter==="in_stock"&&product.stock_status==="in_stock")||(filter==="sold"&&product.stock_status==="sold")||(filter==="published"&&product.publication_status==="published")||(filter==="draft"&&product.publication_status==="draft");return matchesQuery&&matchesFilter});
 return <section className={styles.panel}><div className={styles.headingRow}><div><h2>Ürün Fiyatları</h2></div><span className={styles.count}>{filtered.length} / {products.length}</span></div><div className={styles.toolbar}><input aria-label="Ürün ara" className={styles.search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Kod veya ürün ara..."/><select aria-label="Ürün filtresi" className={styles.select} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tüm ürünler</option><option value="in_stock">Stokta</option><option value="sold">Satıldı</option><option value="published">Yayında</option><option value="draft">Taslak</option></select></div><div className={styles.list}>{filtered.map(product=>{const isEditing=editing===product.id;return <div className={styles.row} key={product.id}><div className={styles.identity}><strong>{product.title}</strong><small>{product.product_code}</small></div>{!isEditing?<><strong className={styles.price}>{money(product.price)}</strong><div className={styles.actions}><button className="adminButton adminButtonSecondary" type="button" onClick={()=>setEditing(product.id)}>Düzenle</button><Link className={styles.openLink} href={`/admin/listings/${product.id}`}>Aç</Link></div></>:<form action={updateProductPrice} className={styles.inlineEditor}><input type="hidden" name="id" value={product.id}/><input className={styles.priceInput} autoFocus name="price" inputMode="decimal" defaultValue={product.price??""}/><button className="adminButton" type="submit">Kaydet</button><button className={styles.cancelButton} type="button" onClick={()=>setEditing(null)}>Vazgeç</button></form>}</div>})}</div></section>
}

export function TradePriceList({rows,query,deviceType,status,page}:{rows:VariantRow[];query:string;deviceType:string;status:string;page:number}){
 const[editing,setEditing]=useState<string|null>(null);
 const total=Number(rows[0]?.total_count??0);const pageSize=100;const totalPages=Math.max(1,Math.ceil(total/pageSize));
 const types=["Telefon","Tablet","Laptop / Bilgisayar","Akıllı Saat","Kulaklık","Aksesuar","Bilgisayar Bileşeni"];
 return <section className={styles.panel}>
  <div className={styles.headingRow}><div><h2>Takas ve Teknik Servis Fiyatları</h2><p style={{margin:"6px 0 0",maxWidth:900,color:"#9aa6b6",lineHeight:1.55}}>Her depolama ve renk artık ayrı fiyat satırıdır. Örneğin iPhone 15 128 GB Siyah ile 256 GB Siyah birbirinden bağımsız fiyatlandırılır.</p></div><span className={styles.count}>{total} varyant</span></div>
  <div style={{margin:"0 0 16px",padding:"12px 14px",border:"1px solid #2a3241",borderRadius:14,background:"#0c1118",color:"#c5cfdd",fontSize:13,lineHeight:1.55}}><strong>Fiyat kuralı:</strong> TR, YD kayıtlı ve YD kayıtsız değerleri bu satırdaki <strong>depolama + renk</strong> varyantına özeldir. Fiyat girilmeyen varyant müşteri Takas/Servis formunda görünmez.</div>
  <form method="get" className={styles.toolbar}><input type="hidden" name="view" value="trade"/><input aria-label="Varyant ara" className={styles.search} name="q" defaultValue={query} placeholder="Marka, model, depolama veya renk ara..."/><select aria-label="Cihaz türü" className={styles.select} name="deviceType" defaultValue={deviceType}><option value="">Tüm cihaz türleri</option>{types.map(x=><option key={x} value={x}>{x}</option>)}</select><select aria-label="Fiyat durumu" className={styles.select} name="status" defaultValue={status}><option value="all">Tümü</option><option value="priced">Fiyatlandırılmış</option><option value="unpriced">Fiyat bekliyor</option></select><button className="adminButton" type="submit">Filtrele</button></form>
  <div className={styles.list}>{rows.map(row=>{const isEditing=editing===row.variant_id;const priced=Boolean(row.trade_id)&&Number(row.market_price_tr)>0;return <div className={`${styles.row} ${styles.tradeRow}`} key={row.variant_id}>
   <div className={styles.identity}><strong>{row.brand} {row.model}</strong><small>{row.device_type} · {row.sub_category||row.category} · {priced?"Fiyat aktif":"Fiyat bekliyor"}</small><small><strong>Depolama:</strong> {row.storage||"Standart"} · <strong>Renk:</strong> {row.color||"Standart"}</small></div>
   {priced&&!isEditing?<><div className={styles.tradePrices}><span><small>TR · Servis referansı</small><strong>{money(row.market_price_tr)}</strong></span><span><small>YD kayıtlı</small><strong>{money(row.market_price_passport)}</strong></span><span><small>YD kayıtsız</small><strong>{money(row.market_price_international)}</strong></span></div><div className={styles.actions}><button className="adminButton adminButtonSecondary" type="button" onClick={()=>setEditing(row.variant_id)}>Düzenle</button><form action={deleteTradeInDevicePrice} onSubmit={e=>{if(!window.confirm(`${row.brand} ${row.model} · ${row.storage||"Standart"} · ${row.color||"Standart"} fiyatı kaldırılsın mı?`))e.preventDefault()}}><input type="hidden" name="id" value={row.trade_id??""}/><button className="adminButton adminDangerButton">Fiyatı kaldır</button></form></div></>:null}
   {!isEditing&&!priced?<div className={styles.actions}><strong className={styles.price}>Fiyat girilmedi</strong><button className="adminButton adminButtonSecondary" type="button" onClick={()=>setEditing(row.variant_id)}>Fiyatlandır</button></div>:null}
   {isEditing?<form action={upsertVariantPrice} className={styles.tradeEditor}><input type="hidden" name="variantId" value={row.variant_id}/><label>TR — servis referansı<input autoFocus name="marketPriceTr" inputMode="decimal" defaultValue={row.market_price_tr??""} required/></label><label>YD kayıtlı<input name="marketPricePassport" inputMode="decimal" defaultValue={row.market_price_passport??0} required/></label><label>YD kayıtsız<input name="marketPriceInternational" inputMode="decimal" defaultValue={row.market_price_international??0} required/></label><label>Kâr %<input name="profitMarginPct" inputMode="decimal" defaultValue={row.profit_margin_pct??15} required/></label><div className={styles.actions}><button className="adminButton">Kaydet</button><button className={styles.cancelButton} type="button" onClick={()=>setEditing(null)}>Vazgeç</button></div></form>:null}
  </div>})}{!rows.length?<p className="emptyState">Filtreye uygun varyant bulunamadı.</p>:null}</div>
  {totalPages>1?<div className={styles.toolbar} style={{justifyContent:"center",marginTop:18}}>{page>1?<Link className="adminButton adminButtonSecondary" href={pageHref(page-1,query,deviceType,status)}>← Önceki</Link>:null}<span className={styles.count}>Sayfa {page} / {totalPages}</span>{page<totalPages?<Link className="adminButton adminButtonSecondary" href={pageHref(page+1,query,deviceType,status)}>Sonraki →</Link>:null}</div>:null}
 </section>
}
