import Link from "next/link";
import "./guide.css";

const sections = [
  ["1. Genel Bakış", ["Genel Bakış günlük kontrol ekranıdır. Taslak ürünleri, stok durumlarını ve devam eden servis kayıtlarını kontrol et.", "Yeni ürün, barkod tarama ve servis kaydı gibi sık kullanılan işlemlere buradan geç."]],
  ["2. Yeni Ürün Ekleme", ["Ürün Yönetimi → Yeni ürün ekle ekranını aç.", "Sahibinden ilanı varsa Sahibinden'den getir; yoksa Manuel ilan oluştur seç.", "Görselleri yükle ve kapak olacak görseli ilk sıraya getir.", "Kategori seçildiğinde marka kataloğu ve kategoriye özel alanlar otomatik açılır.", "Telefon, laptop/bilgisayar, bilgisayar parçası, oyun konsolu ve giyilebilir teknoloji aynı form alanlarını kullanmaz; ekranda açılan alanları doldur.", "Teknik Servis ürün kategorisi değildir; servis cihazları Teknik Servis modülünden kaydedilir.", "Ürün oluşturulurken ilk satış fiyatını girebilirsin. Ürün oluşturulduktan sonra fiyat yalnızca Fiyat Yönetimi'nden değiştirilir.", "Taslak veya Yayınla seçeneğini belirle ve kaydet. Ürün kodu ile barkod sistem tarafından oluşturulur."]],
  ["3. Ürün Yönetimi", ["Ürünler ekranında ürün kodu veya ürün adıyla ara; stok ve yayın filtrelerini kullan.", "Ürün detayında ürün bilgilerini, görselleri, açıklamayı, stok durumunu, yayın durumunu ve öne çıkan durumunu yönet.", "Satılan cihazı Satıldı yap. Yeniden stoğa girerse Stokta durumuna getir.", "Ürün detayında fiyat değiştirilmez. Fiyat değişikliği için Fiyat Yönetimi → Ürün Fiyatları'nı aç."]],
  ["4. Fiyat Yönetimi — Temel Mantık", ["Fiyat Yönetimi ürün oluşturma dışındaki bütün fiyat değişikliklerinin merkezidir.", "Ürün Fiyatları mevcut mağaza ürünlerinin satış fiyatlarını yönetir.", "Takas Fiyatları ortak cihaz kataloğudur. Takas formundaki marka/model listeleri ve Teknik Servis formundaki cihaz listeleri bu katalogdan gelir.", "Takas Fiyatları içindeki TR değeri Teknik Servis fiyat motorunun ana cihaz referansıdır. Teknik Servis YD kayıtlı veya YD kayıtsız fiyatları kullanmaz.", "Fiyat Motoru servis ve takas hesaplamalarında kullanılan işlem yüzdelerini, cihaz segment çarpanlarını ve model istisnalarını yönetir.", "Toplu İşlemler & Geçmiş birden fazla fiyatı yüzdesel veya kur bazlı değiştirmek ve yapılan toplu işlemleri geri almak için kullanılır."]],
  ["5. Ürün Fiyatları", ["Fiyat Yönetimi → Ürün Fiyatları'nı aç.", "Ürün kodu veya adıyla ürünü bul. Gerekirse Stokta, Satıldı, Yayında veya Taslak filtresini kullan.", "Düzenle'ye bas, yeni satış fiyatını gir ve Kaydet.", "Aç bağlantısı ürün kaydını gösterir; ürün detayındaki fiyat salt okunur kalır.", "Tek ürün fiyat değişikliklerinde toplu işlem kullanmak yerine bu ekranı kullan."]],
  ["6. Takas Fiyatları — Ortak Cihaz Kataloğu", ["Fiyat Yönetimi → Takas Fiyatları'nı aç.", "Bu ekran yalnızca takas için değil, Teknik Servis cihaz seçimi için de ortak kaynaktır. Yeni marka/model eklediğinde iki müşteri formunda da kullanılabilir hale gelir.", "Marka/model/varyant ile cihazı bul veya Yeni cihaz ile yeni referans ekle. Aynı modelin farklı hafıza/varyantlarını ayrı kayıt olarak tut.", "TR alanına Türkiye cihaz piyasa değerini gir. Bu değer Takas hesaplamasında kullanılır ve aynı zamanda Teknik Servis fiyat motorunun temel cihaz referansıdır.", "YD kayıtlı alanı pasaport/kayıtlı yurt dışı cihaz takas referansıdır. YD kayıtsız alanı kayıtsız/yurt dışı cihaz takas referansıdır.", "Teknik Servis hesaplaması yalnızca TR değerini baz alır. TR değeri olmayan cihaz için otomatik servis fiyatı üretilmemelidir; cihaz fiziksel kontrol/fiyat teyidi akışına düşer.", "Kâr % alanı Trove'nin takas hesabındaki marjı etkiler; Teknik Servis servis bedelini doğrudan belirlemez.", "Bir cihazı silersen veya katalogdan çıkarırsan müşteri Takas ve Teknik Servis cihaz seçimlerini de etkileyebileceğini unutma."]],
  ["7. Teknik Servis Formu — Yeni Soru Yapısı", ["Teknik Servis müşteri formu cihaz türü, marka ve modeli Takas Fiyatları kataloğundan dinamik olarak alır.", "Müşteriye aynı arızayı farklı isimlerle tekrar seçtiren eski checkbox mantığı kullanılmaz. Her cihaz bölümü için tek bir durum sorusu sorulur.", "Telefon tarafında örnek kontrol başlıkları: cihaz açılıyor mu, ekran/dokunmatik, arka cam/gövde, batarya, şarj, kamera, biyometrik, ses, tuş/titreşim, bağlantı, sensörler, sıvı teması, sistem/anakart ve önceki onarım geçmişi.", "Sadece sorunlu cevaplar fiyat motoruna servis kodu olarak gönderilir. Sağlam/normal cevaplar fiyatı artırmaz.", "Aynı fiziksel sorunu temsil eden kodlar tekilleştirilir; ekran + dokunmatik gibi çakışan eski servis kalemlerinin iki kez fiyatlanmasına izin verilmez.", "Teknik Servis formunda görünen cihaz listesiyle Takas Fiyatları kataloğu arasında ayrı manuel liste tutulmaz."]],
  ["8. Fiyat Motoru — Teknik Servis Hesabı", ["Teknik Servis hesabı Takas Fiyatları → TR cihaz değerinden başlar.", "Formdaki sorunlu cevap her servis işlemi için tek bir canonical servis koduna dönüşür.", "Fiyat Motoru ilgili servis kodunun Servis % oranını, minimum/maksimum servis sınırlarını ve varsa segment/nesil katsayılarını uygular.", "Model istisnası varsa genel formül yerine eşleşen istisna kullanılabilir.", "Birden fazla bağımsız arıza varsa tekilleştirilmiş servis kalemleri birlikte hesaplanır. Aynı arızanın eski/yeni iki kodu aynı anda toplanmaz.", "TR referansı yoksa ilan satış fiyatı gibi başka bir kaynağa geri dönülmez; otomatik tahmin verilmemesi beklenir."]],
  ["9. Fiyat Motoru — Takas Hesabı", ["Takas da aynı ortak cihaz kataloğunu kullanır ancak Teknik Servis ile aynı sonucu üretmez.", "TR, YD kayıtlı veya YD kayıtsız cihaz referansı müşterinin seçtiği cihaz kayıt durumuna göre kullanılır.", "Takas % değerleri arıza ve durum nedeniyle cihaz değerinden yapılacak kesintiyi belirler.", "Kâr % takas teklifinde mağaza marjını etkiler. Teknik Servis tarafındaki Servis % ile karıştırma.", "Aşırı kesinti oluşan takaslarda sistem otomatik rakam göstermek yerine mağaza değerlendirmesine yönlendirebilir."]],
  ["10. Fiyat Motoru — Segmentler", ["Segment katsayıları cihaz sınıfına göre hesaplanan değeri çarpar.", "Compact, Standard, Plus, Pro, Pro Max ve benzeri segmentlerin çarpanlarını yalnızca fiyat yapısında genel bir düzeltme gerektiğinde değiştir.", "Bir tek model pahalı veya ucuz kalıyorsa segmenti değiştirme; Model İstisnası oluştur.", "Segment değişikliği aynı segmentteki birden fazla hesabı etkileyebileceği için kaydetmeden önce kapsamını kontrol et."]],
  ["11. Fiyat Motoru — Model İstisnaları", ["Standart formül belirli bir modelde doğru sonuç vermiyorsa Model istisnaları bölümünü kullan.", "Cihaz türü, marka ve modeli seç; servis için işlem kalemini ve min/max fiyatı veya takas için kesinti tutarını gir.", "İstisna yalnızca eşleşen model ve işlemde genel formülün yerine kullanılır.", "Toplu zamdan hariç tut seçeneği açık olan istisnalar toplu değişikliklerden korunur.", "İstisnayı artık kullanmayacaksan Sil ile kaldır; genel fiyat motoru tekrar devreye girer."]],
  ["12. Toplu Zam / İndirim", ["Fiyat Yönetimi → Toplu İşlemler & Geçmiş'i aç.", "Önce kapsamı seç: Tümü, Kategori, Marka, Model veya Seçili ürünler.", "Sonra etkilenecek alanı seç: ürün satış fiyatı, takas piyasa fiyatı veya izin verilen diğer fiyat motoru alanları.", "Takas TR fiyatına uygulanacak toplu değişikliğin Teknik Servis tahminlerini de değiştireceğini unutma.", "Oranı yüzde olarak gir. Pozitif değer zam, negatif değer indirimdir.", "Önizle'ye bas. Etkilenecek kayıt sayısını ve örnek eski → yeni fiyatları kontrol et.", "Sonuç doğruysa Değişikliği uygula. Önizleme yapmadan toplu değişiklik uygulama."]],
  ["13. Kur Bazlı Güncelleme", ["USD bazlı referanslar için Toplu İşlemler & Geçmiş → Kur bazlı güncelleme bölümünü kullan.", "Baz USD/TRY mevcut hesaplamanın kuru, Yeni USD/TRY uygulanacak yeni kuru gösterir.", "Yuvarlama adımını seç ve önce Kontrol et'e bas.", "Gösterilen baz → yeni kur doğruysa Güncellemeyi uygula.", "TR takas referansı kur güncellemesinden etkilenirse Teknik Servis otomatik tahminleri de yeni TR referansına göre değişir."]],
  ["14. Fiyat İşlem Geçmişi ve Geri Alma", ["Toplu zam/indirim işlemleri İşlem geçmişinde tutulur.", "Yanlış kapsam veya oran uygulandıysa ilgili işlemin Geri al düğmesini kullan.", "Geri alınmış işlem tekrar aktif işlem gibi değerlendirilmez ve geçmişte Geri alındı olarak görünür.", "Kur geçmişi yapılan kur değişikliklerini ve etkilenen kayıt sayılarını gösterir.", "Tek ürün üzerinde yapılan normal fiyat düzenlemesi ile toplu işlem geçmişini birbirine karıştırma."]],
  ["15. Barkod ve Etiket", ["Barkod Tara ekranında telefon/tablet/bilgisayar kamerasını veya fiziksel barkod okuyucuyu kullan.", "Barkod okutulduğunda ilgili ürün kaydı açılır.", "Buradan ürün bilgilerini ve stok durumunu yönetebilirsin; fiyat değişikliği gerekiyorsa Fiyat Yönetimi'ne geç.", "Etiketi ürün ekranından aç ve yazdır. Etiketteki barkod ile ürün kodunun doğru ürüne ait olduğunu kontrol et."]],
  ["16. Teknik Servis — Mağaza Operasyonu", ["Teknik Servis → Yeni servis kaydı ile müşteri ve cihaz kabulünü oluştur.", "Müşteri adı, telefon, cihaz bilgisi, şikayet, tespit edilen arıza ve durum alanlarını doldur.", "Servise özel barkodu cihazla eşleştir.", "Müşteri formundaki otomatik tahmin yalnızca ön tahmindir; mağazada fiziksel kontrolden sonra kesin servis bedeli netleştirilir.", "İşlem ilerledikçe durumunu güncelle. Tamamlanan kayıtları geçmiş için arşivle.", "Servis fiyat kuralları yalnızca Fiyat Yönetimi → Fiyat Motoru'ndan yönetilir; ayrı bir teknik servis fiyat düzenleme ekranı kullanılmaz."]],
  ["17. Kategori Yönetimi", ["Kategori Yönetimi ürün kategorilerini ve müşteri sitesindeki görünürlüğünü yönetir.", "Yeni ürün formu kategoriye göre dinamik alan açar; kategori seçimini doğru yap.", "Teknik Servis ürün kategorisi değildir ve yeni ürün seçiminde gösterilmez."]],
  ["18. Slider, İçerik ve Site Ayarları", ["Slider & içerik bölümünden ana sayfa kampanya ve sliderlarını yönet.", "Şirket & iletişim bölümünden telefon, WhatsApp, e-posta, Instagram, adres ve şirket bilgilerini güncelle.", "Logo & site kimliği bölümünden logo ve marka görünümünü yönet.", "Değişiklikten sonra müşteri sitesini mobil ve masaüstünde kontrol et."]],
  ["19. Önerilen Günlük Kullanım", ["Yeni ürün: görseller → kategori → ürün bilgileri → ilk fiyat → yayın → etiket.", "Ürün fiyatı değişti: Fiyat Yönetimi → Ürün Fiyatları → ürünü bul → düzenle.", "Yeni takas/servis cihazı eklenecek: Fiyat Yönetimi → Takas Fiyatları → cihazı ekle → TR/YD referanslarını gir.", "Teknik servis tahmini sapıyor: önce Takas Fiyatları → TR değerini kontrol et; sonra Fiyat Motoru → Servis % / segment / istisna kontrolü yap.", "Takas tahmini sapıyor: Takas Fiyatları → doğru TR/YD referansını ve Kâr % değerini kontrol et; sonra Takas % kesintilerini incele.", "Piyasa genel olarak değişti: Toplu İşlemler → kapsam → hedef → oran → önizleme → uygula.", "Servis cihazı geldi: Teknik Servis → yeni kayıt → barkod → durum takibi → arşiv.", "Mağazada ürün bulundu: barkodu tara → ürünü aç → stok/yayın işlemini yap."]],
] as const;

export default function AdminGuidePage() {
  return <main className="adminShell adminShellWide adminGuidePage">
    <header className="adminDashboardHeader"><div><span className="adminDashboardEyebrow">KULLANIM REHBERİ</span><h1>Trove Admin Kullanım Rehberi</h1></div><Link className="adminButton adminButtonSecondary" href="/admin">Genel Bakış</Link></header>
    <div className="adminGuideGrid">{sections.map(([title, items]) => <section className="adminGuideCard" key={title}><h2>{title}</h2><ol>{items.map(item => <li key={item}>{item}</li>)}</ol></section>)}</div>
  </main>;
}
