import Link from "next/link";
import "./guide.css";

const sections = [
  ["1. Genel Bakış", ["Genel Bakış günlük kontrol ekranıdır. Taslak ürünleri, stok durumlarını ve devam eden servis kayıtlarını kontrol et.", "Yeni ürün, barkod tarama ve servis kaydı gibi sık kullanılan işlemlere buradan geç."]],
  ["2. Yeni Ürün Ekleme", ["Ürün Yönetimi → Yeni ürün ekle ekranını aç.", "Sahibinden ilanı varsa Sahibinden'den getir; yoksa Manuel ilan oluştur seç.", "Görselleri yükle ve kapak olacak görseli ilk sıraya getir.", "Kategori seçildiğinde marka kataloğu ve kategoriye özel alanlar otomatik açılır.", "Telefon, laptop/bilgisayar, bilgisayar parçası, oyun konsolu ve giyilebilir teknoloji aynı form alanlarını kullanmaz; ekranda açılan alanları doldur.", "Teknik Servis ürün kategorisi değildir; servis cihazları Teknik Servis modülünden kaydedilir.", "Ürün oluşturulurken ilk satış fiyatını girebilirsin. Ürün oluşturulduktan sonra fiyat yalnızca Fiyat Yönetimi'nden değiştirilir.", "Taslak veya Yayınla seçeneğini belirle ve kaydet. Ürün kodu ile barkod sistem tarafından oluşturulur."]],
  ["3. Ürün Yönetimi", ["Ürünler ekranında ürün kodu veya ürün adıyla ara; stok ve yayın filtrelerini kullan.", "Ürün detayında ürün bilgilerini, görselleri, açıklamayı, stok durumunu, yayın durumunu ve öne çıkan durumunu yönet.", "Satılan cihazı Satıldı yap. Yeniden stoğa girerse Stokta durumuna getir.", "Ürün detayında fiyat değiştirilmez. Fiyat değişikliği için Fiyat Yönetimi → Ürün Fiyatları'nı aç."]],
  ["4. Fiyat Yönetimi — Temel Mantık", ["Fiyat Yönetimi ürün oluşturma dışındaki bütün fiyat değişikliklerinin merkezidir.", "Ürün Fiyatları mevcut mağaza ürünlerinin satış fiyatlarını yönetir.", "Takas Fiyatları müşteriden alınabilecek cihazların piyasa referanslarını ve kâr oranını yönetir.", "Fiyat Motoru servis ve takas hesaplamalarında kullanılan işlem yüzdelerini, cihaz segment çarpanlarını ve model istisnalarını yönetir.", "Toplu İşlemler & Geçmiş birden fazla fiyatı yüzdesel veya kur bazlı değiştirmek ve yapılan toplu işlemleri geri almak için kullanılır."]],
  ["5. Ürün Fiyatları", ["Fiyat Yönetimi → Ürün Fiyatları'nı aç.", "Ürün kodu veya adıyla ürünü bul. Gerekirse Stokta, Satıldı, Yayında veya Taslak filtresini kullan.", "Düzenle'ye bas, yeni satış fiyatını gir ve Kaydet.", "Aç bağlantısı ürün kaydını gösterir; ürün detayındaki fiyat salt okunur kalır.", "Tek ürün fiyat değişikliklerinde toplu işlem kullanmak yerine bu ekranı kullan."]],
  ["6. Takas Fiyatları", ["Fiyat Yönetimi → Takas Fiyatları'nı aç.", "Marka/model/varyant ile cihazı bul veya Yeni cihaz ile yeni takas referansı ekle.", "TR cihaz için TR, pasaport kayıtlı cihaz için YD kayıtlı, kayıtsız cihaz için YD kayıtsız piyasa değerini gir.", "Kâr % alanı Trove'nin takas hesaplamasında kullanılacak marjı belirler.", "Piyasa değiştiğinde ilgili cihazı Düzenle ile güncelle. Aynı cihazın farklı hafıza/varyantlarını ayrı referans olarak tut."]],
  ["7. Fiyat Motoru — İşlem Katsayıları", ["İşlem katsayıları servis fiyatı ve takas kesintisinin cihaz referans değerinden hangi yüzdeyle hesaplanacağını belirler.", "Örneğin ekran, pil, kamera veya şarj işleminin satırını açıp Servis % ve Takas % değerlerini değiştirebilirsin.", "Servis % müşteriye verilecek servis tahminini; Takas % arızalı cihazın takas değerinden yapılacak kesintiyi etkiler.", "Bu katsayılar globaldir. Kategori, marka veya model bazında farklı sonuç gerekiyorsa Model İstisnası kullan."]],
  ["8. Fiyat Motoru — Segmentler", ["Segment katsayıları cihaz sınıfına göre hesaplanan değeri çarpar.", "Compact, Standard, Plus, Pro, Pro Max ve benzeri segmentlerin çarpanlarını yalnızca fiyat yapısında genel bir düzeltme gerektiğinde değiştir.", "Bir tek model pahalı veya ucuz kalıyorsa segmenti değiştirme; Model İstisnası oluştur.", "Segment değişikliği aynı segmentteki birden fazla hesabı etkileyebileceği için kaydetmeden önce kapsamını kontrol et."]],
  ["9. Fiyat Motoru — Model İstisnaları", ["Standart formül belirli bir modelde doğru sonuç vermiyorsa Model istisnaları bölümünü kullan.", "Cihaz türü, marka ve modeli seç; servis için işlem kalemini ve min/max fiyatı veya takas için kesinti tutarını gir.", "İstisna yalnızca eşleşen model ve işlemde genel formülün yerine kullanılır.", "Toplu zamdan hariç tut seçeneği açık olan istisnalar toplu değişikliklerden korunur.", "İstisnayı artık kullanmayacaksan Sil ile kaldır; genel fiyat motoru tekrar devreye girer."]],
  ["10. Toplu Zam / İndirim", ["Fiyat Yönetimi → Toplu İşlemler & Geçmiş'i aç.", "Önce kapsamı seç: Tümü, Kategori, Marka, Model veya Seçili ürünler.", "Sonra etkilenecek alanı seç: ürün satış fiyatı, takas piyasa fiyatı veya izin verilen diğer fiyat motoru alanları.", "Oranı yüzde olarak gir. Pozitif değer zam, negatif değer indirimdir.", "Önizle'ye bas. Etkilenecek kayıt sayısını ve örnek eski → yeni fiyatları kontrol et.", "Sonuç doğruysa Değişikliği uygula. Önizleme yapmadan toplu değişiklik uygulama.", "Seçili ürünler kapsamı yalnızca seçtiğin ürünlerin satış fiyatlarını değiştirir."]],
  ["11. Kur Bazlı Güncelleme", ["USD bazlı referanslar için Toplu İşlemler & Geçmiş → Kur bazlı güncelleme bölümünü kullan.", "Baz USD/TRY mevcut hesaplamanın kuru, Yeni USD/TRY uygulanacak yeni kuru gösterir.", "Yuvarlama adımını seç ve önce Kontrol et'e bas.", "Gösterilen baz → yeni kur doğruysa Güncellemeyi uygula.", "Kur güncellemesi geçmişte ayrıca kaydedilir; kaç ürün, takas ve servis referansının etkilendiğini geçmişten görebilirsin."]],
  ["12. Fiyat İşlem Geçmişi ve Geri Alma", ["Toplu zam/indirim işlemleri İşlem geçmişinde tutulur.", "Yanlış kapsam veya oran uygulandıysa ilgili işlemin Geri al düğmesini kullan.", "Geri alınmış işlem tekrar aktif işlem gibi değerlendirilmez ve geçmişte Geri alındı olarak görünür.", "Kur geçmişi yapılan kur değişikliklerini ve etkilenen kayıt sayılarını gösterir.", "Tek ürün üzerinde yapılan normal fiyat düzenlemesi ile toplu işlem geçmişini birbirine karıştırma."]],
  ["13. Barkod ve Etiket", ["Barkod Tara ekranında telefon/tablet/bilgisayar kamerasını veya fiziksel barkod okuyucuyu kullan.", "Barkod okutulduğunda ilgili ürün kaydı açılır.", "Buradan ürün bilgilerini ve stok durumunu yönetebilirsin; fiyat değişikliği gerekiyorsa Fiyat Yönetimi'ne geç.", "Etiketi ürün ekranından aç ve yazdır. Etiketteki barkod ile ürün kodunun doğru ürüne ait olduğunu kontrol et."]],
  ["14. Teknik Servis", ["Teknik Servis → Yeni servis kaydı ile müşteri ve cihaz kabulünü oluştur.", "Müşteri adı, telefon, cihaz bilgisi, şikayet, tespit edilen arıza ve durum alanlarını doldur.", "Servise özel barkodu cihazla eşleştir.", "İşlem ilerledikçe durumunu güncelle. Tamamlanan kayıtları geçmiş için arşivle.", "Servis fiyat hesaplamasının genel kuralları Fiyat Yönetimi → Fiyat Motoru'ndan yönetilir."]],
  ["15. Kategori Yönetimi", ["Kategori Yönetimi ürün kategorilerini ve müşteri sitesindeki görünürlüğünü yönetir.", "Yeni ürün formu kategoriye göre dinamik alan açar; kategori seçimini doğru yap.", "Teknik Servis ürün kategorisi değildir ve yeni ürün seçiminde gösterilmez."]],
  ["16. Slider, İçerik ve Site Ayarları", ["Slider & içerik bölümünden ana sayfa kampanya ve sliderlarını yönet.", "Şirket & iletişim bölümünden telefon, WhatsApp, e-posta, Instagram, adres ve şirket bilgilerini güncelle.", "Logo & site kimliği bölümünden logo ve marka görünümünü yönet.", "Değişiklikten sonra müşteri sitesini mobil ve masaüstünde kontrol et."]],
  ["17. Önerilen Günlük Kullanım", ["Yeni ürün: görseller → kategori → ürün bilgileri → ilk fiyat → yayın → etiket.", "Ürün fiyatı değişti: Fiyat Yönetimi → Ürün Fiyatları → ürünü bul → düzenle.", "Piyasa genel olarak değişti: Toplu İşlemler → kapsam → hedef → oran → önizleme → uygula.", "Servis/takas hesapları sapıyor: Fiyat Motoru → işlem katsayısı/segment/istisna kontrolü.", "Servis cihazı geldi: Teknik Servis → yeni kayıt → barkod → durum takibi → arşiv.", "Mağazada ürün bulundu: barkodu tara → ürünü aç → stok/yayın işlemini yap."]],
] as const;

export default function AdminGuidePage() {
  return <main className="adminShell adminShellWide adminGuidePage">
    <header className="adminDashboardHeader"><div><span className="adminDashboardEyebrow">KULLANIM REHBERİ</span><h1>Trove Admin Kullanım Rehberi</h1></div><Link className="adminButton adminButtonSecondary" href="/admin">Genel Bakış</Link></header>
    <div className="adminGuideGrid">{sections.map(([title, items]) => <section className="adminGuideCard" key={title}><h2>{title}</h2><ol>{items.map(item => <li key={item}>{item}</li>)}</ol></section>)}</div>
  </main>;
}
