import Link from "next/link";
import "./guide.css";

const sections = [
  ["1. Genel Bakış", ["Genel Bakış günlük kontrol ekranıdır. Taslak ürünleri, stok durumlarını ve devam eden servis kayıtlarını kontrol et.", "Yeni ürün, barkod tarama ve servis kaydı gibi sık kullanılan işlemlere buradan geç."]],
  ["2. Yeni Ürün Ekleme", ["Ürün Yönetimi → Yeni ürün ekle ekranını aç.", "Sahibinden ilanı varsa Sahibinden'den getir; yoksa Manuel ilan oluştur seç.", "Görselleri yükle ve kapak olacak görseli ilk sıraya getir.", "Kategori seçildiğinde marka kataloğu ve kategoriye özel alanlar otomatik açılır.", "Telefon, laptop/bilgisayar, bilgisayar parçası, oyun konsolu ve giyilebilir teknoloji aynı form alanlarını kullanmaz; ekranda açılan alanları doldur.", "Teknik Servis ürün kategorisi değildir; servis cihazları Teknik Servis modülünden kaydedilir.", "Ürün oluşturulurken ilk satış fiyatını girebilirsin. Ürün oluşturulduktan sonra fiyat yalnızca Fiyat Yönetimi'nden değiştirilir.", "Taslak veya Yayınla seçeneğini belirle ve kaydet. Ürün kodu ile barkod sistem tarafından oluşturulur."]],
  ["3. Ürün Yönetimi", ["Ürünler ekranında ürün kodu veya ürün adıyla ara; stok ve yayın filtrelerini kullan.", "Ürün detayında ürün bilgilerini, görselleri, açıklamayı, stok durumunu, yayın durumunu ve öne çıkan durumunu yönet.", "Satılan cihazı Satıldı yap. Yeniden stoğa girerse Stokta durumuna getir.", "Ürün detayında fiyat değiştirilmez. Fiyat değişikliği için Fiyat Yönetimi → Ürün Fiyatları'nı aç."]],
  ["4. Fiyat Yönetimi — Temel Mantık", ["Fiyat Yönetimi ürün oluşturma dışındaki bütün fiyat değişikliklerinin merkezidir.", "Ürün Fiyatları mevcut mağaza ürünlerinin satış fiyatlarını yönetir.", "Takas Fiyatları ortak cihaz kataloğudur. Takas formundaki marka/model listeleri ve Teknik Servis formundaki cihaz listeleri bu katalogdan gelir.", "Takas Fiyatları içindeki TR değeri Teknik Servis fiyat motorunun ana cihaz referansıdır. Teknik Servis YD kayıtlı veya YD kayıtsız fiyatları kullanmaz.", "Fiyat Motoru servis ve takas hesaplamalarında kullanılan işlem yüzdelerini, cihaz segment çarpanlarını ve model istisnalarını yönetir.", "Toplu İşlemler & Geçmiş birden fazla fiyatı yüzdesel veya kur bazlı değiştirmek ve yapılan toplu işlemleri geri almak için kullanılır."]],
  ["5. Ürün Fiyatları", ["Fiyat Yönetimi → Ürün Fiyatları'nı aç.", "Ürün kodu veya adıyla ürünü bul. Gerekirse Stokta, Satıldı, Yayında veya Taslak filtresini kullan.", "Düzenle'ye bas, yeni satış fiyatını gir ve Kaydet.", "Aç bağlantısı ürün kaydını gösterir; ürün detayındaki fiyat salt okunur kalır.", "Tek ürün fiyat değişikliklerinde toplu işlem kullanmak yerine bu ekranı kullan."]],
  ["6. Takas Fiyatları — Ortak Cihaz Kataloğu", ["Fiyat Yönetimi → Takas Fiyatları'nı aç.", "Bu ekran yalnızca takas için değil, Teknik Servis cihaz seçimi için de ortak kaynaktır. Yeni marka/model eklediğinde iki müşteri formunda da kullanılabilir hale gelir.", "Marka/model/varyant ile cihazı bul veya Yeni cihaz ile yeni referans ekle. Aynı modelin farklı hafıza ve renk varyantlarını ayrı fiyatlandır.", "TR alanına Türkiye cihaz piyasa değerini gir. Bu değer Takas hesaplamasında kullanılır ve aynı zamanda Teknik Servis fiyat motorunun temel cihaz referansıdır.", "YD kayıtlı alanı pasaport/kayıtlı yurt dışı cihaz takas referansıdır. YD kayıtsız alanı kayıtsız/yurt dışı cihaz takas referansıdır.", "Teknik Servis hesaplaması yalnızca TR değerini baz alır. TR değeri olmayan cihaz için otomatik servis fiyatı üretilmemelidir; cihaz fiziksel kontrol/fiyat teyidi akışına düşer.", "Kâr % alanı Trove'nin takas hesabındaki marjı etkiler; Teknik Servis servis bedelini doğrudan belirlemez."]],
  ["7. Teknik Servis Formu", ["Müşteri önce cihaz türünü, marka/modeli, hafızayı ve rengi seçer.", "Ardından yalnızca ihtiyaç duyduğu servis işlemlerini isteğe bağlı listeden işaretler; her alt sistem için zorunlu evet/hayır sorusu yoktur.", "Birden fazla servis ihtiyacı aynı anda seçilebilir.", "Açıklama / not alanı isteğe bağlıdır; müşteri şikayetini veya önceki onarım bilgisini tek alanda yazabilir.", "Teknik Servis formunda görünen fiyatlandırılmış cihazlar merkezi cihaz/varyant kataloğundan gelir."]],
  ["8. Fiyat Motoru — Teknik Servis Hesabı", ["Teknik Servis hesabı cihazın tam TR varyant değerinden başlar: marka → model → hafıza → renk.", "Seçilen servis işlemleri fiyat motorundaki Servis % oranlarını ve varsa minimum/maksimum sınırları kullanır.", "Model istisnası varsa eşleşen işlemde genel formül yerine istisna kullanılabilir.", "Birden fazla bağımsız arıza birlikte hesaplanabilir.", "Tam varyantın TR referansı yoksa başka bir satış fiyatına geri dönülmez; otomatik tahmin verilmez."]],
  ["9. Fiyat Motoru — Takas Hesabı", ["Takas aynı ortak cihaz kataloğunu kullanır ancak Teknik Servis ile aynı sonucu üretmez.", "TR, YD kayıtlı veya YD kayıtsız referans müşterinin seçtiği kayıt durumuna göre kullanılır.", "Takas % değerleri arıza ve durum nedeniyle cihaz değerinden yapılacak kesintiyi belirler.", "Kâr % takas teklifinde mağaza marjını etkiler. Teknik Servis tarafındaki Servis % ile karıştırma.", "Aşırı kesinti oluşan takaslarda sistem otomatik rakam göstermek yerine mağaza değerlendirmesine yönlendirebilir."]],
  ["10. Fiyat Motoru — Segmentler", ["Segment katsayıları cihaz sınıfına göre hesaplanan değeri çarpar.", "Compact, Standard, Plus, Pro, Pro Max ve benzeri segmentlerin çarpanlarını yalnızca genel bir düzeltme gerektiğinde değiştir.", "Bir tek model pahalı veya ucuz kalıyorsa segmenti değiştirme; Model İstisnası oluştur.", "Segment değişikliği aynı segmentteki birden fazla hesabı etkileyebileceği için kaydetmeden önce kapsamını kontrol et."]],
  ["11. Fiyat Motoru — Model İstisnaları", ["Standart formül belirli bir modelde doğru sonuç vermiyorsa Model istisnaları bölümünü kullan.", "Cihaz türü, marka ve modeli seç; servis için işlem kalemini ve min/max fiyatı veya takas için kesinti tutarını gir.", "İstisna yalnızca eşleşen model ve işlemde genel formülün yerine kullanılır.", "Toplu zamdan hariç tut seçeneği açık olan istisnalar toplu değişikliklerden korunur."]],
  ["12. Toplu Zam / İndirim", ["Fiyat Yönetimi → Toplu İşlemler & Geçmiş'i aç.", "Önce kapsamı seç: Tümü, Kategori, Marka, Model veya Seçili ürünler.", "Sonra etkilenecek alanı seç.", "Oranı yüzde olarak gir. Pozitif değer zam, negatif değer indirimdir.", "Önizle'ye bas ve etkilenecek kayıtları kontrol et.", "Sonuç doğruysa Değişikliği uygula. Önizleme yapmadan toplu değişiklik uygulama."]],
  ["13. Kur Bazlı Güncelleme", ["USD bazlı referanslar için Toplu İşlemler & Geçmiş → Kur bazlı güncelleme bölümünü kullan.", "Baz USD/TRY mevcut hesaplamanın kuru, Yeni USD/TRY uygulanacak yeni kuru gösterir.", "Yuvarlama adımını seç ve önce Kontrol et'e bas.", "Gösterilen baz → yeni kur doğruysa Güncellemeyi uygula."]],
  ["14. Fiyat İşlem Geçmişi ve Geri Alma", ["Toplu zam/indirim işlemleri İşlem geçmişinde tutulur.", "Yanlış kapsam veya oran uygulandıysa ilgili işlemin Geri al düğmesini kullan.", "Bir toplu işlemden sonra aynı fiyat elle değiştirildiyse sistem geri alma sırasında çakışmayı bildirir; sonradan yapılan değişikliği sessizce ezmez.", "Kur geçmişi yapılan kur değişikliklerini ve etkilenen kayıt sayılarını gösterir."]],
  ["15. Barkod ve Etiket", ["Barkod Tara ekranında telefon/tablet/bilgisayar kamerasını veya fiziksel barkod okuyucuyu kullan.", "Barkod okutulduğunda ilgili ürün kaydı açılır.", "Buradan ürün bilgilerini ve stok durumunu yönetebilirsin; fiyat değişikliği gerekiyorsa Fiyat Yönetimi'ne geç.", "Etiketi ürün ekranından aç ve yazdır. Etiketteki barkod ile ürün kodunun doğru ürüne ait olduğunu kontrol et."]],
  ["16. Teknik Servis — Mağaza Operasyonu", ["Teknik Servis → Yeni servis kaydı ile müşteri ve cihaz kabulünü oluştur.", "Müşteri adı, telefon, cihaz bilgisi, şikayet, tespit edilen arıza ve durum alanlarını doldur.", "Servise özel barkodu cihazla eşleştir.", "Müşteri formundaki otomatik tahmin yalnızca ön tahmindir; mağazada fiziksel kontrolden sonra kesin servis bedeli netleştirilir.", "İşlem ilerledikçe durumunu güncelle. Tamamlanan kayıtları geçmiş için arşivle."]],
  ["17. Kategori Yönetimi", ["Kategori Yönetimi ürün kategorilerini ve müşteri sitesindeki görünürlüğünü yönetir.", "Yeni ürün formu kategoriye göre dinamik alan açar; kategori seçimini doğru yap.", "Teknik Servis ürün kategorisi değildir ve yeni ürün seçiminde gösterilmez."]],
  ["18. Slider, İçerik ve Site Ayarları", ["Slider & içerik bölümünden ana sayfa kampanya ve sliderlarını yönet.", "Şirket & iletişim bölümünden telefon, WhatsApp, e-posta, Instagram, adres ve şirket bilgilerini güncelle.", "Logo & site kimliği bölümünden logo ve marka görünümünü yönet.", "Değişiklikten sonra müşteri sitesini mobil ve masaüstünde kontrol et."]],
  ["19. PayTR — İlk Kurulum İçin Gerekenler", ["Bu bölüm PayTR hesabı açıldıktan sonra kullanılmalıdır. İnternetten bulunan örnek Merchant ID, Key veya Salt değerleriyle gerçek PayTR testi yapılamaz.", "Önce PayTR üye işyeri başvurusu tamamlanmalı ve PayTR Mağaza Paneli açılmalıdır.", "PayTR Mağaza Paneli → Destek & Kurulum → Entegrasyon Bilgileri ekranını aç. Burada Mağaza No (merchant_id), Mağaza Parolası (merchant_key) ve Mağaza Gizli Anahtarı (merchant_salt) bulunur. Bu bilgileri yalnızca yetkili PayTR kullanıcıları görebilir.", "Merchant Key ve Merchant Salt birer şifredir. WhatsApp'tan, e-postadan veya açık bir metin dosyasından paylaşma; GitHub'a kesinlikle yazma.", "Trove tarafında ayrıca SUPABASE_SERVICE_ROLE_KEY sunucu gizlisi gerekir. Bu anahtar da hiçbir zaman tarayıcıya, müşteri sayfasına veya GitHub'a konulmamalıdır."]],
  ["20. PayTR — Cloudflare Gizli Bilgilerini Ekleme", ["Trove canlı sitesi Cloudflare Worker üzerinde çalışır. PayTR şifrelerini normal site ayarı olarak değil, Cloudflare Secret olarak kaydet.", "Teknik işlem yapacak kişi proje klasöründe terminal açar ve sırasıyla şu secret adlarını tanımlar: PAYTR_MERCHANT_ID, PAYTR_MERCHANT_KEY, PAYTR_MERCHANT_SALT ve SUPABASE_SERVICE_ROLE_KEY.", "Wrangler ile işlem yapılacaksa her secret için `npx wrangler secret put SECRET_ADI` komutu çalıştırılır. Komut değeri istediğinde PayTR panelindeki karşılığı yapıştırılır. Örnek: `npx wrangler secret put PAYTR_MERCHANT_ID`.", "Aynı işlemi PAYTR_MERCHANT_KEY ve PAYTR_MERCHANT_SALT için tekrarla. Değerleri komutun yanına açık şekilde yazma; komut değer istediğinde yapıştır.", "SUPABASE_SERVICE_ROLE_KEY zaten canlı Worker'da tanımlıysa tekrar değiştirme. Emin değilsen önce teknik sorumluya kontrol ettir.", "Secret eklemek mevcut kod dosyalarına şifre yazmak değildir. Cloudflare bu değerleri gizli olarak saklar; hassas değerleri wrangler yapılandırmasındaki normal `vars` alanına koyma."]],
  ["21. PayTR — Bildirim URL ve Ödeme Sonucunun Mantığı", ["PayTR ödeme sonucunu müşterinin gördüğü başarılı/başarısız sayfasından değil, sunucumuza yaptığı Bildirim URL çağrısından doğrular.", "Trove için bildirim yolu `/api/payments/paytr/callback` olarak hazırlanmıştır. PayTR mağaza ayarında istenen Bildirim URL, canlı alan adının sonuna bu yol eklenerek girilmelidir. Örnek mantık: `https://SITENIZIN-ALAN-ADI/api/payments/paytr/callback`.", "Başarılı yönlendirme sayfası `/odeme/basarili`, başarısız yönlendirme sayfası `/odeme/basarisiz` yoludur. Bunlar müşteriye bilgi verir; siparişi kendi başına Ödendi yapmaz.", "Ödeme gerçekten başarılı kabul edilmeden önce PayTR callback imzası doğrulanır. Bu nedenle Bildirim URL'nin internete açık HTTPS adresi olması gerekir.", "PayTR aynı bildirimi tekrar gönderebilir. Trove ödeme altyapısı aynı başarılı ödemeyi ikinci kez siparişe uygulamayacak şekilde hazırlanmıştır."]],
  ["22. PayTR — Admin Panelinden Test Modunu Açma", ["Secret'lar canlı sunucuya eklendikten sonra Trove Admin'e giriş yap.", "Şirket & İletişim & Yasal → Satın Alma & Ödeme bölümünü aç.", "PayTR sunucu anahtarları durumunda Hazır benzeri olumlu durum görmeden PayTR'yi açmaya çalışma. Eksik görünüyorsa Cloudflare secret'larından biri eksiktir.", "İlk kurulumda mutlaka PayTR Test Modu açık kalsın. Doğrudan canlı ödeme ile başlama.", "Taksit istemiyorsan Tek çekim seçeneğini kullan. Taksit kullanılacaksa izin verilen maksimum taksit sayısını belirle; `0` PayTR'nin yürürlükte izin verdiği üst sınırı kullanması anlamına gelir.", "Ayarları kaydet. PayTR etkinleştirme anahtarını yalnızca secret'lar hazır, callback adresi doğru ve müşteri ödeme ekranı PayTR iframe'e bağlanmışsa aç."]],
  ["23. PayTR — İlk Gerçek Test", ["Önce düşük fiyatlı bir test ürünü oluştur veya uygun bir stok ürününü kullan. Ürün Yayında ve Stokta olmalı, satış fiyatı sıfırdan büyük olmalıdır.", "Müşteri tarafında ürünü aç, Satın Al akışını başlat ve gerçekçi ad, telefon, e-posta ve adres bilgileriyle sipariş oluştur.", "Kart ödeme ekranında PayTR iframe görünmelidir. Kart bilgileri Trove tarafından alınmamalı veya kaydedilmemelidir; kart formu PayTR tarafında çalışır.", "PayTR'nin test işlemi için sağladığı yöntem/kart bilgilerini kullan. Rastgele gerçek kartla deneme yapma.", "Ödeme sonrası yalnızca 'Başarılı' sayfasını görmek yeterli değildir. Admin → Siparişler → ilgili siparişi aç ve Ödeme durumu = Ödendi olduğunu, PayTR Merchant OID oluştuğunu ve ödeme olayının kaydedildiğini kontrol et.", "Başarısız ödeme testi de yap. Başarısız callback sonrasında sipariş Ödendi olmamalı ve ürünün gereksiz yere sonsuza kadar rezerve kalmadığı kontrol edilmelidir.", "Test tamamlanmadan PayTR Test Modu kapatılmamalıdır."]],
  ["24. PayTR — Canlıya Alma Kontrol Listesi", ["PayTR hesabının canlı ödeme almaya yetkili olduğundan emin ol.", "PAYTR_MERCHANT_ID, PAYTR_MERCHANT_KEY ve PAYTR_MERCHANT_SALT Cloudflare Secret olarak tanımlı olmalı; kaynak kodda bulunmamalı.", "Bildirim URL canlı HTTPS alan adını ve `/api/payments/paytr/callback` yolunu kullanmalı.", "Başarılı test ödemesinde callback gelmiş ve admin siparişinde ödeme gerçekten Ödendi görünmüş olmalı.", "Başarısız ödeme senaryosu denenmiş olmalı.", "Her şey doğrulandıktan sonra Admin → Satın Alma & Ödeme bölümünde Test Modu kapatılır ve PayTR etkin bırakılır.", "Canlıya geçtikten sonra ilk gerçek siparişi yakından takip et. PayTR panelindeki işlem ile Trove Admin'deki sipariş tutarı ve ödeme durumu aynı olmalıdır."]],
  ["25. PayTR — Sorun Çıkarsa Ne Kontrol Edilir?", ["PayTR anahtarları eksik diyorsa önce Cloudflare'da üç PAYTR secret'ının ve SUPABASE_SERVICE_ROLE_KEY'in tanımlı olduğunu kontrol et.", "Ödeme formu açılmıyorsa PayTR Test Modu, Merchant bilgileri, ürün fiyatı ve müşterinin zorunlu iletişim/adres alanlarını kontrol et.", "Müşteri ödeme yaptı ama sipariş Ödendi olmadıysa ilk kontrol edilecek yer Bildirim URL'dir. Başarılı yönlendirme ekranını ödeme kanıtı kabul etme.", "Tutar uyuşmazlığı varsa siparişi elle Ödendi yapmadan önce PayTR panelindeki tahsilat tutarıyla Trove sipariş tutarını karşılaştır.", "Merchant Key veya Salt'ın yanlış kişiye gönderildiğinden şüpheleniyorsan PayTR üzerinden anahtar yenileme sürecini başlat ve Cloudflare secret'larını yeni değerlerle güncelle.", "Sorun çözülene kadar PayTR'yi kapatıp mevcut güvenli ödeme yöntemini kullanmak, doğrulanmamış kart ödemesini açık bırakmaktan daha güvenlidir."]],
  ["26. Önerilen Günlük Kullanım", ["Yeni ürün: görseller → kategori → ürün bilgileri → ilk fiyat → yayın → etiket.", "Ürün fiyatı değişti: Fiyat Yönetimi → Ürün Fiyatları → ürünü bul → düzenle.", "Yeni takas/servis cihazı: Fiyat Yönetimi → Takas ve Teknik Servis Fiyatları → tam varyantı bul → fiyatlandır.", "Teknik servis tahmini sapıyor: önce tam varyantın TR değerini, sonra Fiyat Motoru servis kuralını kontrol et.", "Piyasa genel olarak değişti: Toplu İşlemler → kapsam → hedef → oran → önizleme → uygula.", "Servis cihazı geldi: Teknik Servis → yeni kayıt → barkod → durum takibi → arşiv.", "Mağazada ürün bulundu: barkodu tara → ürünü aç → stok/yayın işlemini yap."]],
] as const;

export default function AdminGuidePage() {
  return <main className="adminShell adminShellWide adminGuidePage">
    <header className="adminDashboardHeader"><div><span className="adminDashboardEyebrow">KULLANIM REHBERİ</span><h1>Trove Admin Kullanım Rehberi</h1></div><Link className="adminButton adminButtonSecondary" href="/admin">Genel Bakış</Link></header>
    <div className="adminGuideGrid">{sections.map(([title, items]) => <section className="adminGuideCard" key={title}><h2>{title}</h2><ol>{items.map(item => <li key={item}>{item}</li>)}</ol></section>)}</div>
  </main>;
}
