"use client";

import { createBrowserClient } from "@supabase/ssr";
import { FormEvent, useState } from "react";
import { saveSiteSettings } from "./actions";

type SettingsFormProps = {
  supabaseUrl: string;
  supabasePublishableKey: string;
  initial: {
    siteName: string; siteTagline: string; whatsappNumber: string; whatsappDefaultMessage: string;
    contactEmail: string; contactPhone: string; instagramUrl: string; companyAddress: string; aboutText: string;
    logoUrl: string | null; brandWordmarkUrl: string | null; appIconUrl: string | null;
  };
};

const MAX_BRAND_ASSET_BYTES = 1024 * 1024;
function validateSvg(file: File, label: string) { if (file.type !== "image/svg+xml" && !file.name.toLowerCase().endsWith(".svg")) throw new Error(`${label} yalnızca SVG formatında olmalıdır.`); if (file.size > MAX_BRAND_ASSET_BYTES) throw new Error(`${label} en fazla 1 MB olabilir.`); }
function sanitizeSvgElement(svg: SVGSVGElement, removeImages = false) { svg.querySelectorAll("script,foreignObject,iframe,object,embed").forEach((node) => node.remove()); if (removeImages) svg.querySelectorAll("image").forEach((node) => node.remove()); svg.querySelectorAll("*").forEach((node) => { for (const attribute of Array.from(node.attributes)) { const name = attribute.name.toLowerCase(); const value = attribute.value.trim().toLowerCase(); if (name.startsWith("on")) node.removeAttribute(attribute.name); if ((name === "href" || name === "xlink:href") && /^(https?:|javascript:|data:text\/html)/.test(value)) node.removeAttribute(attribute.name); } }); svg.querySelectorAll("metadata").forEach((node) => node.remove()); }
async function normalizeWordmarkSvg(file: File): Promise<File> { const documentSvg = new DOMParser().parseFromString(await file.text(), "image/svg+xml"); const svg = documentSvg.documentElement as unknown as SVGSVGElement; if (documentSvg.querySelector("parsererror") || svg.tagName.toLowerCase() !== "svg") throw new Error("Marka yazısı SVG dosyası okunamadı."); sanitizeSvgElement(svg, true); svg.removeAttribute("width"); svg.removeAttribute("height"); svg.removeAttribute("style"); svg.setAttribute("preserveAspectRatio", "xMidYMid meet"); const mount = document.createElement("div"); mount.style.cssText = "position:fixed;left:-100000px;top:-100000px;width:2000px;height:2000px;visibility:hidden;pointer-events:none"; mount.innerHTML = new XMLSerializer().serializeToString(svg); document.body.appendChild(mount); try { const liveSvg = mount.querySelector("svg") as SVGSVGElement | null; if (!liveSvg) throw new Error("Marka yazısı SVG sınırları hesaplanamadı."); const box = liveSvg.getBBox(); if (box.width <= 0 || box.height <= 0) throw new Error("Marka yazısı SVG içinde görünür içerik bulunamadı."); const padding = Math.max(box.width, box.height) * .04; svg.setAttribute("viewBox", `${box.x-padding} ${box.y-padding} ${box.width+padding*2} ${box.height+padding*2}`); } finally { mount.remove(); } const normalized = new File([new XMLSerializer().serializeToString(svg)], file.name, { type: "image/svg+xml" }); if (normalized.size > MAX_BRAND_ASSET_BYTES) throw new Error("Temizlenen marka yazısı SVG dosyası en fazla 1 MB olabilir."); return normalized; }
async function svgToPng(file: Blob): Promise<File> { const url = URL.createObjectURL(file); try { const image = new Image(); image.decoding = "async"; image.src = url; await image.decode(); const canvas = document.createElement("canvas"); canvas.width = 512; canvas.height = 512; const context = canvas.getContext("2d"); if (!context) throw new Error("Uygulama ikonu oluşturulamadı."); const scale = Math.min(440 / image.naturalWidth, 440 / image.naturalHeight); const width = image.naturalWidth * scale; const height = image.naturalHeight * scale; context.clearRect(0, 0, 512, 512); context.drawImage(image, (512-width)/2, (512-height)/2, width, height); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/png", .95)); if (!blob) throw new Error("Uygulama ikonu PNG olarak oluşturulamadı."); return new File([blob], `trove-app-icon-${Date.now()}.png`, { type: "image/png" }); } finally { URL.revokeObjectURL(url); } }

export function SettingsForm({ supabaseUrl, supabasePublishableKey, initial }: SettingsFormProps) {
  const [siteName,setSiteName]=useState(initial.siteName); const [siteTagline,setSiteTagline]=useState(initial.siteTagline); const [whatsappNumber,setWhatsappNumber]=useState(initial.whatsappNumber); const [whatsappDefaultMessage,setWhatsappDefaultMessage]=useState(initial.whatsappDefaultMessage);
  const [contactEmail,setContactEmail]=useState(initial.contactEmail); const [contactPhone,setContactPhone]=useState(initial.contactPhone); const [instagramUrl,setInstagramUrl]=useState(initial.instagramUrl); const [companyAddress,setCompanyAddress]=useState(initial.companyAddress); const [aboutText,setAboutText]=useState(initial.aboutText);
  const [logoUrl,setLogoUrl]=useState<string|null>(initial.logoUrl); const [brandWordmarkUrl,setBrandWordmarkUrl]=useState<string|null>(initial.brandWordmarkUrl); const [appIconUrl,setAppIconUrl]=useState<string|null>(initial.appIconUrl); const [logoFile,setLogoFile]=useState<File|null>(null); const [brandWordmarkFile,setBrandWordmarkFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [status,setStatus]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  const supabase=createBrowserClient(supabaseUrl,supabasePublishableKey);
  async function uploadBrandAsset(file:File,prefix:string){const extension=file.type==="image/png"?"png":"svg";const path=`${prefix}/${prefix}-${Date.now()}.${extension}`;const {error:uploadError}=await supabase.storage.from("brand-assets").upload(path,file,{contentType:file.type,cacheControl:"3600",upsert:false});if(uploadError)throw new Error(`Dosya yüklenemedi: ${uploadError.message}`);return supabase.storage.from("brand-assets").getPublicUrl(path).data.publicUrl;}
  async function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError(null);setStatus(null);try{let nextLogoUrl=logoUrl;let nextBrandWordmarkUrl=brandWordmarkUrl;let nextAppIconUrl=appIconUrl;if(logoFile){validateSvg(logoFile,"Logo");setStatus("Logo ve mobil uygulama simgesi hazırlanıyor...");nextLogoUrl=await uploadBrandAsset(logoFile,"logo");nextAppIconUrl=await uploadBrandAsset(await svgToPng(logoFile),"app-icon");}else if(nextLogoUrl&&!nextAppIconUrl){setStatus("Mevcut logodan mobil uygulama simgesi hazırlanıyor...");const response=await fetch(nextLogoUrl);if(!response.ok)throw new Error("Mevcut logo okunamadı.");nextAppIconUrl=await uploadBrandAsset(await svgToPng(await response.blob()),"app-icon");}if(brandWordmarkFile){validateSvg(brandWordmarkFile,"Marka yazısı");setStatus("Marka yazısı hazırlanıyor...");nextBrandWordmarkUrl=await uploadBrandAsset(await normalizeWordmarkSvg(brandWordmarkFile),"wordmark");}await saveSiteSettings({siteName,siteTagline,whatsappNumber,whatsappDefaultMessage,contactEmail,contactPhone,instagramUrl,companyAddress,aboutText,logoUrl:nextLogoUrl,brandWordmarkUrl:nextBrandWordmarkUrl,appIconUrl:nextAppIconUrl});setLogoUrl(nextLogoUrl);setBrandWordmarkUrl(nextBrandWordmarkUrl);setAppIconUrl(nextAppIconUrl);setLogoFile(null);setBrandWordmarkFile(null);setStatus("Şirket ve iletişim bilgileri kaydedildi.");}catch(caught){setError(caught instanceof Error?caught.message:"Ayarlar kaydedilemedi.");setStatus(null);}finally{setBusy(false);}}
  return <form className="adminImportForm" onSubmit={handleSubmit}>
    {error?<p className="adminError">{error}</p>:null}{status?<p className="adminStatus">{status}</p>:null}
    <label className="adminField adminUploadBox">Logo SVG<div className="adminLogoPreview" style={{minHeight:88,display:"flex",alignItems:"center",gap:18}}>{logoUrl?<img src={logoUrl} alt="Mevcut logo" style={{maxWidth:80,maxHeight:56}}/>:<span>Henüz logo yok</span>}{appIconUrl?<img src={appIconUrl} alt="Mobil uygulama simgesi" style={{width:56,height:56,objectFit:"contain",borderRadius:12}}/>:null}</div><input accept="image/svg+xml,.svg" disabled={busy} onChange={e=>setLogoFile(e.target.files?.[0]??null)} type="file"/><small>Header ve mobil ana ekran simgesinde kullanılır.</small></label>
    <label className="adminField adminUploadBox">Marka yazısı SVG<div className="adminLogoPreview" style={{minHeight:88,display:"flex",alignItems:"center",background:"transparent"}}>{brandWordmarkUrl?<img src={brandWordmarkUrl} alt="Mevcut marka yazısı" style={{maxWidth:220,maxHeight:56}}/>:<span>Henüz marka yazısı SVG yok</span>}</div><input accept="image/svg+xml,.svg" disabled={busy} onChange={e=>setBrandWordmarkFile(e.target.files?.[0]??null)} type="file"/></label>
    <label className="adminField">Site adı<input disabled={busy} maxLength={80} onChange={e=>setSiteName(e.target.value)} value={siteName}/></label>
    <label className="adminField">Ana slogan<input disabled={busy} maxLength={180} onChange={e=>setSiteTagline(e.target.value)} value={siteTagline}/></label>
    <label className="adminField adminFieldWide">Hakkımızda<textarea disabled={busy} maxLength={2000} rows={5} onChange={e=>setAboutText(e.target.value)} placeholder="Trove Teknoloji hakkında kısa tanıtım" value={aboutText}/></label>
    <div className="adminField adminFieldWide"><strong>İletişim</strong><small>Footer ve Hakkımızda sayfasında kullanılacak bilgiler.</small></div>
    <label className="adminField">E-posta<input disabled={busy} type="email" onChange={e=>setContactEmail(e.target.value)} placeholder="info@trove..." value={contactEmail}/></label>
    <label className="adminField">Telefon<input disabled={busy} onChange={e=>setContactPhone(e.target.value)} placeholder="+90 555 123 45 67" value={contactPhone}/></label>
    <label className="adminField">WhatsApp numarası<input disabled={busy} onChange={e=>setWhatsappNumber(e.target.value)} placeholder="905551234567" value={whatsappNumber}/></label>
    <label className="adminField">Instagram bağlantısı<input disabled={busy} onChange={e=>setInstagramUrl(e.target.value)} placeholder="https://instagram.com/..." value={instagramUrl}/></label>
    <label className="adminField adminFieldWide">İş yeri adresi<textarea disabled={busy} maxLength={500} rows={3} onChange={e=>setCompanyAddress(e.target.value)} placeholder="Açık adresi eksiksiz gir; harita ve yol tarifi bu metinden oluşturulur." value={companyAddress}/></label>
    <label className="adminField adminFieldWide">Varsayılan WhatsApp mesajı<textarea disabled={busy} maxLength={500} onChange={e=>setWhatsappDefaultMessage(e.target.value)} value={whatsappDefaultMessage}/></label>
    <button className="adminButton adminImportButton" disabled={busy} type="submit">{busy?"Kaydediliyor...":"Ayarları Kaydet"}</button>
  </form>;
}
