export type ImportedListing = {
  title: string;
  brand: string | null;
  model: string | null;
  price: number | null;
  condition: "new" | "used" | "refurbished" | null;
  storage: string | null;
  color: string | null;
  batteryHealth: string | null;
  description: string | null;
  categorySlug: "telefon" | "laptop-bilgisayar" | "bilgisayar-parcalari";
};

type JsonRecord = Record<string, unknown>;

function decodeHtml(value: string): string {
  return value.replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">");
}
function cleanText(value: unknown): string | null { if (typeof value !== "string") return null; const cleaned = decodeHtml(value).replace(/\s+/g, " ").trim(); return cleaned || null; }
function parseMeta(html: string): Map<string, string> { const result = new Map<string,string>(); for (const tag of html.match(/<meta\b[^>]*>/gi) ?? []) { const attrs=new Map<string,string>(); for(const match of tag.matchAll(/([:\w-]+)\s*=\s*["']([^"']*)["']/g)) attrs.set(match[1].toLowerCase(),decodeHtml(match[2])); const key=attrs.get("property")??attrs.get("name")??attrs.get("itemprop"); const content=attrs.get("content"); if(key&&content) result.set(key.toLowerCase(),content); } return result; }
function findJsonLdProduct(value: unknown): JsonRecord | null { if(!value||typeof value!=="object") return null; if(Array.isArray(value)){for(const item of value){const found=findJsonLdProduct(item);if(found)return found;}return null;} const record=value as JsonRecord; const type=record["@type"]; if(type==="Product"||(Array.isArray(type)&&type.includes("Product")))return record; for(const child of Object.values(record)){const found=findJsonLdProduct(child);if(found)return found;}return null; }
function extractJsonLd(html:string):unknown[]{const values:unknown[]=[];for(const match of html.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{values.push(JSON.parse(match[1].trim()));}catch{}}return values;}
function asRecord(value:unknown):JsonRecord|null{return value&&typeof value==="object"&&!Array.isArray(value)?value as JsonRecord:null;}
function propertyValue(product:JsonRecord|null,names:string[]):string|null{const properties=product?.additionalProperty;if(!Array.isArray(properties))return null;const wanted=names.map(name=>name.toLocaleLowerCase("tr-TR"));for(const item of properties){const record=asRecord(item);const name=cleanText(record?.name)?.toLocaleLowerCase("tr-TR");if(name&&wanted.includes(name))return cleanText(record?.value);}return null;}
function parsePrice(value:unknown):number|null{const text=typeof value==="number"?String(value):cleanText(value);if(!text)return null;let normalized=text.replace(/[^\d,.-]/g,"");if(/^\d{1,3}(\.\d{3})+$/.test(normalized))normalized=normalized.replace(/\./g,"");else if(/^\d{1,3}(,\d{3})+$/.test(normalized))normalized=normalized.replace(/,/g,"");else normalized=normalized.replace(/\.(?=.*\.)/g,"").replace(",", ".");const price=Number(normalized);return Number.isFinite(price)&&price>=0?price:null;}
function inferCondition(text:string,explicit:string|null):ImportedListing["condition"]{const source=`${explicit??""} ${text}`.toLocaleLowerCase("tr-TR");if(source.includes("yenilenmiş")||source.includes("refurbished"))return"refurbished";if(source.includes("2. el")||source.includes("ikinci el")||source.includes("kullanılmış"))return"used";if(source.includes("sıfır")||source.includes("yeni"))return"new";return null;}
function inferCategory(text:string):ImportedListing["categorySlug"]{const source=text.toLocaleLowerCase("tr-TR");if(["ekran kartı","işlemci","anakart","ram","ssd","harddisk","hard disk","bilgisayar parçası","bilgisayar bileşeni"].some(term=>source.includes(term)))return"bilgisayar-parcalari";if(["cep telefonu","akıllı telefon","iphone","smartphone","telefon"].some(term=>source.includes(term)))return"telefon";if(["macbook","laptop","notebook","dizüstü","masaüstü bilgisayar","all in one","bilgisayar"].some(term=>source.includes(term)))return"laptop-bilgisayar";throw new Error("İlan kategorisi Trove kategorileriyle eşleştirilemedi.");}
function inferBrand(title:string,explicit:string|null):string|null{if(explicit)return explicit;const brands=["Apple","Samsung","Xiaomi","Huawei","Oppo","Vivo","Realme","Honor","Asus","Lenovo","HP","Dell","Acer","MSI","Monster","Casper","Gigabyte"];return brands.find(brand=>new RegExp(`\\b${brand}\\b`,"i").test(title))??null;}
function extractBreadcrumbText(values:unknown[]):string{const names:string[]=[];const visit=(value:unknown)=>{if(!value||typeof value!=="object")return;if(Array.isArray(value))return value.forEach(visit);const record=value as JsonRecord;if(record["@type"]==="BreadcrumbList"&&Array.isArray(record.itemListElement)){for(const entry of record.itemListElement){const entryRecord=asRecord(entry);const itemRecord=asRecord(entryRecord?.item);const name=cleanText(entryRecord?.name)??cleanText(itemRecord?.name);if(name)names.push(name);}}Object.values(record).forEach(visit);};values.forEach(visit);return names.join(" ");}
function normalizeLabel(value:string):string{return value.toLocaleLowerCase("tr-TR").replace(/[:：]/g,"").replace(/\s+/g," ").trim();}
function fieldFromLines(lines:string[],labels:string[]):string|null{const normalizedLabels=labels.map(normalizeLabel);for(let index=0;index<lines.length;index+=1){const line=lines[index];const normalized=normalizeLabel(line);for(const label of normalizedLabels){if(normalized===label)return cleanText(lines[index+1]);if(normalized.startsWith(`${label} `))return cleanText(line.slice(label.length));}}return null;}
const CATEGORY_ONLY_LINES=new Set(["cep telefonu","telefon","bilgisayar","laptop","notebook","bilgisayar parçaları","bilgisayar parçası"]);
const FIELD_LABEL_LINES=new Set(["marka","model","dahili hafıza","hafıza","depolama kapasitesi","depolama","renk","pil sağlığı","batarya sağlığı","durumu","cihaz durumu","ürün durumu","fiyat","açıklama","ilan açıklaması"]);
function titleFromLines(lines:string[],text:string):string|null{const labeled=fieldFromLines(lines,["İlan Başlığı","Başlık"]);if(labeled&&labeled.length>=3)return labeled;const terms=["iphone","telefon","samsung","xiaomi","macbook","laptop","notebook","bilgisayar","ekran kartı","işlemci","anakart","ssd"];return lines.find(line=>{const normalized=normalizeLabel(line);return line.length>=8&&line.length<=180&&!CATEGORY_ONLY_LINES.has(normalized)&&!FIELD_LABEL_LINES.has(normalized)&&terms.some(term=>normalized.includes(term))&&!/\b(?:tl|₺)\b/i.test(line);})??(text.length<=180?cleanText(text):null);}
function descriptionFromText(text:string):string|null{const match=text.match(/(?:^|\n)\s*(?:açıklama|ilan açıklaması)\s*:?[ \t]*\n?([\s\S]*)$/i);return cleanText(match?.[1])?.slice(0,6000)??null;}
export function assertSahibindenUrl(value:string):URL{let url:URL;try{url=new URL(value.trim());}catch{throw new Error("Geçerli bir Sahibinden ilan linki girilmelidir.");}const host=url.hostname.toLowerCase().replace(/^www\./,"");if(url.protocol!=="https:"||host!=="sahibinden.com")throw new Error("Yalnızca sahibinden.com ilan linkleri destekleniyor.");return url;}
export function parseSahibindenText(rawText:string):ImportedListing{const text=rawText.replace(/\r/g,"").trim();if(text.length<20)throw new Error("Sahibinden ilan metni çok kısa. İlan detaylarını kopyalayıp yapıştırmalısın.");const lines=text.split("\n").map(line=>line.trim()).filter(Boolean);const title=titleFromLines(lines,text);if(!title)throw new Error("İlan başlığı yapıştırılan metinden belirlenemedi.");const brandExplicit=fieldFromLines(lines,["Marka"]);const model=fieldFromLines(lines,["Model"]);const storage=fieldFromLines(lines,["Dahili Hafıza","Hafıza","Depolama Kapasitesi","Depolama"]);const color=fieldFromLines(lines,["Renk"]);const batteryHealth=fieldFromLines(lines,["Pil Sağlığı","Batarya Sağlığı"]);const conditionText=fieldFromLines(lines,["Durumu","Cihaz Durumu","Ürün Durumu"]);const explicitPrice=fieldFromLines(lines,["Fiyat"]);const priceText=explicitPrice??lines.find(line=>/\d[\d.,\s]*\s*(?:TL|₺)\b/i.test(line))??null;return{title,brand:inferBrand(title,brandExplicit),model,price:parsePrice(priceText),condition:inferCondition(text,conditionText),storage,color,batteryHealth,description:descriptionFromText(text),categorySlug:inferCategory(text)};}
export function parseSahibindenHtml(html:string):ImportedListing{const meta=parseMeta(html);const jsonValues=extractJsonLd(html);const product=jsonValues.map(findJsonLdProduct).find(Boolean)??null;const rawTitle=cleanText(product?.name)??cleanText(meta.get("og:title"))??cleanText(meta.get("twitter:title"));if(!rawTitle)throw new Error("İlan başlığı Sahibinden sayfasından okunamadı.");const title=rawTitle.replace(/\s*[-|]\s*sahibinden\.com.*$/i,"").trim();const description=cleanText(product?.description)??cleanText(meta.get("og:description"))??cleanText(meta.get("description"));const brandRecord=asRecord(product?.brand);const brandExplicit=cleanText(brandRecord?.name)??cleanText(product?.brand)??propertyValue(product,["Marka"]);const model=cleanText(product?.model)??propertyValue(product,["Model"]);const storage=propertyValue(product,["Dahili Hafıza","Hafıza","Depolama"]);const color=propertyValue(product,["Renk"]);const batteryHealth=propertyValue(product,["Pil Sağlığı","Batarya Sağlığı"]);const conditionText=propertyValue(product,["Durumu","Cihaz Durumu"]);const offers=asRecord(product?.offers);const price=parsePrice(offers?.price??meta.get("product:price:amount")??meta.get("price"));const breadcrumb=extractBreadcrumbText(jsonValues);const categoryText=[title,description??"",breadcrumb].join(" ");return{title,brand:inferBrand(title,brandExplicit),model,price,condition:inferCondition(categoryText,conditionText),storage,color,batteryHealth,description,categorySlug:inferCategory(categoryText)};}
