"use client";

import { createBrowserClient } from "@supabase/ssr";
import { useState } from "react";
import { saveBrandSettings } from "./brand-settings-actions";

const MAX=1024*1024;
function validate(file:File){if(file.size>MAX)throw new Error("SVG dosyası en fazla 1 MB olabilir.");if(file.type!=="image/svg+xml"&&!file.name.toLowerCase().endsWith(".svg"))throw new Error("Yalnızca SVG yüklenebilir.");}
async function cleanSvg(file:File,removeImages=false){const doc=new DOMParser().parseFromString(await file.text(),"image/svg+xml");const svg=doc.documentElement as unknown as SVGSVGElement;if(doc.querySelector("parsererror")||svg.tagName.toLowerCase()!=="svg")throw new Error("SVG okunamadı.");svg.querySelectorAll("script,foreignObject,iframe,object,embed,metadata").forEach(n=>n.remove());if(removeImages)svg.querySelectorAll("image").forEach(n=>n.remove());svg.querySelectorAll("*").forEach(node=>Array.from(node.attributes).forEach(attr=>{const name=attr.name.toLowerCase(),value=attr.value.trim().toLowerCase();if(name.startsWith("on"))node.removeAttribute(attr.name);if((name==="href"||name==="xlink:href")&&/^(https?:|javascript:|data:text\/html)/.test(value))node.removeAttribute(attr.name);}));return new File([new XMLSerializer().serializeToString(svg)],file.name,{type:"image/svg+xml"});}
async function toPng(file:Blob){const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement("canvas");canvas.width=512;canvas.height=512;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Uygulama ikonu oluşturulamadı.");const scale=Math.min(440/image.naturalWidth,440/image.naturalHeight);const w=image.naturalWidth*scale,h=image.naturalHeight*scale;ctx.drawImage(image,(512-w)/2,(512-h)/2,w,h);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,"image/png",.95));if(!blob)throw new Error("PNG oluşturulamadı.");return new File([blob],`trove-app-icon-${Date.now()}.png`,{type:"image/png"});}finally{URL.revokeObjectURL(url);}}

type Props={supabaseUrl:string;supabasePublishableKey:string;initial:{logoUrl:string|null;wordmarkUrl:string|null;appIconUrl:string|null}};
export function BrandSettingsForm({supabaseUrl,supabasePublishableKey,initial}:Props){const [logoUrl,setLogoUrl]=useState(initial.logoUrl);const [wordmarkUrl,setWordmarkUrl]=useState(initial.wordmarkUrl);const [appIconUrl,setAppIconUrl]=useState(initial.appIconUrl);const [logo,setLogo]=useState<File|null>(null);const [wordmark,setWordmark]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<{ok:boolean;text:string}|null>(null);const supabase=createBrowserClient(supabaseUrl,supabasePublishableKey);
  async function upload(file:File,prefix:string){const ext=file.type==="image/png"?"png":"svg";const path=`${prefix}/${prefix}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from("brand-assets").upload(path,file,{contentType:file.type,cacheControl:"3600"});if(error)throw new Error(error.message);return supabase.storage.from("brand-assets").getPublicUrl(path).data.publicUrl;}
  async function submit(){setBusy(true);setMessage(null);try{let nextLogo=logoUrl,nextWordmark=wordmarkUrl,nextIcon=appIconUrl;if(logo){validate(logo);const clean=await cleanSvg(logo);nextLogo=await upload(clean,"logo");nextIcon=await upload(await toPng(clean),"app-icon");}if(wordmark){validate(wordmark);nextWordmark=await upload(await cleanSvg(wordmark,true),"wordmark");}const result=await saveBrandSettings({logoUrl:nextLogo,brandWordmarkUrl:nextWordmark,appIconUrl:nextIcon});setMessage({ok:result.ok,text:result.message});if(result.ok){setLogoUrl(nextLogo);setWordmarkUrl(nextWordmark);setAppIconUrl(nextIcon);setLogo(null);setWordmark(null);}}catch(e){setMessage({ok:false,text:e instanceof Error?e.message:"Dosyalar kaydedilemedi."});}finally{setBusy(false);}}
  return <section className="adminDashboardCard"><div className="adminPageHeader"><div><h2 style={{margin:0}}>Logo & Marka Kimliği</h2><p className="adminLead">Header logosu, marka yazısı ve mobil uygulama ikonunu yönet.</p></div></div>{message?<p className={message.ok?"adminSuccess":"adminError"}>{message.text}</p>:null}<div className="adminListingForm"><label className="adminField adminUploadBox">Logo SVG<div style={{minHeight:72,display:"flex",alignItems:"center",gap:14}}>{logoUrl?<img src={logoUrl} alt="Logo" style={{maxWidth:76,maxHeight:52}}/>:<span>Logo yok</span>}{appIconUrl?<img src={appIconUrl} alt="Uygulama ikonu" style={{width:50,height:50,objectFit:"contain",borderRadius:10}}/>:null}</div><input type="file" accept="image/svg+xml,.svg" onChange={e=>setLogo(e.target.files?.[0]??null)}/><small>Logo yüklendiğinde 512×512 uygulama ikonu da otomatik hazırlanır.</small></label><label className="adminField adminUploadBox">Marka yazısı SVG<div style={{minHeight:72,display:"flex",alignItems:"center"}}>{wordmarkUrl?<img src={wordmarkUrl} alt="Marka yazısı" style={{maxWidth:220,maxHeight:52}}/>:<span>Marka yazısı yok</span>}</div><input type="file" accept="image/svg+xml,.svg" onChange={e=>setWordmark(e.target.files?.[0]??null)}/></label></div><button className="adminButton" disabled={busy} type="button" onClick={submit}>{busy?"Kaydediliyor...":"Marka Kimliğini Kaydet"}</button></section>}
