import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase/server-client";
import { createTradeInDevice, deleteTradeInDevice, toggleTradeInDevice, updateTradeInDevice } from "./actions";

type Props={searchParams:Promise<{q?:string;type?:string;brand?:string}>};
export default async function AdminTradeInPage({searchParams}:Props){
 const {q,type,brand}=await searchParams; const supabase=await createSupabaseServerClient();
 const {data:allData}=await supabase.from("trade_in_devices").select("id,device_type,brand,model,storage,market_price_tr,market_price_passport,market_price_international,profit_margin_pct,is_active,updated_at").order("device_type").order("brand").order("model");
 const all=allData??[]; const types=Array.from(new Set(all.map(x=>String(x.device_type)))); const brands=Array.from(new Set(all.filter(x=>!type||x.device_type===type).map(x=>String(x.brand)))); const needle=(q??"").trim().toLocaleLowerCase("tr-TR");
 const devices=all.filter(x=>(!type||x.device_type===type)&&(!brand||x.brand===brand)&&(!needle||[x.device_type,x.brand,x.model,x.storage].some(v=>String(v??"").toLocaleLowerCase("tr-TR").includes(needle))));
 return <main className="adminShell adminShellWide">
  <header className="adminTopbar"><div><h1 className="adminPageTitle">Takas Cihaz Fiyatları</h1><p className="adminLead">Cihaz kataloğunu filtrele; fiyatı eksik kayıtları tamamlayıp TR/YD piyasa değerlerini yönet.</p></div><Link className="adminButton adminButtonSecondary" href="/admin/trade-in/costs">Masraf Referansları</Link></header>
  <section className="adminDashboardCard"><form className="adminListingForm" method="get"><label className="adminField">Ara<input name="q" defaultValue={q??""} placeholder="Marka, model, hafıza"/></label><label className="adminField">Cihaz türü<select name="type" defaultValue={type??""}><option value="">Tümü</option>{types.map(x=><option key={x}>{x}</option>)}</select></label><label className="adminField">Marka<select name="brand" defaultValue={brand??""}><option value="">Tümü</option>{brands.map(x=><option key={x}>{x}</option>)}</select></label><div className="adminFormActions"><button className="adminButton">Filtrele</button><Link className="adminButton adminButtonSecondary" href="/admin/trade-in">Temizle</Link></div></form><p className="adminLead">{devices.length} / {all.length} kayıt gösteriliyor. Otomatik eklenen katalog kayıtlarında fiyat 0 ise güncel piyasa fiyatını elle tamamla.</p></section>
  <section className="adminDashboardCard"><form className="adminListingForm" action={createTradeInDevice}><label className="adminField">Cihaz türü<select name="deviceType" required defaultValue="Telefon"><option>Telefon</option><option>Laptop / Bilgisayar</option><option>Tablet</option><option>Akıllı Saat</option><option>Kulaklık</option><option>Diğer</option></select></label><label className="adminField">Marka<input name="brand" required placeholder="Apple"/></label><label className="adminField">Model<input name="model" required placeholder="iPhone 15 Pro"/></label><label className="adminField">Hafıza / varyant<input name="storage" placeholder="256 GB"/></label><label className="adminField">TR güncel fiyat<input name="marketPriceTr" required inputMode="decimal" placeholder="50000"/></label><label className="adminField">Yurt dışı kayıtlı fiyat<input name="marketPricePassport" required inputMode="decimal" placeholder="40000"/></label><label className="adminField">Yurt dışı kayıtsız fiyat<input name="marketPriceInternational" required inputMode="decimal" placeholder="31000"/></label><label className="adminField">Trove kâr marjı %<input name="profitMarginPct" required inputMode="decimal" defaultValue="15"/></label><div className="adminFormActions"><button className="adminButton" type="submit">Cihazı Listeye Ekle</button></div></form></section>
  <section className="listingSection"><div className="sectionHeading"><div><h2>Cihaz referansları</h2><p>{devices.length} cihaz / varyant</p></div></div>{devices.length?<div className="adminDraftList">{devices.map(device=><article className="adminDashboardCard" key={device.id} style={{marginBottom:14}}><form className="adminListingForm" action={updateTradeInDevice}><input type="hidden" name="id" value={device.id}/><label className="adminField">Tür<input name="deviceType" defaultValue={device.device_type} required/></label><label className="adminField">Marka<input name="brand" defaultValue={device.brand} required/></label><label className="adminField">Model<input name="model" defaultValue={device.model} required/></label><label className="adminField">Varyant<input name="storage" defaultValue={device.storage}/></label><label className="adminField">TR fiyat<input name="marketPriceTr" inputMode="decimal" defaultValue={Number(device.market_price_tr)} required/></label><label className="adminField">YD kayıtlı<input name="marketPricePassport" inputMode="decimal" defaultValue={Number(device.market_price_passport)} required/></label><label className="adminField">YD kayıtsız<input name="marketPriceInternational" inputMode="decimal" defaultValue={Number(device.market_price_international)} required/></label><label className="adminField">Kâr marjı %<input name="profitMarginPct" inputMode="decimal" defaultValue={Number(device.profit_margin_pct)} required/></label><div className="adminFormActions"><button className="adminButton">Fiyatları Kaydet</button></div></form><div className="adminInlineActions" style={{marginTop:12}}><form action={toggleTradeInDevice}><input type="hidden" name="id" value={device.id}/><input type="hidden" name="active" value={String(device.is_active)}/><button className="adminButton adminButtonSecondary">{device.is_active?"Gizle":"Göster"}</button></form><form action={deleteTradeInDevice}><input type="hidden" name="id" value={device.id}/><button className="adminButton adminDangerButton">Sil</button></form><span className="adminStatusPill">{device.is_active?"Aktif":"Gizli"}</span></div></article>)}</div>:<p className="emptyState">Filtreye uygun cihaz bulunamadı.</p>}</section>
 </main>;
}
