"use client";

import { useState } from "react";
import { saveCompanyContactSettings } from "./company-legal-actions";

type Initial={siteName:string;siteTagline:string;aboutText:string;contactEmail:string;contactPhone:string;whatsappNumber:string;instagramUrl:string;companyAddress:string;whatsappDefaultMessage:string};
export function CompanyContactForm({initial}:{initial:Initial}){
  const [form,setForm]=useState(initial); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<{ok:boolean;text:string}|null>(null);
  const set=(key:keyof Initial,value:string)=>setForm(prev=>({...prev,[key]:value}));
  async function submit(){setBusy(true);setMessage(null);const result=await saveCompanyContactSettings(form);setMessage({ok:result.ok,text:result.message});setBusy(false);}
  return <section className="adminDashboardCard"><div className="adminPageHeader"><div><h2 style={{margin:0}}>Şirket & İletişim</h2><p className="adminLead">Müşterinin göreceği marka tanıtımı, iletişim ve mağaza adresi.</p></div></div>{message?<p className={message.ok?"adminSuccess":"adminError"}>{message.text}</p>:null}<div className="adminListingForm"><label className="adminField">Marka / işletme adı<input value={form.siteName} onChange={e=>set("siteName",e.target.value)} /></label><label className="adminField">Kısa slogan<input value={form.siteTagline} onChange={e=>set("siteTagline",e.target.value)} /></label><label className="adminField adminFieldWide">Hakkımızda<textarea rows={6} value={form.aboutText} onChange={e=>set("aboutText",e.target.value)} /></label><label className="adminField">E-posta<input type="email" value={form.contactEmail} onChange={e=>set("contactEmail",e.target.value)} /></label><label className="adminField">Telefon<input value={form.contactPhone} onChange={e=>set("contactPhone",e.target.value)} /></label><label className="adminField">WhatsApp<input value={form.whatsappNumber} onChange={e=>set("whatsappNumber",e.target.value)} /></label><label className="adminField">Instagram URL<input value={form.instagramUrl} onChange={e=>set("instagramUrl",e.target.value)} /></label><label className="adminField adminFieldWide">Mağaza / merkez adresi<textarea rows={3} value={form.companyAddress} onChange={e=>set("companyAddress",e.target.value)} /></label><label className="adminField adminFieldWide">Varsayılan WhatsApp mesajı<textarea rows={3} value={form.whatsappDefaultMessage} onChange={e=>set("whatsappDefaultMessage",e.target.value)} /></label></div><button className="adminButton" disabled={busy} type="button" onClick={submit}>{busy?"Kaydediliyor...":"Şirket Bilgilerini Kaydet"}</button></section>;
}
