"use client";

import { useState } from "react";
import { saveEtbisSettings } from "./company-legal-actions";

type Initial={legalCompanyName:string;taxNumber:string;mersisNumber:string;kepAddress:string;tradeRegistryNumber:string;chamberName:string;etbisRegistered:boolean;etbisSiteUrl:string;etbisQrUrl:string};
export function EtbisSettingsForm({initial}:{initial:Initial}){
  const [form,setForm]=useState(initial); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<{ok:boolean;text:string}|null>(null);
  const set=<K extends keyof Initial>(key:K,value:Initial[K])=>setForm(prev=>({...prev,[key]:value}));
  async function submit(){setBusy(true);setMessage(null);const result=await saveEtbisSettings(form);setMessage({ok:result.ok,text:result.message});setBusy(false);}
  return <section className="adminDashboardCard"><div className="adminPageHeader"><div><h2 style={{margin:0}}>Yasal Bilgiler & ETBİS</h2><p className="adminLead">E-ticaret faaliyeti için şirketin yasal ve ETBİS kayıt bilgilerini tek yerde tut.</p></div></div>{message?<p className={message.ok?"adminSuccess":"adminError"}>{message.text}</p>:null}<div className="adminListingForm"><label className="adminField adminFieldWide">ETBİS durumu<select value={form.etbisRegistered?"registered":"not_registered"} onChange={e=>set("etbisRegistered",e.target.value==="registered")}><option value="not_registered">Henüz kayıtlı değil</option><option value="registered">ETBİS kayıtlı</option></select></label><label className="adminField adminFieldWide">Ticaret unvanı<input value={form.legalCompanyName} onChange={e=>set("legalCompanyName",e.target.value)} /></label><label className="adminField">Vergi kimlik numarası<input inputMode="numeric" value={form.taxNumber} onChange={e=>set("taxNumber",e.target.value)} /></label><label className="adminField">MERSİS numarası<input inputMode="numeric" value={form.mersisNumber} onChange={e=>set("mersisNumber",e.target.value)} /></label><label className="adminField">KEP adresi<input value={form.kepAddress} onChange={e=>set("kepAddress",e.target.value)} placeholder="...@hs01.kep.tr" /></label><label className="adminField">Ticaret sicil no<input value={form.tradeRegistryNumber} onChange={e=>set("tradeRegistryNumber",e.target.value)} /></label><label className="adminField adminFieldWide">Bağlı oda / meslek kuruluşu<input value={form.chamberName} onChange={e=>set("chamberName",e.target.value)} /></label><label className="adminField">ETBİS kayıt / sorgu bağlantısı<input value={form.etbisSiteUrl} onChange={e=>set("etbisSiteUrl",e.target.value)} placeholder="https://etbis.ticaret.gov.tr/..." /></label><label className="adminField">ETBİS karekod görsel URL'si<input value={form.etbisQrUrl} onChange={e=>set("etbisQrUrl",e.target.value)} placeholder="Kayıt sonrası eklenebilir" /></label></div><p className="adminStatus">ETBİS kaydı sistem tarafından otomatik yapılmaz. Bu alanlar e-Devlet/ETBİS kaydından sonra site ve operasyon bilgilerinin doğru tutulması için hazırlanmıştır.</p><button className="adminButton" disabled={busy} type="button" onClick={submit}>{busy?"Kaydediliyor...":"Yasal / ETBİS Bilgilerini Kaydet"}</button></section>;
}
