"use client";

import { useState } from "react";
import { savePurchaseSettings } from "./purchase-settings-actions";

type Props={initial:{purchaseEnabled:boolean;bankName:string;accountHolder:string;iban:string;paytrEnabled:boolean;paytrTestMode:boolean;paytrNoInstallment:boolean;paytrMaxInstallment:number;paytrConfigured:boolean}};
function formatIban(value:string){const compact=value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,26);return compact.replace(/(.{4})/g,"$1 ").trim()}
export function PurchaseSettingsForm({initial}:Props){
 const[purchaseEnabled,setPurchaseEnabled]=useState(initial.purchaseEnabled);const[bankName,setBankName]=useState(initial.bankName);const[accountHolder,setAccountHolder]=useState(initial.accountHolder);const[iban,setIban]=useState(formatIban(initial.iban));
 const[paytrEnabled,setPaytrEnabled]=useState(initial.paytrEnabled);const[paytrTestMode,setPaytrTestMode]=useState(initial.paytrTestMode);const[paytrNoInstallment,setPaytrNoInstallment]=useState(initial.paytrNoInstallment);const[paytrMaxInstallment,setPaytrMaxInstallment]=useState(initial.paytrMaxInstallment);
 const[busy,setBusy]=useState(false);const[status,setStatus]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 async function submit(){setBusy(true);setStatus(null);setError(null);try{const result=await savePurchaseSettings({purchaseEnabled,bankName,accountHolder,iban,paytrEnabled,paytrTestMode,paytrNoInstallment,paytrMaxInstallment});if(!result.ok){setError(result.message);return}setStatus("Satın alma ve ödeme ayarları kaydedildi.")}catch{setError("Ayarlar kaydedilirken beklenmeyen bir hata oluştu.")}finally{setBusy(false)}}
 return <section className="adminDashboardCard" style={{marginTop:16}}><div className="adminPageHeader"><div><h2 style={{margin:0}}>Satın Alma & Ödeme</h2><p className="adminLead">Havale/EFT mevcut akıştır. PayTR altyapısı ayrıca hazırlanmıştır ve anahtarlar tanımlanınca test modunda etkinleştirilebilir.</p></div></div>{error?<p className="adminError">{error}</p>:null}{status?<p className="adminSuccess">{status}</p>:null}
 <div className="adminListingForm"><label className="adminField adminFieldWide"><span>Satın alma sistemi</span><select disabled={busy} value={purchaseEnabled?"on":"off"} onChange={e=>setPurchaseEnabled(e.target.value==="on")}><option value="off">Kapalı — satın al butonu görünmez</option><option value="on">Açık — mevcut satın alma formu kullanılabilir</option></select></label>
 <label className="adminField">Banka adı<input disabled={busy} maxLength={100} value={bankName} onChange={e=>setBankName(e.target.value)}/></label><label className="adminField">Hesap sahibi<input disabled={busy} maxLength={120} value={accountHolder} onChange={e=>setAccountHolder(e.target.value)}/></label><label className="adminField adminFieldWide">IBAN<input disabled={busy} maxLength={32} value={iban} onChange={e=>setIban(formatIban(e.target.value))}/></label>
 <div className="adminField adminFieldWide"><span>PayTR sunucu anahtarları</span><strong>{initial.paytrConfigured?"Hazır":"Eksik"}</strong><small>Merchant ID/Key/Salt panelde veya veritabanında tutulmaz; sadece sunucu ortam değişkenlerinde saklanır.</small></div>
 <label className="adminField"><span>PayTR</span><select disabled={busy} value={paytrEnabled?"on":"off"} onChange={e=>setPaytrEnabled(e.target.value==="on")}><option value="off">Kapalı</option><option value="on" disabled={!initial.paytrConfigured}>Açık</option></select></label><label className="adminField"><span>PayTR modu</span><select disabled={busy||!paytrEnabled} value={paytrTestMode?"test":"live"} onChange={e=>setPaytrTestMode(e.target.value==="test")}><option value="test">Test</option><option value="live">Canlı</option></select></label>
 <label className="adminField"><span>Taksit</span><select disabled={busy||!paytrEnabled} value={paytrNoInstallment?"off":"on"} onChange={e=>setPaytrNoInstallment(e.target.value==="off")}><option value="on">İzin ver</option><option value="off">Tek çekim</option></select></label><label className="adminField"><span>Azami taksit</span><input disabled={busy||!paytrEnabled||paytrNoInstallment} type="number" min={0} max={12} value={paytrMaxInstallment} onChange={e=>setPaytrMaxInstallment(Number(e.target.value)||0)}/><small>0 = PayTR mağaza ayarını kullanır.</small></label></div>
 <button className="adminButton" disabled={busy} type="button" onClick={submit}>{busy?"Kaydediliyor...":"Ödeme Ayarlarını Kaydet"}</button></section>;
}
