"use client";

import { FormEvent, useMemo, useState } from "react";
import type { Locale } from "../../../modules/i18n";
import type { ServicePriceReference } from "../../../modules/technical-service/pricing";

const DEVICE_MODELS:Record<string,Record<string,string[]>>={Telefon:{Apple:["iPhone 16 Pro Max","iPhone 16 Pro","iPhone 16","iPhone 15 Pro Max","iPhone 15 Pro","iPhone 15","iPhone 14 Pro Max","iPhone 14 Pro","iPhone 14","iPhone 13 Pro Max","iPhone 13 Pro","iPhone 13","iPhone 12 Pro Max","iPhone 12 Pro","iPhone 12","iPhone 11"],Samsung:["Galaxy S25 Ultra","Galaxy S25+","Galaxy S25","Galaxy S24 Ultra","Galaxy S24+","Galaxy S24","Galaxy S23 Ultra","Galaxy S23","Galaxy A56","Galaxy A55","Galaxy A35"],Xiaomi:["Xiaomi 15 Ultra","Xiaomi 15","Xiaomi 14","Redmi Note 14 Pro+","Redmi Note 14 Pro","Redmi Note 13 Pro"],Huawei:["Pura 70 Ultra","Pura 70 Pro","Pura 70","Nova 13 Pro","Nova 13"],Honor:["Magic7 Pro","Magic6 Pro","Honor 400 Pro","Honor 400","Honor 200"],Oppo:["Find X8 Pro","Find X8","Reno13 Pro","Reno13","Reno12"],Diğer:["Diğer / Listede yok"]},Laptop:{Apple:["MacBook Air 13 M4","MacBook Air 15 M4","MacBook Pro 14","MacBook Pro 16","MacBook Air M3","MacBook Air M2"],Asus:["ROG Strix","ROG Zephyrus","TUF Gaming","Vivobook","Zenbook"],Lenovo:["Legion","LOQ","ThinkPad","IdeaPad","Yoga"],HP:["Omen","Victus","Pavilion","Envy","ProBook"],Dell:["Alienware","G Series","XPS","Inspiron","Latitude"],MSI:["Raider","Vector","Stealth","Katana","Cyborg","Modern"],Diğer:["Diğer / Listede yok"]}};
type Estimate={min:number;max:number}|null;

const GROUPS=[
 {title:"Ekran & Gövde",codes:["screen","display","touch","rear_glass"]},
 {title:"Kamera & Biyometrik",codes:["camera","camera_lens","front_camera","rear_camera","face_id","fingerprint"]},
 {title:"Şarj & Güç",codes:["battery","charge","charging_port","wireless_charging","power","power_button","volume_buttons","no_power"]},
 {title:"Ses & Titreşim",codes:["audio","speaker","earpiece","microphone","vibration"]},
 {title:"Bağlantı & Sensörler",codes:["wireless","cellular","proximity_sensor","sensors"]},
 {title:"Anakart & Sistem",codes:["liquid","liquid_cleaning","motherboard","software","data_transfer"]},
] as const;

const copy={
 tr:{device:"Cihaz",fault:"Arıza",offer:"Teklif",deviceInfo:"Cihaz Bilgileri",deviceInfoText:"Marka ve modeli seç.",deviceType:"Cihaz türü",brand:"Marka",model:"Model",select:"Seç",continue:"Devam Et →",faultTitle:"Detaylı Arıza Tespiti",faultText:"Cihazdaki tüm sorunları ayrı ayrı işaretle. Birden fazla arıza birlikte fiyatlandırılır.",noPrices:"Bu cihaz için henüz servis fiyat kalemi tanımlı değil.",faultDetail:"Arıza detayı",faultPlaceholder:"Belirtiyi, ne zaman başladığını ve varsa önceki işlemi yazabilirsin",note:"Ek not",notePlaceholder:"Varsa ek bilgi",back:"← Geri",calculating:"Hesaplanıyor...",seePrice:"Tahmini Fiyatı Gör →",estimateTitle:"Tahmini Servis Fiyatı",estimateText:"Kesin fiyat cihaz teknik kontrolden sonra netleşir.",estimateRange:"Tahmini servis aralığı",estimateCalculated:"Seçilen cihaz ve tüm arıza kalemleri birlikte hesaplandı.",estimatePrice:"Tahmini servis fiyatı",checkRequired:"Kontrol gerekli",noReference:"Bu arıza için referans fiyat tanımlanmamış.",name:"Ad Soyad",phone:"Telefon",getOffer:"Detaylı Teklif Al",calcError:"Fiyat hesaplanamadı.",devicePhone:"Telefon",other:"Diğer",otherModel:"Diğer / Listede yok"},
 en:{device:"Device",fault:"Issue",offer:"Quote",deviceInfo:"Device Information",deviceInfoText:"Select the brand and model.",deviceType:"Device type",brand:"Brand",model:"Model",select:"Select",continue:"Continue →",faultTitle:"Detailed Diagnostics",faultText:"Select every issue separately. Multiple faults are priced together.",noPrices:"No service price items have been defined for this device yet.",faultDetail:"Issue details",faultPlaceholder:"Describe the symptom, when it started and any previous repair",note:"Additional note",notePlaceholder:"Any additional information",back:"← Back",calculating:"Calculating...",seePrice:"View Estimated Price →",estimateTitle:"Estimated Service Price",estimateText:"The final price is confirmed after a technical inspection of the device.",estimateRange:"Estimated service range",estimateCalculated:"Calculated using the device and all selected faults.",estimatePrice:"Estimated service price",checkRequired:"Inspection required",noReference:"No reference price is defined for this issue.",name:"Full Name",phone:"Phone",getOffer:"Get Detailed Quote",calcError:"Price could not be calculated.",devicePhone:"Phone",other:"Other",otherModel:"Other / Not listed"}
} as const;

export function ServiceOfferForm({whatsappNumber,prices,locale}:{whatsappNumber:string;prices:ServicePriceReference[];locale:Locale}){
 const t=copy[locale];const en=locale==="en";
 const[step,setStep]=useState(1);const[estimate,setEstimate]=useState<Estimate>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[data,setData]=useState({deviceType:"",brand:"",model:"",name:"",phone:"",detail:"",note:""});const[faults,setFaults]=useState<string[]>([]);
 const deviceTypes=useMemo(()=>Array.from(new Set([...Object.keys(DEVICE_MODELS),...prices.map(x=>x.device_type)])),[prices]);
 const brands=useMemo(()=>{if(!data.deviceType)return[];const defaults=Object.keys(DEVICE_MODELS[data.deviceType]??{});const scoped=prices.filter(x=>x.device_type===data.deviceType&&x.brand).map(x=>x.brand);return Array.from(new Set([...defaults,...scoped]))},[data.deviceType,prices]);
 const models=useMemo(()=>{if(!data.deviceType||!data.brand)return[];const defaults=DEVICE_MODELS[data.deviceType]?.[data.brand]??[];const scoped=prices.filter(x=>x.device_type===data.deviceType&&x.brand===data.brand&&x.model).map(x=>x.model);return Array.from(new Set([...defaults,...scoped]))},[data.deviceType,data.brand,prices]);
 const availableFaults=useMemo(()=>{if(!data.deviceType)return[];const map=new Map<string,{row:ServicePriceReference;score:number}>();for(const row of prices){if(row.device_type!==data.deviceType)continue;let score=0;if(!row.brand&&!row.model)score=1;else if(row.brand===data.brand&&!row.model)score=2;else if(row.brand===data.brand&&row.model===data.model)score=3;else continue;const current=map.get(row.fault_code);if(!current||score>current.score)map.set(row.fault_code,{row,score})}return Array.from(map.values()).map(x=>x.row)},[prices,data.deviceType,data.brand,data.model]);
 const groupedFaults=useMemo(()=>{const used=new Set<string>();const groups=GROUPS.map(group=>{const items=group.codes.map(code=>availableFaults.find(x=>x.fault_code===code)).filter((x):x is ServicePriceReference=>Boolean(x));items.forEach(x=>used.add(x.fault_code));return{title:group.title,items}}).filter(x=>x.items.length);const other=availableFaults.filter(x=>!used.has(x.fault_code));if(other.length)groups.push({title:en?"Other":"Diğer İşlemler",items:other});return groups},[availableFaults,en]);
 function set(key:keyof typeof data,value:string){setData(x=>({...x,[key]:value}));setEstimate(null)}function money(v:number){return `${Math.round(v).toLocaleString(locale==="en"?"en-US":"tr-TR")} ₺`}function toggle(code:string){setFaults(x=>x.includes(code)?x.filter(y=>y!==code):[...x,code]);setEstimate(null)}
 function displayDevice(value:string){if(!en)return value;if(value==="Telefon")return t.devicePhone;return value}function displayBrand(value:string){return en&&value==="Diğer"?t.other:value}function displayModel(value:string){return en&&value==="Diğer / Listede yok"?t.otherModel:value}
 async function calculate(){setLoading(true);setError("");try{const r=await fetch("/api/technical-service/estimate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({deviceType:data.deviceType,brand:data.brand,model:data.model,faultCodes:faults})});const j=await r.json();if(!r.ok)throw new Error(j.error||t.calcError);setEstimate(j)}catch(e){setEstimate(null);setError(e instanceof Error?e.message:t.calcError)}finally{setLoading(false)}}
 async function next(){if(step===1&&(!data.deviceType||!data.brand||!data.model))return;if(step===2){if(!faults.length)return;await calculate();setStep(3);return}setStep(x=>Math.min(3,x+1))}
 function submit(e:FormEvent){e.preventDefault();if(!data.name||!data.phone||!whatsappNumber)return;const labels=faults.map(code=>availableFaults.find(x=>x.fault_code===code)?.fault_label).filter(Boolean);const msg=en?["Hello Trove Technology, I would like a detailed technical service quote.",estimate?`Estimated service range: ${money(estimate.min)} - ${money(estimate.max)}`:"The estimated price will be checked in store.","",`Device: ${displayDevice(data.deviceType)} / ${displayBrand(data.brand)} / ${displayModel(data.model)}`,"Issues:",...labels.map(x=>`• ${x}`),data.detail?`Issue details: ${data.detail}`:"",data.note?`Additional note: ${data.note}`:"","",`Full Name: ${data.name}`,`Phone: ${data.phone}`,"The final price is confirmed after the device is physically inspected."].filter(Boolean).join("\n"):["Merhaba Trove Teknoloji, teknik servis için detaylı teklif almak istiyorum.",estimate?`Tahmini servis aralığı: ${money(estimate.min)} - ${money(estimate.max)}`:"Tahmini fiyat mağazada kontrol edilecek.","",`Cihaz: ${data.deviceType} / ${data.brand} / ${data.model}`,"Arızalar:",...labels.map(x=>`• ${x}`),data.detail?`Arıza detayı: ${data.detail}`:"",data.note?`Ek not: ${data.note}`:"","",`Ad Soyad: ${data.name}`,`Telefon: ${data.phone}`,"Tahmini fiyat cihaz fiziksel olarak kontrol edildikten sonra kesinleşir."].filter(Boolean).join("\n");window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(msg)}`,"_blank","noopener,noreferrer")}
 return <form className="tradeForm serviceOfferForm" onSubmit={submit}><div className="tradeProgress"><div className="tradeProgressBar"><span style={{width:`${step/3*100}%`}}/></div><div className="tradeSteps"><button type="button" className={step===1?"active":""} onClick={()=>setStep(1)}>1 <span>{t.device}</span></button><button type="button" className={step===2?"active":""} onClick={()=>step>1&&setStep(2)}>2 <span>{t.fault}</span></button><button type="button" className={step===3?"active":""} onClick={()=>step>2&&setStep(3)}>3 <span>{t.offer}</span></button></div></div>
 {step===1?<section className="tradeStep"><div><span className="tradeEyebrow">1 / 3</span><h2>{t.deviceInfo}</h2><p>{t.deviceInfoText}</p></div><div className="tradeGrid"><label>{t.deviceType}<select value={data.deviceType} onChange={e=>{set("deviceType",e.target.value);setData(x=>({...x,brand:"",model:""}));setFaults([])}}><option value="">{t.select}</option>{deviceTypes.map(x=><option key={x} value={x}>{displayDevice(x)}</option>)}</select></label><label>{t.brand}<select disabled={!data.deviceType} value={data.brand} onChange={e=>{set("brand",e.target.value);setData(x=>({...x,model:""}));setFaults([])}}><option value="">{t.select}</option>{brands.map(x=><option key={x} value={x}>{displayBrand(x)}</option>)}</select></label><label className="wide">{t.model}<select disabled={!data.brand} value={data.model} onChange={e=>{set("model",e.target.value);setFaults([])}}><option value="">{t.select}</option>{models.map(x=><option key={x} value={x}>{displayModel(x)}</option>)}</select></label></div><button className="tradePrimary" type="button" disabled={!data.deviceType||!data.brand||!data.model} onClick={next}>{t.continue}</button></section>:null}
 {step===2?<section className="tradeStep"><div><span className="tradeEyebrow">2 / 3</span><h2>{t.faultTitle}</h2><p>{t.faultText}</p></div><div className="serviceFaultGroups">{groupedFaults.map(group=><section className="serviceFaultGroup" key={group.title}><h3>{group.title}</h3><div className="serviceOfferFaults">{group.items.map(x=><label className={faults.includes(x.fault_code)?"isSelected":""} key={x.fault_code}><input type="checkbox" checked={faults.includes(x.fault_code)} onChange={()=>toggle(x.fault_code)}/><span>{x.fault_label}</span></label>)}</div></section>)}</div>{!availableFaults.length?<div className="emptyState">{t.noPrices}</div>:null}<div className="tradeGrid"><label className="wide">{t.faultDetail}<textarea value={data.detail} onChange={e=>set("detail",e.target.value)} placeholder={t.faultPlaceholder}/></label><label className="wide">{t.note}<textarea value={data.note} onChange={e=>set("note",e.target.value)} placeholder={t.notePlaceholder}/></label></div><div className="tradeActions"><button type="button" onClick={()=>setStep(1)}>{t.back}</button><button className="tradePrimary" type="button" disabled={!faults.length||loading} onClick={next}>{loading?t.calculating:t.seePrice}</button></div></section>:null}
 {step===3?<section className="tradeStep"><div><span className="tradeEyebrow">3 / 3</span><h2>{t.estimateTitle}</h2><p>{t.estimateText}</p></div>{estimate?<div className="tradeEstimate"><div><span>{t.estimateRange}</span><strong>{money(estimate.min)} – {money(estimate.max)}</strong><small>{t.estimateCalculated}</small></div></div>:<div className="tradeEstimate tradeEstimateUnavailable"><div><span>{t.estimatePrice}</span><strong>{t.checkRequired}</strong><small>{error||t.noReference}</small></div></div>}<div className="tradeGrid"><label>{t.name}<input value={data.name} onChange={e=>set("name",e.target.value)}/></label><label>{t.phone}<input inputMode="tel" value={data.phone} onChange={e=>set("phone",e.target.value)}/></label></div><div className="tradeActions"><button type="button" onClick={()=>setStep(2)}>{t.back}</button><button className="tradePrimary" type="submit" disabled={!data.name||!data.phone||!whatsappNumber}>{t.getOffer}</button></div></section>:null}</form>
}
