"use client";

import { FormEvent, useMemo, useState } from "react";
import type { Locale } from "../../../modules/i18n";
import type { ServicePriceReference } from "../../../modules/technical-service/pricing";
import type { TradeInCatalogDevice } from "../../../modules/trade-in/catalog";

type Estimate={min:number;max:number}|null;
type Option={value:string;tr:string;en:string;code?:string};
type Question={key:string;tr:string;en:string;options:Option[]};

const Q:Record<string,Question>={
 power:{key:"power",tr:"Güç / açılmama",en:"Power / no power",options:[{value:"no_power",tr:"Cihaz açılmıyor",en:"Device does not power on",code:"no_power"}]},
 screen:{key:"screen",tr:"Ekran",en:"Screen",options:[{value:"screen",tr:"Ekran / görüntü / dokunmatik sorunu",en:"Screen / display / touch issue",code:"screen"}]},
 rear:{key:"rear",tr:"Arka cam / kapak",en:"Rear glass / cover",options:[{value:"rear_glass",tr:"Arka cam / kapak değişimi",en:"Rear glass / cover replacement",code:"rear_glass"}]},
 battery:{key:"battery",tr:"Batarya",en:"Battery",options:[{value:"battery",tr:"Batarya değişimi / batarya servisi",en:"Battery replacement / service",code:"battery"}]},
 charging:{key:"charging",tr:"Şarj",en:"Charging",options:[{value:"charging_port",tr:"Şarj soketi / kablolu şarj",en:"Charging port / wired charging",code:"charging_port"},{value:"wireless_charging",tr:"Kablosuz şarj",en:"Wireless charging",code:"wireless_charging"}]},
 camera:{key:"camera",tr:"Kamera",en:"Camera",options:[{value:"camera_lens",tr:"Kamera lens camı",en:"Camera lens glass",code:"camera_lens"},{value:"front_camera",tr:"Ön kamera",en:"Front camera",code:"front_camera"},{value:"rear_camera",tr:"Arka kamera",en:"Rear camera",code:"rear_camera"}]},
 biometric:{key:"biometric",tr:"Biyometrik",en:"Biometric",options:[{value:"face_id",tr:"Face ID / yüz tanıma",en:"Face ID / face recognition",code:"face_id"},{value:"fingerprint",tr:"Parmak izi",en:"Fingerprint",code:"fingerprint"}]},
 audio:{key:"audio",tr:"Ses",en:"Audio",options:[{value:"speaker",tr:"Hoparlör",en:"Speaker",code:"speaker"},{value:"earpiece",tr:"Ahize",en:"Earpiece",code:"earpiece"},{value:"microphone",tr:"Mikrofon",en:"Microphone",code:"microphone"}]},
 buttons:{key:"buttons",tr:"Tuş / titreşim",en:"Buttons / vibration",options:[{value:"power_button",tr:"Güç tuşu",en:"Power button",code:"power_button"},{value:"volume_buttons",tr:"Ses tuşları",en:"Volume buttons",code:"volume_buttons"},{value:"vibration",tr:"Titreşim",en:"Vibration",code:"vibration"}]},
 network:{key:"network",tr:"Bağlantı",en:"Connectivity",options:[{value:"wireless",tr:"Wi-Fi / Bluetooth",en:"Wi-Fi / Bluetooth",code:"wireless"},{value:"cellular",tr:"Şebeke / SIM",en:"Cellular / SIM",code:"cellular"}]},
 sensor:{key:"sensor",tr:"Sensör",en:"Sensor",options:[{value:"proximity_sensor",tr:"Yakınlık / ışık sensörü",en:"Proximity / light sensor",code:"proximity_sensor"},{value:"sensors",tr:"Diğer sensör",en:"Other sensor",code:"sensors"}]},
 liquid:{key:"liquid",tr:"Sıvı teması",en:"Liquid contact",options:[{value:"liquid_cleaning",tr:"Sıvı teması / oksit temizliği",en:"Liquid contact / oxidation cleaning",code:"liquid_cleaning"}]},
 system:{key:"system",tr:"Sistem / anakart",en:"System / motherboard",options:[{value:"motherboard",tr:"Anakart arızası",en:"Motherboard issue",code:"motherboard"},{value:"software",tr:"Yazılım / sistem",en:"Software / system",code:"software"}]},
 data:{key:"data",tr:"Veri",en:"Data",options:[{value:"data_transfer",tr:"Veri aktarımı / yedekleme",en:"Data transfer / backup",code:"data_transfer"}]},
};

function questionsFor(type:string){
 if(type==="Kulaklık")return [Q.power,Q.battery,Q.charging,Q.audio,Q.buttons,Q.network,Q.liquid,Q.system];
 if(type==="Akıllı Saat")return [Q.power,Q.screen,Q.battery,Q.charging,Q.buttons,Q.network,Q.sensor,Q.liquid,Q.system];
 if(type==="Laptop / Bilgisayar")return [Q.power,Q.screen,Q.battery,Q.charging,Q.camera,Q.audio,Q.buttons,Q.network,Q.liquid,Q.system,Q.data];
 if(type==="Tablet")return [Q.power,Q.screen,Q.rear,Q.battery,Q.charging,Q.camera,Q.biometric,Q.audio,Q.buttons,Q.network,Q.sensor,Q.liquid,Q.system,Q.data];
 return [Q.power,Q.screen,Q.rear,Q.battery,Q.charging,Q.camera,Q.biometric,Q.audio,Q.buttons,Q.network,Q.sensor,Q.liquid,Q.system,Q.data];
}

export function ServiceOfferForm({whatsappNumber,prices,devices,locale}:{whatsappNumber:string;prices:ServicePriceReference[];devices:TradeInCatalogDevice[];locale:Locale}){
 const en=locale==="en";const[step,setStep]=useState(1);const[estimate,setEstimate]=useState<Estimate>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 const[data,setData]=useState({deviceType:"",brand:"",model:"",storage:"",color:"",name:"",phone:"",detail:"",repairHistory:"",note:""});
 const[selectedFaults,setSelectedFaults]=useState<string[]>([]);
 const deviceTypes=useMemo(()=>Array.from(new Set(devices.map(x=>x.device_type))),[devices]);
 const brands=useMemo(()=>Array.from(new Set(devices.filter(x=>x.device_type===data.deviceType).map(x=>x.brand))),[devices,data.deviceType]);
 const models=useMemo(()=>Array.from(new Set(devices.filter(x=>x.device_type===data.deviceType&&x.brand===data.brand).map(x=>x.model))),[devices,data.deviceType,data.brand]);
 const variants=useMemo(()=>devices.filter(x=>x.device_type===data.deviceType&&x.brand===data.brand&&x.model===data.model),[devices,data.deviceType,data.brand,data.model]);
 const storages=useMemo(()=>Array.from(new Set(variants.map(x=>x.storage||"Standart"))),[variants]);
 const colors=useMemo(()=>Array.from(new Set(variants.filter(x=>(x.storage||"Standart")===data.storage).map(x=>x.color||"Standart"))),[variants,data.storage]);
 const selectedQuestions=useMemo(()=>questionsFor(data.deviceType),[data.deviceType]);
 const availableFaults=useMemo(()=>prices.filter(x=>x.device_type===data.deviceType),[prices,data.deviceType]);
 const availableCodes=useMemo(()=>new Set(availableFaults.map(x=>x.fault_code)),[availableFaults]);
 const checklist=useMemo(()=>selectedQuestions.map(q=>({...q,options:q.options.filter(o=>o.code&&availableCodes.has(o.code))})).filter(q=>q.options.length),[selectedQuestions,availableCodes]);
 const faults=useMemo(()=>Array.from(new Set(selectedFaults.filter(code=>availableCodes.has(code)))),[selectedFaults,availableCodes]);
 function resetEstimate(){setEstimate(null);setError("")}
 function change(next:Partial<typeof data>){setData(x=>({...x,...next}));resetEstimate()}
 function toggleFault(code:string){setSelectedFaults(current=>current.includes(code)?current.filter(x=>x!==code):[...current,code]);resetEstimate()}
 function resetFaults(){setSelectedFaults([]);resetEstimate()}
 function money(v:number){return `${Math.round(v).toLocaleString(en?"en-US":"tr-TR")} ₺`}
 async function calculate(){setLoading(true);setError("");try{const r=await fetch("/api/technical-service/estimate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({deviceType:data.deviceType,brand:data.brand,model:data.model,storage:data.storage==="Standart"?"":data.storage,color:data.color==="Standart"?"":data.color,faultCodes:faults})});const j=await r.json();if(!r.ok)throw new Error(j.error||(en?"Price could not be calculated.":"Fiyat hesaplanamadı."));setEstimate(j)}catch(e){setEstimate(null);setError(e instanceof Error?e.message:"Fiyat hesaplanamadı.")}finally{setLoading(false)}}
 async function next(){if(step===1){if(!data.deviceType||!data.brand||!data.model||!data.storage||!data.color)return;setStep(2);return}if(step===2){if(!faults.length)return;await calculate();setStep(3)}}
 function submit(e:FormEvent){e.preventDefault();if(!data.name||!data.phone||!whatsappNumber)return;const labels=faults.map(code=>availableFaults.find(x=>x.fault_code===code)?.fault_label??code);const msg=[en?"Hello Trove Technology, I would like a detailed technical service quote.":"Merhaba Trove Teknoloji, teknik servis için detaylı teklif almak istiyorum.",estimate?`${en?"Estimated service range":"Tahmini servis aralığı"}: ${money(estimate.min)} - ${money(estimate.max)}`:en?"The estimated price will be checked in store.":"Tahmini fiyat mağazada kontrol edilecek.","",`${en?"Device":"Cihaz"}: ${data.deviceType} / ${data.brand} / ${data.model}`,`${en?"Storage":"Depolama"}: ${data.storage}`,`${en?"Color":"Renk"}: ${data.color}`,en?"Selected service needs:":"Seçilen servis ihtiyaçları:",...labels.map(x=>`• ${x}`),data.detail?`${en?"Symptom / complaint":"Belirti / şikayet"}: ${data.detail}`:"",data.repairHistory?`${en?"Previous repair":"Önceki işlem"}: ${data.repairHistory}`:"",data.note?`${en?"Note":"Not"}: ${data.note}`:"","",`${en?"Full Name":"Ad Soyad"}: ${data.name}`,`${en?"Phone":"Telefon"}: ${data.phone}`].filter(Boolean).join("\n");window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(msg)}`,"_blank","noopener,noreferrer")}
 if(!devices.length)return <div className="tradeUnavailable"><strong>{en?"Service pricing variants are being prepared.":"Teknik servis fiyat varyantları hazırlanıyor."}</strong></div>;
 return <form className="tradeForm serviceOfferForm" onSubmit={submit}>
  <div className="tradeProgress"><div className="tradeProgressBar"><span style={{width:`${step/3*100}%`}}/></div><div className="tradeSteps"><button type="button" className={step===1?"active":""} onClick={()=>setStep(1)}>1 <span>{en?"Device":"Cihaz"}</span></button><button type="button" className={step===2?"active":""} onClick={()=>step>1&&setStep(2)}>2 <span>{en?"Service":"Servis"}</span></button><button type="button" className={step===3?"active":""} onClick={()=>step>2&&setStep(3)}>3 <span>{en?"Quote":"Teklif"}</span></button></div></div>
  {step===1?<section className="tradeStep"><div><span className="tradeEyebrow">1 / 3</span><h2>{en?"Exact Device Variant":"Cihaz Varyantı"}</h2><p>{en?"Storage and color are priced independently.":"Depolama ve renk ayrı fiyatlandırılır."}</p></div><div className="tradeGrid">
   <label>{en?"Device type":"Cihaz türü"}<select value={data.deviceType} onChange={e=>{change({deviceType:e.target.value,brand:"",model:"",storage:"",color:""});resetFaults()}}><option value="">{en?"Select":"Seç"}</option>{deviceTypes.map(x=><option key={x}>{x}</option>)}</select></label>
   <label>{en?"Brand":"Marka"}<select disabled={!data.deviceType} value={data.brand} onChange={e=>{change({brand:e.target.value,model:"",storage:"",color:""});resetFaults()}}><option value="">{en?"Select":"Seç"}</option>{brands.map(x=><option key={x}>{x}</option>)}</select></label>
   <label>{en?"Model":"Model"}<select disabled={!data.brand} value={data.model} onChange={e=>{change({model:e.target.value,storage:"",color:""});resetFaults()}}><option value="">{en?"Select":"Seç"}</option>{models.map(x=><option key={x}>{x}</option>)}</select></label>
   <label>{en?"Storage":"Depolama"}<select disabled={!data.model} value={data.storage} onChange={e=>{change({storage:e.target.value,color:""});resetFaults()}}><option value="">{en?"Select":"Seç"}</option>{storages.map(x=><option key={x}>{x}</option>)}</select></label>
   <label>{en?"Color":"Renk"}<select disabled={!data.storage} value={data.color} onChange={e=>{change({color:e.target.value});resetFaults()}}><option value="">{en?"Select":"Seç"}</option>{colors.map(x=><option key={x}>{x}</option>)}</select></label>
  </div><button className="tradePrimary" type="button" disabled={!data.deviceType||!data.brand||!data.model||!data.storage||!data.color} onClick={next}>{en?"Continue →":"Devam Et →"}</button></section>:null}
  {step===2?<section className="tradeStep"><div><span className="tradeEyebrow">2 / 3</span><h2>{en?"What service do you need?":"Hangi işlem için fiyat almak istiyorsun?"}</h2><p>{en?"Select only the service needs that apply. You do not need to answer every item.":"Sadece ihtiyacın olan işlemleri işaretle. Tüm seçenekleri doldurmak zorunda değilsin."}</p></div><div className="serviceQuestionList">{checklist.map(group=><fieldset className="serviceQuestion" key={group.key} style={{border:0,padding:0,margin:0}}><legend style={{fontWeight:700,marginBottom:8}}>{en?group.en:group.tr}</legend><div style={{display:"grid",gap:8}}>{group.options.map(option=><label key={option.code} style={{display:"flex",alignItems:"center",gap:10,cursor:"pointer"}}><input type="checkbox" checked={Boolean(option.code&&faults.includes(option.code))} onChange={()=>option.code&&toggleFault(option.code)}/><span>{en?option.en:option.tr}</span></label>)}</div></fieldset>)}</div><div className="tradeGrid"><label className="wide">{en?"Symptom / complaint (optional)":"Belirti / şikayet (isteğe bağlı)"}<textarea value={data.detail} onChange={e=>change({detail:e.target.value})} placeholder={en?"Add details only if needed":"Gerekliyse kısa bir açıklama ekle"}/></label><label className="wide">{en?"Previous repair (optional)":"Daha önce işlem gördüyse (isteğe bağlı)"}<textarea value={data.repairHistory} onChange={e=>change({repairHistory:e.target.value})}/></label><label className="wide">{en?"Note (optional)":"Ek not (isteğe bağlı)"}<textarea value={data.note} onChange={e=>change({note:e.target.value})}/></label></div><div className="tradeActions"><button type="button" onClick={()=>setStep(1)}>← {en?"Back":"Geri"}</button><button className="tradePrimary" type="button" disabled={!faults.length||loading} onClick={next}>{loading?(en?"Calculating...":"Hesaplanıyor..."):(en?`Get price for ${faults.length} service${faults.length>1?"s":""} →`:`${faults.length} işlem için fiyatı gör →`)}</button></div></section>:null}
  {step===3?<section className="tradeStep"><div><span className="tradeEyebrow">3 / 3</span><h2>{en?"Estimated Service Price":"Tahmini Servis Fiyatı"}</h2></div>{estimate?<div className="tradeEstimate"><div><span>{en?"Estimated range":"Tahmini servis aralığı"}</span><strong>{money(estimate.min)} – {money(estimate.max)}</strong><small>{data.storage} · {data.color} · {faults.length} {en?"service(s)":"işlem"}</small></div></div>:<div className="tradeEstimate tradeEstimateUnavailable"><div><strong>{en?"Inspection required":"Kontrol gerekli"}</strong><small>{error||"Bu varyant için fiyat oluşturulamadı."}</small></div></div>}<div className="tradeGrid"><label>{en?"Full Name":"Ad Soyad"}<input value={data.name} onChange={e=>change({name:e.target.value})}/></label><label>{en?"Phone":"Telefon"}<input inputMode="tel" value={data.phone} onChange={e=>change({phone:e.target.value})}/></label></div><div className="tradeActions"><button type="button" onClick={()=>setStep(2)}>← {en?"Back":"Geri"}</button><button className="tradePrimary" type="submit" disabled={!data.name||!data.phone||!whatsappNumber}>{en?"Get Detailed Quote":"Detaylı Teklif Al"}</button></div></section>:null}
 </form>
}
