"use client";

import { createBrowserClient } from "@supabase/ssr";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { HomepageSlide, HomepageSlideSection, HomepageSlideTransition } from "@/modules/homepage/slides";

const SECTION_LABELS: Record<HomepageSlideSection, string> = { campaigns:"Kampanyalar", phones:"Telefonlar", computers:"Bilgisayarlar", wearables:"Giyilebilir Teknoloji", accessories:"Aksesuarlar & Yedek Parçalar" };
const EFFECT_LABELS: Record<HomepageSlideTransition,string> = { slide:"Yana Kaydır", fade:"Soluk Geçiş", zoom:"Yakınlaştır", flip:"3D Çevir", blur:"Bulanık Geçiş", stack:"Kart Destesi" };
const SECTION_GUIDES: Record<HomepageSlideSection,{size:string;ratio:number;link:string;note:string}> = {
 campaigns:{size:"1680 × 1200 px",ratio:1680/1200,link:"/kategori/telefon",note:"Kampanya alanı artık daha yüksek 7:5 oranında gösterilir. Metin ve önemli ürünü kenarlardan uzak tut."},
 phones:{size:"1600 × 900 px",ratio:16/9,link:"/kategori/telefon",note:"Telefon kampanyası, marka veya ürün grubu görselleri için."},
 computers:{size:"1600 × 900 px",ratio:16/9,link:"/kategori/laptop-bilgisayar",note:"Laptop ve bilgisayar ürün grubu görselleri için."},
 wearables:{size:"1600 × 900 px",ratio:16/9,link:"/kategori/giyilebilir-teknoloji",note:"Saat, kulaklık ve diğer giyilebilir teknoloji görselleri için."},
 accessories:{size:"1600 × 900 px",ratio:16/9,link:"/kategori/aksesuar-yedek-parca",note:"Aksesuar ve yedek parça ürün grubu görselleri için."},
};
const ROUTE_GUIDE=[
 ["/kategori/telefon","Telefonlar"],["/kategori/laptop-bilgisayar","Laptop & Bilgisayar"],["/kategori/giyilebilir-teknoloji","Giyilebilir Teknoloji"],["/kategori/aksesuar-yedek-parca","Aksesuar & Yedek Parça"],["/kategori/teknik-servis","Teknik Servis"],["/takas","Takas"],["/ilan/TEL-001","Belirli ürün — gerçek ürün kodunu yaz"],["https://...","Harici web adresi"]
] as const;
const ALLOWED_TYPES=new Set(["image/jpeg","image/png","image/webp","image/avif"]); const MAX_BYTES=10*1024*1024;
function validLink(value:string){return !value||value.startsWith("/")||value.startsWith("https://")||value.startsWith("http://")}

export function HomepageSliderManager({initialSlides,supabaseUrl,supabasePublishableKey}:{initialSlides:HomepageSlide[];supabaseUrl:string;supabasePublishableKey:string}){
 const router=useRouter(); const [slides,setSlides]=useState(initialSlides); const [section,setSection]=useState<HomepageSlideSection>("campaigns"); const [file,setFile]=useState<File|null>(null); const [fileHint,setFileHint]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null); const [editingId,setEditingId]=useState<string|null>(null);
 const supabase=useMemo(()=>createBrowserClient(supabaseUrl,supabasePublishableKey),[supabaseUrl,supabasePublishableKey]); const guide=SECTION_GUIDES[section];
 async function addSlide(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;if(!file)return setMessage("Önce bir görsel seçin.");if(!ALLOWED_TYPES.has(file.type))return setMessage("JPG, PNG, WEBP veya AVIF yükleyin.");if(file.size>MAX_BYTES)return setMessage("Görsel 10 MB sınırını aşıyor.");const form=new FormData(formElement);const linkUrl=String(form.get("linkUrl")||"").trim();if(!validLink(linkUrl))return setMessage("Bağlantı / ile veya https:// ile başlamalıdır.");const transitionEffect=String(form.get("transitionEffect")||"").trim() as HomepageSlideTransition|"";setBusy(true);setMessage(null);try{const extension=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${section}/${crypto.randomUUID()}.${extension}`;const {error:uploadError}=await supabase.storage.from("homepage-slides").upload(path,file,{contentType:file.type,cacheControl:"3600"});if(uploadError)throw uploadError;const {data:publicData}=supabase.storage.from("homepage-slides").getPublicUrl(path);const payload={section,title:String(form.get("title")||"").trim()||null,subtitle:String(form.get("subtitle")||"").trim()||null,link_url:linkUrl||null,image_url:publicData.publicUrl,sort_order:Number(form.get("sortOrder")||0),transition_effect:transitionEffect||null,is_active:true};const {data,error}=await supabase.from("homepage_slides").insert(payload).select("id,section,title,subtitle,image_url,link_url,sort_order,is_active,transition_effect").single();if(error)throw error;setSlides(c=>[...c,data as HomepageSlide].sort((a,b)=>a.sort_order-b.sort_order));setFile(null);setFileHint(null);formElement.reset();setSection("campaigns");setMessage("Slider görseli eklendi.");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Görsel eklenemedi.")}finally{setBusy(false)}}
 async function removeSlide(slide:HomepageSlide){if(!confirm("Bu slider görseli silinsin mi?"))return;setBusy(true);const {error}=await supabase.from("homepage_slides").delete().eq("id",slide.id);if(error)setMessage(error.message);else{setSlides(c=>c.filter(i=>i.id!==slide.id));setMessage("Slider görseli silindi.");router.refresh()}setBusy(false)}
 async function toggleSlide(slide:HomepageSlide){setBusy(true);const {error}=await supabase.from("homepage_slides").update({is_active:!slide.is_active}).eq("id",slide.id);if(error)setMessage(error.message);else{setSlides(c=>c.map(i=>i.id===slide.id?{...i,is_active:!i.is_active}:i));router.refresh()}setBusy(false)}
 async function updateSlide(event:FormEvent<HTMLFormElement>,slide:HomepageSlide){event.preventDefault();const form=new FormData(event.currentTarget);const link=String(form.get("editLink")||"").trim();if(!validLink(link))return setMessage("Bağlantı / ile veya https:// ile başlamalıdır.");const effect=String(form.get("editEffect")||"").trim() as HomepageSlideTransition|"";const payload={title:String(form.get("editTitle")||"").trim()||null,subtitle:String(form.get("editSubtitle")||"").trim()||null,link_url:link||null,sort_order:Number(form.get("editSort")||0),transition_effect:effect||null};setBusy(true);const {error}=await supabase.from("homepage_slides").update(payload).eq("id",slide.id);if(error)setMessage(error.message);else{setSlides(c=>c.map(i=>i.id===slide.id?{...i,...payload}:i).sort((a,b)=>a.sort_order-b.sort_order));setEditingId(null);setMessage("Slider düzenlendi.");router.refresh()}setBusy(false)}
 function chooseFile(event:ChangeEvent<HTMLInputElement>){const selected=event.target.files?.[0]??null;setFile(selected);setFileHint(null);if(!selected||!ALLOWED_TYPES.has(selected.type))return;const url=URL.createObjectURL(selected);const image=new Image();image.onload=()=>{const difference=Math.abs(image.naturalWidth/image.naturalHeight-guide.ratio)/guide.ratio;setFileHint(difference>.08?`Seçilen görsel ${image.naturalWidth} × ${image.naturalHeight}px. Önerilen ${guide.size}; görsel kırpılabilir.`:`Görsel oranı uygun: ${image.naturalWidth} × ${image.naturalHeight}px.`);URL.revokeObjectURL(url)};image.onerror=()=>URL.revokeObjectURL(url);image.src=url}
 return <div className="adminSliderManager">
  <section className="adminDashboardCard" style={{marginBottom:18}}><h2 style={{marginTop:0}}>Slider ekleme yönergesi</h2><p className="adminLead"><strong>{SECTION_LABELS[section]}</strong> önerilen görsel: <strong>{guide.size}</strong>. WEBP/AVIF tercih et; mümkünse 1 MB altında tut.</p><div className="adminFlowSteps"><span>1. Bölümü seç</span><span>2. Görseli yükle</span><span>3. Efekt ve bağlantıyı seç</span></div><p className="adminLead">{guide.note}</p><div style={{display:"grid",gap:6}}><strong>Site içi bağlantı rehberi — / işaretinden sonrasını aynen yaz:</strong>{ROUTE_GUIDE.map(([route,label])=><div key={route}><code>{route}</code> — {label}</div>)}</div><p className="adminLead" style={{marginBottom:0}}>Kategori adı tahmin ederek yazılmamalı. Yukarıdaki yollar geçerli müşteri sayfalarıdır; yanlış slug 404 verir.</p></section>
  <form className="adminDashboardCard adminListingForm" onSubmit={addSlide}><label className="adminField">Bölüm<select value={section} onChange={e=>{setSection(e.target.value as HomepageSlideSection);setFileHint(null)}}>{Object.entries(SECTION_LABELS).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="adminField">Sıra<input name="sortOrder" type="number" defaultValue="0" /></label><label className="adminField adminFieldWide">Görsel<input accept="image/jpeg,image/png,image/webp,image/avif" type="file" onChange={chooseFile} required/><small>Önerilen: {guide.size}</small>{fileHint?<small>{fileHint}</small>:null}</label><label className="adminField">Başlık<input name="title" placeholder="İsteğe bağlı"/></label><label className="adminField">Kısa metin<input name="subtitle" placeholder="İsteğe bağlı"/></label><label className="adminField">Efekt<select name="transitionEffect" defaultValue=""><option value="">Genel ayarı kullan</option>{Object.entries(EFFECT_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="adminField adminFieldWide">Bağlantı<input name="linkUrl" placeholder={guide.link}/><small>Yukarıdaki rehberdeki yolu kopyalaman önerilir.</small></label><div className="adminFormActions adminFieldWide"><button className="adminButton" disabled={busy} type="submit">{busy?"Yükleniyor...":"Slider görseli ekle"}</button></div>{message?<p className="adminLead adminFieldWide">{message}</p>:null}</form>
  {Object.entries(SECTION_LABELS).map(([key,label])=>{const sectionSlides=slides.filter(s=>s.section===key);return <section className="adminDashboardCard" key={key}><div className="sectionHeading"><h2>{label}</h2><span>{sectionSlides.length} görsel</span></div>{sectionSlides.length?<div className="adminSliderGrid">{sectionSlides.map(slide=><article className="adminSliderCard" key={slide.id}><img src={slide.image_url} alt={slide.title||label}/>{editingId===slide.id?<form onSubmit={e=>updateSlide(e,slide)} style={{display:"grid",gap:8}}><label className="adminField">Başlık<input name="editTitle" defaultValue={slide.title??""}/></label><label className="adminField">Kısa metin<input name="editSubtitle" defaultValue={slide.subtitle??""}/></label><label className="adminField">Bağlantı<input name="editLink" defaultValue={slide.link_url??""}/></label><label className="adminField">Sıra<input name="editSort" type="number" defaultValue={slide.sort_order}/></label><label className="adminField">Efekt<select name="editEffect" defaultValue={slide.transition_effect??""}><option value="">Genel ayarı kullan</option>{Object.entries(EFFECT_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="adminInlineActions"><button className="adminButton" disabled={busy}>Kaydet</button><button className="adminButton adminButtonSecondary" type="button" onClick={()=>setEditingId(null)}>Vazgeç</button></div></form>:<div><strong>{slide.title||"Başlıksız"}</strong><small>Sıra: {slide.sort_order} · {slide.is_active?"Aktif":"Pasif"}{slide.link_url?` · ${slide.link_url}`:" · Bağlantı yok"}</small></div>}<div className="adminInlineActions">{editingId!==slide.id?<button className="adminButton" disabled={busy} onClick={()=>setEditingId(slide.id)} type="button">Düzenle</button>:null}<button className="adminButton adminButtonSecondary" disabled={busy} onClick={()=>toggleSlide(slide)} type="button">{slide.is_active?"Gizle":"Göster"}</button><button className="adminButton adminDangerButton" disabled={busy} onClick={()=>removeSlide(slide)} type="button">Sil</button></div></article>)}</div>:<p className="emptyState">Henüz görsel eklenmedi.</p>}</section>})}
 </div>
}