"use client";

import { createBrowserClient } from "@supabase/ssr";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { HomepageSlide, HomepageSlideSection, HomepageSlideTransition } from "@/modules/homepage/slides";

const SECTION_LABELS: Record<HomepageSlideSection,string>={campaigns:"Kampanyalar",phones:"Telefonlar",computers:"Bilgisayarlar",wearables:"Giyilebilir Teknoloji",accessories:"Aksesuarlar & Yedek Parçalar"};
const EFFECT_LABELS: Record<HomepageSlideTransition,string>={slide:"Yana Kaydır",fade:"Soluk Geçiş",zoom:"Yakınlaştır",flip:"3D Çevir",blur:"Bulanık Geçiş",stack:"Kart Destesi"};
const SECTION_GUIDES: Record<HomepageSlideSection,{size:string;ratio:number;note:string}>={campaigns:{size:"1680 × 1200 px",ratio:1680/1200,note:"Kampanya alanı 7:5 oranında gösterilir."},phones:{size:"1600 × 900 px",ratio:16/9,note:"Telefon ürün grubu görselleri için."},computers:{size:"1600 × 900 px",ratio:16/9,note:"Laptop ve bilgisayar görselleri için."},wearables:{size:"1600 × 900 px",ratio:16/9,note:"Saat, kulaklık ve giyilebilir teknoloji için."},accessories:{size:"1600 × 900 px",ratio:16/9,note:"Aksesuar ve yedek parça görselleri için."}};
const PAGE_LINKS=[["/","Ana sayfa"],["/kategori/telefon","Telefonlar"],["/kategori/laptop-bilgisayar","Laptop & Bilgisayar"],["/kategori/giyilebilir-teknoloji","Giyilebilir Teknoloji"],["/kategori/aksesuar-yedek-parca","Aksesuar & Yedek Parça"],["/kategori/bilgisayar-parcalari","Bilgisayar Parçaları"],["/kategori/teknik-servis","Teknik Servis"],["/takas","Takas"],["/hakkimizda","Hakkımızda"],["/iletisim","İletişim"]] as const;
const ALLOWED_TYPES=new Set(["image/jpeg","image/png","image/webp","image/avif"]);const MAX_BYTES=10*1024*1024;
type SliderProduct={productCode:string;title:string;brand:string;model:string};
function LinkPicker({name,products,defaultValue=""}:{name:string;products:SliderProduct[];defaultValue?:string}){const known=defaultValue===""||PAGE_LINKS.some(([href])=>href===defaultValue)||products.some(product=>`/ilan/${product.productCode}`===defaultValue);return <select name={name} defaultValue={defaultValue}>{!known&&defaultValue?<option value={defaultValue}>Mevcut: {defaultValue}</option>:null}<option value="">Bağlantı yok</option><optgroup label="Site sayfaları">{PAGE_LINKS.map(([href,label])=><option value={href} key={href}>{label}</option>)}</optgroup><optgroup label="Yayındaki ürünler">{products.map(product=><option value={`/ilan/${product.productCode}`} key={product.productCode}>{product.title} · {product.productCode}</option>)}</optgroup></select>}

export function HomepageSliderManager({initialSlides,products,supabaseUrl,supabasePublishableKey}:{initialSlides:HomepageSlide[];products:SliderProduct[];supabaseUrl:string;supabasePublishableKey:string}){
 const router=useRouter();const[slides,setSlides]=useState(initialSlides);const[section,setSection]=useState<HomepageSlideSection>("campaigns");const[file,setFile]=useState<File|null>(null);const[fileHint,setFileHint]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string|null>(null);const[editingId,setEditingId]=useState<string|null>(null);const supabase=useMemo(()=>createBrowserClient(supabaseUrl,supabasePublishableKey),[supabaseUrl,supabasePublishableKey]);const guide=SECTION_GUIDES[section];
 async function addSlide(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;if(!file)return setMessage("Önce bir görsel seçin.");if(!ALLOWED_TYPES.has(file.type))return setMessage("JPG, PNG, WEBP veya AVIF yükleyin.");if(file.size>MAX_BYTES)return setMessage("Görsel 10 MB sınırını aşıyor.");const form=new FormData(formElement);setBusy(true);setMessage(null);try{const extension=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${section}/${crypto.randomUUID()}.${extension}`;const{error:uploadError}=await supabase.storage.from("homepage-slides").upload(path,file,{contentType:file.type,cacheControl:"3600"});if(uploadError)throw uploadError;const{data:publicData}=supabase.storage.from("homepage-slides").getPublicUrl(path);const transitionEffect=String(form.get("transitionEffect")||"").trim() as HomepageSlideTransition|"";const payload={section,title:String(form.get("title")||"").trim()||null,subtitle:String(form.get("subtitle")||"").trim()||null,link_url:String(form.get("linkUrl")||"").trim()||null,image_url:publicData.publicUrl,sort_order:Number(form.get("sortOrder")||0),transition_effect:transitionEffect||null,is_active:true};const{data,error}=await supabase.from("homepage_slides").insert(payload).select("id,section,title,subtitle,image_url,link_url,sort_order,is_active,transition_effect").single();if(error)throw error;setSlides(c=>[...c,data as HomepageSlide].sort((a,b)=>a.sort_order-b.sort_order));setFile(null);setFileHint(null);formElement.reset();setMessage("Slider görseli eklendi.");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Görsel eklenemedi.")}finally{setBusy(false)}}
 async function removeSlide(slide:HomepageSlide){if(!confirm("Bu slider görseli silinsin mi?"))return;setBusy(true);const{error}=await supabase.from("homepage_slides").delete().eq("id",slide.id);if(error)setMessage(error.message);else{setSlides(c=>c.filter(i=>i.id!==slide.id));router.refresh()}setBusy(false)}
 async function toggleSlide(slide:HomepageSlide){setBusy(true);const{error}=await supabase.from("homepage_slides").update({is_active:!slide.is_active}).eq("id",slide.id);if(error)setMessage(error.message);else{setSlides(c=>c.map(i=>i.id===slide.id?{...i,is_active:!i.is_active}:i));router.refresh()}setBusy(false)}
 async function updateSlide(event:FormEvent<HTMLFormElement>,slide:HomepageSlide){event.preventDefault();const form=new FormData(event.currentTarget);const effect=String(form.get("editEffect")||"").trim() as HomepageSlideTransition|"";const payload={title:String(form.get("editTitle")||"").trim()||null,subtitle:String(form.get("editSubtitle")||"").trim()||null,link_url:String(form.get("editLink")||"").trim()||null,sort_order:Number(form.get("editSort")||0),transition_effect:effect||null};setBusy(true);const{error}=await supabase.from("homepage_slides").update(payload).eq("id",slide.id);if(error)setMessage(error.message);else{setSlides(c=>c.map(i=>i.id===slide.id?{...i,...payload}:i).sort((a,b)=>a.sort_order-b.sort_order));setEditingId(null);router.refresh()}setBusy(false)}
 function chooseFile(event:ChangeEvent<HTMLInputElement>){const selected=event.target.files?.[0]??null;setFile(selected);setFileHint(null);if(!selected||!ALLOWED_TYPES.has(selected.type))return;const url=URL.createObjectURL(selected);const image=new Image();image.onload=()=>{const difference=Math.abs(image.naturalWidth/image.naturalHeight-guide.ratio)/guide.ratio;setFileHint(difference>.08?`${image.naturalWidth} × ${image.naturalHeight}px; önerilen ${guide.size}. Kırpılabilir.`:`Görsel oranı uygun: ${image.naturalWidth} × ${image.naturalHeight}px.`);URL.revokeObjectURL(url)};image.onerror=()=>URL.revokeObjectURL(url);image.src=url}
 const activeCount=slides.filter(s=>s.is_active).length;
 return <div className="adminSliderManager">
  <div className="adminOverviewGrid adminCompactOverview"><div><span>Toplam</span><strong>{slides.length}</strong></div><div><span>Aktif</span><strong>{activeCount}</strong></div><div><span>Gizli</span><strong>{slides.length-activeCount}</strong></div></div>
  {message?<p className="adminStatus">{message}</p>:null}
  <details className="adminCompactPanel"><summary>+ Yeni slider görseli</summary><div className="adminCompactHint"><strong>{SECTION_LABELS[section]} · {guide.size}</strong><span>{guide.note} WEBP/AVIF ve mümkünse 1 MB altı önerilir.</span></div><form className="adminListingForm adminCompactForm" onSubmit={addSlide}><label className="adminField">Bölüm<select value={section} onChange={e=>{setSection(e.target.value as HomepageSlideSection);setFileHint(null)}}>{Object.entries(SECTION_LABELS).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="adminField">Sıra<input name="sortOrder" type="number" defaultValue="0"/></label><label className="adminField adminFieldWide">Görsel<input accept="image/jpeg,image/png,image/webp,image/avif" type="file" onChange={chooseFile} required/>{fileHint?<small>{fileHint}</small>:null}</label><label className="adminField">Başlık<input name="title" placeholder="İsteğe bağlı"/></label><label className="adminField">Kısa metin<input name="subtitle" placeholder="İsteğe bağlı"/></label><label className="adminField">Efekt<select name="transitionEffect" defaultValue=""><option value="">Genel ayarı kullan</option>{Object.entries(EFFECT_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="adminField adminFieldWide">Bağlantı<LinkPicker name="linkUrl" products={products}/></label><div className="adminFormActions adminFieldWide"><button className="adminButton" disabled={busy}>{busy?"Yükleniyor...":"Slider ekle"}</button></div></form></details>
  <div className="adminToolRow">{Object.entries(SECTION_LABELS).map(([key,label])=>{const sectionSlides=slides.filter(s=>s.section===key);return <details className="adminCompactPanel" key={key} open={key==="campaigns"}><summary>{label} ({sectionSlides.length})</summary>{sectionSlides.length?<div className="adminSliderCompactList">{sectionSlides.map(slide=><article className="adminSliderCompactRow" key={slide.id}><img src={slide.image_url} alt={slide.title||label}/><div className="adminSliderCompactMain">{editingId===slide.id?<form onSubmit={e=>updateSlide(e,slide)} className="adminCompactForm"><label className="adminField">Başlık<input name="editTitle" defaultValue={slide.title??""}/></label><label className="adminField">Kısa metin<input name="editSubtitle" defaultValue={slide.subtitle??""}/></label><label className="adminField">Bağlantı<LinkPicker name="editLink" products={products} defaultValue={slide.link_url??""}/></label><label className="adminField">Sıra<input name="editSort" type="number" defaultValue={slide.sort_order}/></label><label className="adminField">Efekt<select name="editEffect" defaultValue={slide.transition_effect??""}><option value="">Genel ayarı kullan</option>{Object.entries(EFFECT_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="adminInlineActions"><button className="adminButton" disabled={busy}>Kaydet</button><button className="adminButton adminButtonSecondary" type="button" onClick={()=>setEditingId(null)}>Vazgeç</button></div></form>:<><strong>{slide.title||"Başlıksız"}</strong><small>Sıra {slide.sort_order} · {slide.is_active?"Aktif":"Gizli"} · {slide.link_url||"Bağlantı yok"}</small></>}</div><div className="adminInlineActions">{editingId!==slide.id?<button className="adminButton adminButtonSecondary" disabled={busy} onClick={()=>setEditingId(slide.id)} type="button">Düzenle</button>:null}<button className="adminButton adminButtonSecondary" disabled={busy} onClick={()=>toggleSlide(slide)} type="button">{slide.is_active?"Gizle":"Göster"}</button><button className="adminButton adminDangerButton" disabled={busy} onClick={()=>removeSlide(slide)} type="button">Sil</button></div></article>)}</div>:<p className="emptyState">Bu bölüm boş. Ana sayfada da gösterilmez.</p>}</details>})}</div>
 </div>
}
