"use server";

import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server-client";
import { isAdminEmail } from "@/modules/auth/admin-access";

const SERVICE_TYPES = new Set(["phone", "computer", "laptop", "playstation"]);
const SERVICE_STATUSES = new Set(["in_progress", "completed", "notify_customer"]);

function requiredText(formData: FormData, key: string, label: string) { const value = String(formData.get(key) ?? "").trim(); if (!value) throw new Error(`${label} zorunludur.`); return value; }
function optionalText(formData: FormData, key: string) { const value = String(formData.get(key) ?? "").trim(); return value || null; }
function requiredMoney(formData: FormData, key: string, label: string) { const raw = String(formData.get(key) ?? "").trim().replace(",", "."); if (!raw) throw new Error(`${label} zorunludur.`); const value = Number(raw); if (!Number.isFinite(value) || value < 0) throw new Error(`${label} geçerli bir tutar olmalıdır.`); return value; }
function requiredServiceType(formData: FormData) { const value = String(formData.get("serviceType") ?? "").trim(); if (!SERVICE_TYPES.has(value)) throw new Error("Teknik servis türü seçilmelidir."); return value; }
function requiredServiceStatus(formData: FormData) { const value = String(formData.get("serviceStatus") ?? "in_progress").trim(); if (!SERVICE_STATUSES.has(value)) throw new Error("Servis durumu geçersiz."); return value; }
function requiredId(formData: FormData) { const value = String(formData.get("recordId") ?? "").trim(); if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) throw new Error("Servis kaydı bulunamadı."); return value; }

async function getAdminContext() { const supabase = await createSupabaseServerClient(); const { data: userData, error: userError } = await supabase.auth.getUser(); if (userError || !userData.user || !isAdminEmail(userData.user.email)) redirect("/admin/login"); return { supabase, user: userData.user }; }

function readEditablePayload(formData: FormData) { return { service_status: requiredServiceStatus(formData), first_name: requiredText(formData, "firstName", "Ad"), last_name: requiredText(formData, "lastName", "Soyad"), phone: requiredText(formData, "phone", "Telefon numarası"), complaint: requiredText(formData, "complaint", "Müşteri şikayeti"), fault_description: optionalText(formData, "faultDescription"), damage_cost: requiredMoney(formData, "damageCost", "Hasar / maliyet"), labor_cost: requiredMoney(formData, "laborCost", "İşçilik"), amount_paid: requiredMoney(formData, "amountPaid", "Müşterinin verdiği tutar") }; }
function readCreatePayload(formData: FormData) { return { service_type: requiredServiceType(formData), ...readEditablePayload(formData) }; }

export async function createTechnicalServiceRecord(formData: FormData) { const { supabase, user } = await getAdminContext(); let payload; try { payload = { ...readCreatePayload(formData), created_by: user.id }; } catch (error) { redirect(`/admin/technical-service?error=${encodeURIComponent(error instanceof Error ? error.message : "Servis kaydı oluşturulamadı.")}`); } const { data, error } = await supabase.from("technical_service_records").insert(payload).select("service_code").single(); if (error || !data) redirect(`/admin/technical-service?error=${encodeURIComponent("Servis kaydı veritabanına kaydedilemedi.")}`); redirect(`/admin/technical-service?created=${encodeURIComponent(data.service_code)}`); }
export async function updateTechnicalServiceRecord(formData: FormData) { const { supabase } = await getAdminContext(); let recordId: string; let payload; try { recordId = requiredId(formData); payload = { ...readEditablePayload(formData), updated_at: new Date().toISOString() }; } catch (error) { redirect(`/admin/technical-service?error=${encodeURIComponent(error instanceof Error ? error.message : "Servis kaydı güncellenemedi.")}`); } const { error } = await supabase.from("technical_service_records").update(payload).eq("id", recordId).is("archived_at", null); if (error) redirect(`/admin/technical-service?error=${encodeURIComponent("Servis kaydı güncellenemedi.")}`); redirect("/admin/technical-service?updated=1"); }
export async function updateTechnicalServiceStatus(formData: FormData) { const { supabase } = await getAdminContext(); let recordId: string; let serviceStatus: string; try { recordId = requiredId(formData); serviceStatus = requiredServiceStatus(formData); } catch (error) { redirect(`/admin/technical-service/scanner?error=${encodeURIComponent(error instanceof Error ? error.message : "Durum güncellenemedi.")}`); } const returnCode = String(formData.get("returnCode") ?? "").trim(); const { error } = await supabase.from("technical_service_records").update({ service_status: serviceStatus, updated_at: new Date().toISOString() }).eq("id", recordId).is("archived_at", null); if (error) redirect(`/admin/technical-service/scanner?code=${encodeURIComponent(returnCode)}&error=${encodeURIComponent("Durum güncellenemedi.")}`); redirect(`/admin/technical-service/scanner?code=${encodeURIComponent(returnCode)}&updated=1`); }
export async function updateTechnicalServiceStatusFromList(formData: FormData) { const { supabase } = await getAdminContext(); let recordId: string; let serviceStatus: string; try { recordId = requiredId(formData); serviceStatus = requiredServiceStatus(formData); } catch (error) { redirect(`/admin/technical-service?error=${encodeURIComponent(error instanceof Error ? error.message : "Durum güncellenemedi.")}#servis-kayitlari`); } const { error } = await supabase.from("technical_service_records").update({ service_status: serviceStatus, updated_at: new Date().toISOString() }).eq("id", recordId).is("archived_at", null); if (error) redirect(`/admin/technical-service?error=${encodeURIComponent("Durum güncellenemedi.")}#servis-kayitlari`); redirect("/admin/technical-service?updated=1#servis-kayitlari"); }
export async function archiveTechnicalServiceRecord(formData: FormData) { const { supabase, user } = await getAdminContext(); let recordId: string; try { recordId = requiredId(formData); } catch (error) { redirect(`/admin/technical-service?error=${encodeURIComponent(error instanceof Error ? error.message : "Servis kaydı arşivlenemedi.")}`); } const now = new Date().toISOString(); const { error } = await supabase.from("technical_service_records").update({ archived_at: now, archived_by: user.id, updated_at: now }).eq("id", recordId).is("archived_at", null); if (error) redirect(`/admin/technical-service?error=${encodeURIComponent("Servis kaydı arşivlenemedi.")}`); redirect("/admin/technical-service?archived=1"); }
export async function restoreTechnicalServiceRecord(formData: FormData) { const { supabase } = await getAdminContext(); let recordId: string; try { recordId = requiredId(formData); } catch (error) { redirect(`/admin/technical-service?error=${encodeURIComponent(error instanceof Error ? error.message : "Servis kaydı geri yüklenemedi.")}`); } const { error } = await supabase.from("technical_service_records").update({ archived_at: null, archived_by: null, updated_at: new Date().toISOString() }).eq("id", recordId).not("archived_at", "is", null); if (error) redirect(`/admin/technical-service?error=${encodeURIComponent("Servis kaydı geri yüklenemedi.")}`); redirect("/admin/technical-service?restored=1"); }
