"use client";

import { FormEvent, useMemo, useState } from "react";
import type { TradeInCatalogDevice } from "../../modules/trade-in/catalog";

const COSMETIC=["Kusursuz","Çok iyi","İyi","Orta","Yıpranmış"];
type Estimate={estimate:number;min:number;max:number;confidence:string;marketPrice:number;marginAmount:number;deductions:number}|null;

export function TradeInForm({whatsappNumber,devices}:{whatsappNumber:string;devices:TradeInCatalogDevice[]}){
 const [step,setStep]=useState(1);const [estimating,setEstimating]=useState(false);const [estimate,setEstimate]=useState<Estimate>(null);const [estimateError,setEstimateError]=useState("");
 const [data,setData]=useState({deviceType:"",brand:"",model:"",storage:"",deviceId:"",region:"",cosmetic:"",screen:"",body:"",battery:"",working:"",repairs:"",accessories:"",notes:"",name:"",phone:"",city:""});
 const progress=useMemo(()=>`${Math.round(step/3*100)}%`,[step]);const deviceTypes=useMemo(()=>Array.from(new Set(devices.map(x=>x.device_type))),[devices]);const brands=useMemo(()=>Array.from(new Set(devices.filter(x=>x.device_type===data.deviceType).map(x=>x.brand))),[devices,data.deviceType]);const models=useMemo(()=>Array.from(new Set(devices.filter(x=>x.device_type===data.deviceType&&x.brand===data.brand).map(x=>x.model))),[devices,data.deviceType,data.brand]);const variants=useMemo(()=>devices.filter(x=>x.device_type===data.deviceType&&x.brand===data.brand&&x.model===data.model),[devices,data.deviceType,data.brand,data.model]);const storages=useMemo(()=>Array.from(new Set(variants.map(x=>x.storage||"Standart"))),[variants]);
 function set(key:keyof typeof data,value:string){setData(current=>({...current,[key]:value}));if(["region","cosmetic","screen","body","battery","working","repairs","accessories"].includes(key))setEstimate(null)}
 function selectType(value:string){setData(current=>({...current,deviceType:value,brand:"",model:"",storage:"",deviceId:""}));setEstimate(null)}function selectBrand(value:string){setData(current=>({...current,brand:value,model:"",storage:"",deviceId:""}));setEstimate(null)}function selectModel(value:string){const nextVariants=devices.filter(x=>x.device_type===data.deviceType&&x.brand===data.brand&&x.model===value);const only=nextVariants.length===1?nextVariants[0]:null;setData(current=>({...current,model:value,storage:only?(only.storage||"Standart"):"",deviceId:only?.id??""}));setEstimate(null)}function selectStorage(value:string){const match=variants.find(x=>(x.storage||"Standart")===value);setData(current=>({...current,storage:value,deviceId:match?.id??""}));setEstimate(null)}
 async function calculateEstimate(){setEstimating(true);setEstimateError("");try{const response=await fetch("/api/trade-in/estimate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({deviceId:data.deviceId,region:data.region,cosmetic:data.cosmetic,working:data.working,screen:data.screen,body:data.body,battery:data.battery,repairs:data.repairs,accessories:data.accessories})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Tahmin oluşturulamadı.");setEstimate(result)}catch(error){setEstimate(null);setEstimateError(error instanceof Error?error.message:"Tahmin oluşturulamadı.")}finally{setEstimating(false)}}
 async function next(){if(step===1&&(!data.deviceType||!data.brand||!data.model||!data.deviceId||!data.region))return;if(step===2){if(!data.cosmetic||!data.working||!data.screen||!data.body)return;await calculateEstimate();setStep(3);return}setStep(current=>Math.min(3,current+1))}
 function money(value:number){return `${Math.round(value).toLocaleString("tr-TR")} ₺`}
 function submit(event:FormEvent){event.preventDefault();if(!data.name||!data.phone||!whatsappNumber)return;const message=["Merhaba Trove Teknoloji, detaylı takas teklifi almak istiyorum.",estimate?`Sistem tahmini: ${money(estimate.estimate)} (${money(estimate.min)} - ${money(estimate.max)})`:"Sistem tahmini oluşturulamadı.",estimate?`Güncel referans: ${money(estimate.marketPrice)} · masraf kesintileri: ${money(estimate.deductions)}`:"","","CİHAZ BİLGİLERİ",`Tür: ${data.deviceType}`,`Marka: ${data.brand}`,`Model: ${data.model}`,data.storage?`Hafıza: ${data.storage}`:"",data.region?`Cihaz/Kayıt: ${data.region}`:"","","KOZMETİK & DURUM",`Kozmetik: ${data.cosmetic}`,data.screen?`Ekran: ${data.screen}`:"",data.body?`Kasa: ${data.body}`:"",data.battery?`Pil sağlığı: ${data.battery}`:"",`Çalışma durumu: ${data.working}`,data.repairs?`Onarım/değişen: ${data.repairs}`:"",data.accessories?`Kutu/aksesuar: ${data.accessories}`:"",data.notes?`Not: ${data.notes}`:"","","SATICI BİLGİLERİ",`Ad Soyad: ${data.name}`,`Telefon: ${data.phone}`,data.city?`Şehir: ${data.city}`:"","Tahmini fiyat fiziksel kontrolden sonra kesinleşir."].filter(Boolean).join("\n");window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")}
 if(!devices.length)return <div className="tradeUnavailable"><strong>Şu anda otomatik takas listesi hazırlanıyor.</strong><span>Admin panelinden satın alınabilir cihazlar eklendiğinde form aktif olacak.</span></div>;
 return <form className="tradeForm" onSubmit={submit}><div className="tradeProgress"><div className="tradeProgressBar"><span style={{width:progress}}/></div><div className="tradeSteps"><button className={step===1?"active":""} type="button" onClick={()=>setStep(1)}>1 <span>Cihaz</span></button><button className={step===2?"active":""} type="button" onClick={()=>step>1&&setStep(2)}>2 <span>Durum</span></button><button className={step===3?"active":""} type="button" onClick={()=>step>2&&setStep(3)}>3 <span>Teklif</span></button></div></div>
 {step===1?<section className="tradeStep"><div><span className="tradeEyebrow">1 / 3</span><h2>Cihaz Bilgileri</h2><p>TR ve yurt dışı fiyatları ayrı referanslardan hesaplanır.</p></div><div className="tradeGrid"><label>Cihaz türü<select value={data.deviceType} onChange={e=>selectType(e.target.value)}><option value="">Seç</option>{deviceTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>Marka<select disabled={!data.deviceType} value={data.brand} onChange={e=>selectBrand(e.target.value)}><option value="">Seç</option>{brands.map(x=><option key={x}>{x}</option>)}</select></label><label>Model<select disabled={!data.brand} value={data.model} onChange={e=>selectModel(e.target.value)}><option value="">Seç</option>{models.map(x=><option key={x}>{x}</option>)}</select></label><label>Hafıza / Varyant<select disabled={!data.model} value={data.storage} onChange={e=>selectStorage(e.target.value)}><option value="">Seç</option>{storages.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Cihaz / kayıt durumu<select value={data.region} onChange={e=>set("region",e.target.value)}><option value="">Seç</option><option value="tr">TR cihazı</option><option value="passport">Yurt dışı - kayıtlı</option><option value="international">Yurt dışı - kayıtsız</option></select></label></div><button className="tradePrimary" type="button" disabled={!data.deviceId||!data.region} onClick={next}>Devam Et →</button></section>:null}
 {step===2?<section className="tradeStep"><div><span className="tradeEyebrow">2 / 3</span><h2>Cihaz Kozmetiği ve Durumu</h2><p>Hasarlar yüzdeyle değil, admin panelindeki gerçek masraf referanslarıyla düşülür.</p></div><div className="tradeGrid"><label>Kozmetik durum<select value={data.cosmetic} onChange={e=>set("cosmetic",e.target.value)}><option value="">Seç</option>{COSMETIC.map(x=><option key={x}>{x}</option>)}</select></label><label>Çalışma durumu<select value={data.working} onChange={e=>set("working",e.target.value)}><option value="">Seç</option><option>Tam çalışıyor</option><option>Kısmi arızalı</option><option>Çalışmıyor</option></select></label><label>Ekran durumu<select value={data.screen} onChange={e=>set("screen",e.target.value)}><option value="">Seç</option><option>Çiziksiz</option><option>Hafif çizik</option><option>Derin çizik</option><option>Çatlak / kırık</option></select></label><label>Kasa durumu<select value={data.body} onChange={e=>set("body",e.target.value)}><option value="">Seç</option><option>Temiz</option><option>Hafif izler</option><option>Çizik / ezik</option><option>Hasarlı</option></select></label><label>Pil sağlığı<input value={data.battery} onChange={e=>set("battery",e.target.value)} placeholder="%87 veya bilinmiyor"/></label><label>Onarım / değişen<input value={data.repairs} onChange={e=>set("repairs",e.target.value)} placeholder="Yok, ekran değişti..."/></label><label className="wide">Kutu ve aksesuar<input value={data.accessories} onChange={e=>set("accessories",e.target.value)} placeholder="Kutu, şarj kablosu..."/></label><label className="wide">Ek not<textarea value={data.notes} onChange={e=>set("notes",e.target.value)} placeholder="Teklif için bilinmesi gereken diğer detaylar"/></label></div><div className="tradeActions"><button type="button" onClick={()=>setStep(1)}>← Geri</button><button className="tradePrimary" type="button" disabled={estimating||!data.cosmetic||!data.working||!data.screen||!data.body} onClick={next}>{estimating?"Hesaplanıyor...":"Tahmini Fiyatı Hesapla →"}</button></div></section>:null}
 {step===3?<section className="tradeStep"><div><span className="tradeEyebrow">3 / 3</span><h2>Teklif & Satıcı Bilgileri</h2><p>Tahmin seçilen bölge fiyatından Trove kârı ve gerçek masraflar düşülerek hesaplanır.</p></div>{estimate?<div className="tradeEstimate"><div><span>Tahmini ortalama fiyat</span><strong>{money(estimate.estimate)}</strong><small>Tahmini aralık: {money(estimate.min)} – {money(estimate.max)} · Güven: {estimate.confidence}</small><div className="tradeEstimateBreakdown"><span>Güncel referans: {money(estimate.marketPrice)}</span><span>Trove kâr payı: {money(estimate.marginAmount)}</span><span>Masraf kesintileri: {money(estimate.deductions)}</span></div></div><button className="tradePrimary" type="submit" disabled={!data.name||!data.phone||!whatsappNumber}>Detaylı Teklif Al</button></div>:<div className="tradeEstimate tradeEstimateUnavailable"><div><span>Otomatik tahmin</span><strong>Detaylı kontrol gerekli</strong><small>{estimateError||"Bu cihaz için fiyat oluşturulamadı."}</small></div></div>}<div className="tradeGrid"><label>Ad Soyad<input value={data.name} onChange={e=>set("name",e.target.value)} placeholder="Ad Soyad"/></label><label>Telefon<input inputMode="tel" value={data.phone} onChange={e=>set("phone",e.target.value)} placeholder="05xx xxx xx xx"/></label><label className="wide">Şehir / İlçe<input value={data.city} onChange={e=>set("city",e.target.value)} placeholder="İstanbul / Kadıköy"/></label></div><p className="tradeDisclaimer">Bu rakam ön tahmindir; kesin alış fiyatı cihaz mağazada fiziksel olarak kontrol edildikten sonra belirlenir.</p><div className="tradeActions"><button type="button" onClick={()=>setStep(2)}>← Geri</button>{!estimate?<button className="tradePrimary" type="submit" disabled={!data.name||!data.phone||!whatsappNumber}>Detaylı Teklif Al</button>:null}</div></section>:null}</form>
}
