"use client";

import { FormEvent, useMemo, useState } from "react";

const DEVICE_TYPES=["Telefon","Laptop / Bilgisayar","Tablet","Akıllı Saat","Kulaklık","Diğer"];
const COSMETIC=["Kusursuz","Çok iyi","İyi","Orta","Yıpranmış"];

export function TradeInForm({whatsappNumber}:{whatsappNumber:string}){
 const [step,setStep]=useState(1);
 const [data,setData]=useState({deviceType:"",brand:"",model:"",storage:"",region:"",cosmetic:"",screen:"",body:"",battery:"",working:"",repairs:"",accessories:"",notes:"",name:"",phone:"",city:""});
 const progress=useMemo(()=>`${Math.round(step/3*100)}%`,[step]);
 function set(key:keyof typeof data,value:string){setData(current=>({...current,[key]:value}))}
 function next(){if(step===1&&(!data.deviceType||!data.brand||!data.model))return;if(step===2&&(!data.cosmetic||!data.working))return;setStep(current=>Math.min(3,current+1))}
 function submit(event:FormEvent){event.preventDefault();if(!data.name||!data.phone||!whatsappNumber)return;const message=["Merhaba Trove Teknoloji, takas teklifi almak istiyorum.","","CİHAZ BİLGİLERİ",`Tür: ${data.deviceType}`,`Marka: ${data.brand}`,`Model: ${data.model}`,data.storage?`Hafıza: ${data.storage}`:"",data.region?`Cihaz/Kayıt: ${data.region}`:"","","KOZMETİK & DURUM",`Kozmetik: ${data.cosmetic}`,data.screen?`Ekran: ${data.screen}`:"",data.body?`Kasa: ${data.body}`:"",data.battery?`Pil sağlığı: ${data.battery}`:"",`Çalışma durumu: ${data.working}`,data.repairs?`Onarım/değişen: ${data.repairs}`:"",data.accessories?`Kutu/aksesuar: ${data.accessories}`:"",data.notes?`Not: ${data.notes}`:"","","SATICI BİLGİLERİ",`Ad Soyad: ${data.name}`,`Telefon: ${data.phone}`,data.city?`Şehir: ${data.city}`:""].filter(Boolean).join("\n");window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")}
 return <form className="tradeForm" onSubmit={submit}>
  <div className="tradeProgress"><div className="tradeProgressBar"><span style={{width:progress}}/></div><div className="tradeSteps"><button className={step===1?"active":""} type="button" onClick={()=>setStep(1)}>1 <span>Cihaz</span></button><button className={step===2?"active":""} type="button" onClick={()=>step>1&&setStep(2)}>2 <span>Durum</span></button><button className={step===3?"active":""} type="button" onClick={()=>step>2&&setStep(3)}>3 <span>Satıcı</span></button></div></div>
  {step===1?<section className="tradeStep"><div><span className="tradeEyebrow">1 / 3</span><h2>Cihaz Bilgileri</h2><p>Takasa vereceğin cihazı tanımla.</p></div><div className="tradeGrid"><label>Cihaz türü<select value={data.deviceType} onChange={e=>set("deviceType",e.target.value)}><option value="">Seç</option>{DEVICE_TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label>Marka<input value={data.brand} onChange={e=>set("brand",e.target.value)} placeholder="Apple, Samsung..."/></label><label>Model<input value={data.model} onChange={e=>set("model",e.target.value)} placeholder="iPhone 15 Pro..."/></label><label>Hafıza<input value={data.storage} onChange={e=>set("storage",e.target.value)} placeholder="128 GB"/></label><label className="wide">Cihaz / kayıt durumu<select value={data.region} onChange={e=>set("region",e.target.value)}><option value="">Seç</option><option>TR cihazı</option><option>Yurt dışı - kayıtlı</option><option>Yurt dışı - kayıtsız</option></select></label></div><button className="tradePrimary" type="button" onClick={next}>Devam Et →</button></section>:null}
  {step===2?<section className="tradeStep"><div><span className="tradeEyebrow">2 / 3</span><h2>Cihaz Kozmetiği ve Durumu</h2><p>Cihazı mümkün olduğunca doğru tarif et.</p></div><div className="tradeGrid"><label>Kozmetik durum<select value={data.cosmetic} onChange={e=>set("cosmetic",e.target.value)}><option value="">Seç</option>{COSMETIC.map(x=><option key={x}>{x}</option>)}</select></label><label>Çalışma durumu<select value={data.working} onChange={e=>set("working",e.target.value)}><option value="">Seç</option><option>Tam çalışıyor</option><option>Kısmi arızalı</option><option>Çalışmıyor</option></select></label><label>Ekran durumu<select value={data.screen} onChange={e=>set("screen",e.target.value)}><option value="">Seç</option><option>Çiziksiz</option><option>Hafif çizik</option><option>Derin çizik</option><option>Çatlak / kırık</option></select></label><label>Kasa durumu<select value={data.body} onChange={e=>set("body",e.target.value)}><option value="">Seç</option><option>Temiz</option><option>Hafif izler</option><option>Çizik / ezik</option><option>Hasarlı</option></select></label><label>Pil sağlığı<input value={data.battery} onChange={e=>set("battery",e.target.value)} placeholder="%87 veya bilinmiyor"/></label><label>Onarım / değişen<input value={data.repairs} onChange={e=>set("repairs",e.target.value)} placeholder="Yok, ekran değişti..."/></label><label className="wide">Kutu ve aksesuar<input value={data.accessories} onChange={e=>set("accessories",e.target.value)} placeholder="Kutu, şarj kablosu..."/></label><label className="wide">Ek not<textarea value={data.notes} onChange={e=>set("notes",e.target.value)} placeholder="Teklif için bilinmesi gereken diğer detaylar"/></label></div><div className="tradeActions"><button type="button" onClick={()=>setStep(1)}>← Geri</button><button className="tradePrimary" type="button" onClick={next}>Devam Et →</button></div></section>:null}
  {step===3?<section className="tradeStep"><div><span className="tradeEyebrow">3 / 3</span><h2>Satıcı Bilgileri</h2><p>Teklif görüşmesi için iletişim bilgilerini tamamla.</p></div><div className="tradeGrid"><label>Ad Soyad<input value={data.name} onChange={e=>set("name",e.target.value)} placeholder="Ad Soyad"/></label><label>Telefon<input inputMode="tel" value={data.phone} onChange={e=>set("phone",e.target.value)} placeholder="05xx xxx xx xx"/></label><label className="wide">Şehir / İlçe<input value={data.city} onChange={e=>set("city",e.target.value)} placeholder="İstanbul / Kadıköy"/></label></div><div className="tradeSummary"><strong>{data.brand} {data.model}</strong><span>{data.deviceType}{data.storage?` · ${data.storage}`:""} · {data.cosmetic}</span></div><div className="tradeActions"><button type="button" onClick={()=>setStep(2)}>← Geri</button><button className="tradePrimary" type="submit" disabled={!whatsappNumber}>WhatsApp'tan Teklif Al</button></div></section>:null}
 </form>
}